### PR TITLE
pin pandas #2536

### PR DESCRIPTION
**Pull request by marqh**
pin pandas version due to perceived incompatibility with pandas 0.20

### CODE REVIEW

**Comment by marqh** [comment]
#2536 is raised to identify this pinning and work to remedy it

**Comment by ocefpaf** [comment]
@marqh #2538 should fix this. Iris is already pinned to an old `netcdf4-python` version. Pinning `pandas` too is a deal breaker :smile:

**Comment by marqh** [comment]
Hi @ocefpaf 

#2538 looks like a limited scope fix and is certainly better than a pin, I agree

> Iris is already pinned to an old netcdf4-python version.

I don't think this is the case, iris is testing with the latest available netcdf4-python (currently 1.2.7) and passing its test suite

https://github.com/conda-forge/iris-feedstock/blob/master/recipe/meta.yaml#L41
has a pin, but this does not seem to be required, to me

**Comment by ocefpaf** [comment]
> I don't think this is the case

See https://github.com/SciTools/iris/issues/2322

I guess that the tests did not catch the incompatibility that @dkillick found on #2322

**Comment by marqh** [comment]
obsoleted by #2538

**Pull request closed without merging**
