### PR TITLE
Revert "v3.2.0rc0 whats new and version string"

### PR DESCRIPTION
**Pull request by lbdreyer**
Reverts SciTools/iris#4557

This shouldn't have gone onto main!!
This was supposed to target the v3.2.x branch

### CODE REVIEW

**Comment by pp-mo** [comment]
Oh gosh, I should have spotted that  !

Would it not be better to reset the main, than to add a reversion commit ?

**Comment by lbdreyer** [comment]
>Would it not be better to reset the main, than to add a reversion commit ? 

Probably! I added the reversion commit as that it what github creates for you when you click "revert" on a merged PR.

I will try resetting main

**Review by pp-mo — CHANGES_REQUESTED** [review]
I'd prefer to try to reset the branch first, if we can.
It seems to need an admin though, so let's wait + see if @bjlittle can help.

Hi @bjlittle 😉 !

**Comment by bjlittle** [comment]
@lbdreyer Just to let you know that @pp-mo and I successfully reset the `main` branch, so I'm going to close this PR now

Thanks :+1:

**Comment by lbdreyer** [comment]
Something still seems broken on main. The latest [commit](https://github.com/SciTools/iris/commit/d503ce62c41e9d827b91121e4f6395d1fcb6b644) included the pre-commit change and my changes

**Pull request closed without merging**
