### PR TITLE
DOCS: add pin for pydata-sphinx-theme

### PR DESCRIPTION
**Pull request by tkknight**
### Description

* Add a pin for ``pydata-sphinx-theme`` to address #5686.
* Add links to issues/prs for the pins for easy reference
* Remove 2 links from the developers guide sidebar - this cause issues with it expanding the toc instead of going to the page direct.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by tkknight** [comment]
#5698 created as a reminder to unpin.

**Comment by tkknight** [comment]
Closes https://github.com/SciTools/iris/issues/5686.

**Comment by trexfeathers** [comment]
This sort of problem led to to an investigation, and an idea!

SciTools/workflows#38

**Comment by tkknight** [comment]
The a new release of the theme may fix this for use - I will test it.  Hold off merging this for now.

https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.15.2

**Pull request closed without merging**
