### PR TITLE
Add repr_html for CubeLists

### PR DESCRIPTION
**Pull request by DPeterK**
As a (long-delayed) follow-on to a previous PR to add cube html repr (see #2918), this adds html repr functionality to `CubeList` objects. The html repr is designed to be reasonably simple, retaining the content of the original `CubeList` repr while adding an accordion effect that, when a cube in the list is clicked, expands to reveal the html repr of that cube.

### CODE REVIEW

**Comment by DPeterK** [comment]
For want of a properly interactive notebook that demonstrates this in operation, here's a static screengrab of what the repr looks like (with one cube in the list expanded to show the embedded cube repr):

Screenshot 2019-05-15 at 17 05 04

**Comment by bjlittle** [comment]
@DPeterK Fancy doing a re-base?

We just fixed the `travis-ci` tests on `master`, and I'm hoping this will tidy up your CI failures.

Reference https://github.com/SciTools/iris/issues/3349

**Comment by bjlittle** [comment]
Ping @DPeterK :wink:

**Comment by DPeterK** [comment]
@bjlittle ping noted; unfortunately I'm busy now! I'll see what I can do.

**Comment by bjlittle** [comment]
@DPeterK No worries :wink:

**Comment by DPeterK** [comment]
@bjlittle I did it 😁

**Comment by DPeterK** [comment]
... shame the tests still didn't pass :(

**Comment by DPeterK** [comment]
I've updated the CSS for the cubelist repr, including making use of jupyter variables to define elements of the style. This means the cubelist repr will correctly follow jupyter lab themes. When combined with #3380 the cubelist repr now looks like the following:

_Light theme:_
Screenshot 2019-08-27 at 15 32 16

_Dark theme:_
Screenshot 2019-08-27 at 15 31 57

**Comment by bjlittle** [comment]
@DPeterK Awesome, LGTM :+1:

**Pull request merged**
