### PR TITLE
MeshMetadata class.

### PR DESCRIPTION
**Pull request by trexfeathers**
### Description

Implemented the `MeshMetadata` class and tests, in readiness to support the `Mesh` class.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by trexfeathers** [comment]
@bjlittle can you clarify: do we definitely not want to include `node_dimension`, `edge_dimension` and `face_dimension` (and in future `volume_dimension`) in `MeshMetadata._members`? I don't have a good sense of what would (dis)qualify them, and I can't remember if we discussed. Thanks

**Comment by bjlittle** [comment]
@trexfeathers From our discussion, what I recall is that `node_dimension` et al **are** a part of the `MeshMetadata`. However they **do not** participate in `__eq__`.

**Comment by trexfeathers** [comment]
>I _think_ this is true for both strict and lenient

It should be the same behaviour for either, since we do not plan to allow for `None` values of `node_dimension` et al anyway (we fill with a default if no alternative is supplied).

**Comment by trexfeathers** [comment]
Ready for your review again @bjlittle. I've added the extra members for the dimension names.

**Review by bjlittle — APPROVED** [review]
@trexfeathers Awesome LGTM :+1: 

Thanks!

**Pull request merged**
