### PR TITLE
Move to https

### PR DESCRIPTION
**Pull request by bjlittle**
Reference #2227 and this [comment](https://github.com/SciTools/iris/pull/2227#discussion_r85759229)

### CODE REVIEW

**Comment by ajdawson** [comment]
Kind-of annoying that the tests take much longer now, seems to be since the nose timeout change, but I'm not sure why that would be the case for all test runs... Worth investigating?

**Comment by bjlittle** [comment]
Yeah, `TEST_TARGET=default` is just painful now ... but at least the tests are stable.

I'll create an issue.

**Comment by bjlittle** [comment]
@ajdawson See #2229 ... great we now have 200 open issues. Now that is annoying.

**Comment by dkillick** [comment]
> great we now have 200 open issues

Haha, 199 again! :facepunch:

**Comment by bjlittle** [comment]
@ajdawson Fancy taking this PR on?

**Comment by bjlittle** [comment]
Thanks @ajdawson

**Pull request merged**
