### PR TITLE
improved example clarity

### PR DESCRIPTION
**Pull request by marqh**
An improvement to the clarity of a code example

re: https://github.com/SciTools/iris/pull/1892#discussion_r49204959

### CODE REVIEW

**Comment by rhattersley** [comment]
*(Bike-shedding warning :wink:)*

I like your first commit more. The first-different concept makes a lot of sense - without it the code would go wrong if the series subsequently crossed (which is more likely now that you're using is-close rather than strict equality).

**Comment by marqh** [comment]
> I like your first commit more.

I can see why; however, the indexing is wrong and the example doesn't run, I get an invalid slice. 

I'm clearly missing something, tbc...

**Comment by rhattersley** [comment]
> the indexing is wrong and the example doesn't run

The line:

    first_different = np.where(~close)[0]

needs an extra `[0]`, so it becomes:

    first_different = np.where(~close)[0][0]

**Comment by ajdawson** [comment]
Since the two model runs you are using are described in [1], which is also referenced in the example header, wouldn't it be better just to select the period 1860-1999 knowing that this is the correct period, rather than inspect data values to determine this? Inspecting data values seems a little unusual to me when we have the metadata available.

[1] Johns et al (2011) Climate change under aggressive mitigation: the ENSEMBLES multi-model experiment. Climate Dynamics.

**Comment by rhattersley** [comment]
> ... wouldn't it be better just to select the period 1860-1999 knowing that this is the correct period, rather than inspect data values to determine this?

That's a *much* better idea. :+1: :+1: After all, making use of metadata is pretty much the point of Iris!

How about:
```python
    constraint = iris.Constraint(time=lambda cell: cell.point.year <= 1999)
    with iris.FUTURE.context(cell_datetime_objects=True):
        observed = a1b_mean.extract(constraint)
```

**Comment by bjlittle** [comment]
@marqh :+1: for the change ... 

But how about locking the constraint down to exactly match the comment i.e.

```python
    # Constrain the period 1860-1999 and extract the observed data from a1b
    constraint = iris.Constraint(time=lambda cell: 1860 <= cell.point.year <= 1999)
    with iris.FUTURE.context(cell_datetime_objects=True):
        observed = a1b_mean.extract(constraint)
```

**Comment by bjlittle** [comment]
Thanks @marqh :+1:

**Pull request merged**
