### PR TITLE
Single Merge for load_cube

### PR DESCRIPTION
**Pull request by rcomer**
See #3334.  Just removed the first merge to see if anything breaks!

### CODE REVIEW

**Comment by bjlittle** [comment]
@rcomer Thanks for this.

Yup, so it appears there is a double merge being performed here within `iris.load_cube` :scream: 

Once by the underlying `iris.cube._CubeFilter.merged` for the cubes associated with the matching constraint. Then once afterwards within `iris.load_cube` itself, when it calls `merge_cube` on the `iris.cube.CubeList` returned from the filter.

This current functionality all works just fine, but is really a tad inefficient. Plus, it results in a not so informative traceback from `merge_cube` due to the prior (and unnecessary) `merge`.

With regards to the example given in https://github.com/SciTools/iris/issues/3334, we have a traceback that goes from:
```python
iris.exceptions.ConstraintMismatchError: failed to merge into a single cube.
  cube.shape differs: (3, 4) != (2, 4)
```
to:
```python
ConstraintMismatchError: failed to merge into a single cube.
  Coordinates in cube.aux_coords (non-scalar) differ: baz.
```
For me, the second traceback wins the day. From a users perspective, they have a fighting chance to understand what the heck is wrong.

LGTM :+1:

**Comment by bjlittle** [comment]
@rcomer I'm more than happy to merge this, but first I need to fix the master travis-ci tests, which are failing at the moment :cry: 

So, let me do that first, then we can merge this with confidence. Does that sound like a reasonable plan?

**Comment by rcomer** [comment]
@bjlittle sounds good to me 👍

**Comment by bjlittle** [comment]
@rcomer Fancy doing a re-base?

We just fixed the travis-ci tests on master, and I'm hoping this will tidy up your CI failures.

Reference #3349

**Comment by rcomer** [comment]
Rebased 🤞

**Comment by bjlittle** [comment]
It's been a long day, clumsily clicked the thumbs-down emoji by mistake :blush:

**Comment by bjlittle** [comment]
@rcomer Awesome, thanks :+1:

**Pull request merged**
