### PR TITLE
Avoid computing lazy scalar coordinates when printing a Cube

### LINKED ISSUE #5743: Cube printout should not compute lazy scalar coordinates
To address #5723

We've accepted in the discussion there that we really don't want complex lazy calculations performed each time you print a cube.  
Nor would we like it to "realise" a scalar coordinate, so it only happens once, since you really wouldn't expect printing to _modify_ a cube.

It seems reasonable instead to just print something like "complex_scalarvalue_coord: \<lazy\>" in this case.
The user could of course realize it, if + when the value is actually _wanted_. 

Note: IMHO this is not a major change, and can just be done
  -- we have changed printout format before without considering it a breaking change.
Also relevant here : _most_ scalar coords, ones loaded from files, are not lazy, since #5229 
( so in many/most cases, adopting this _won't_ change the output )

### PR DESCRIPTION
**Pull request by fnattino**
### Description

The point and bound of a scalar coordinate are printed out only when the corresponding data is not lazy. Fix #5743. 

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by pp-mo** [comment]
Note: we are planning now a minor "interim" release to include #5833  and #5740
Ping @trexfeathers can we fit this in ?

Status : I think ..
  * this basically works
  * a fix for #5743 is very desirable
  * the new behaviour (coords print differently ) should not be considered a breaking change
  * the broken test is a simple fix
  * however, some more specific tests would be a good thing

**Comment by pp-mo** [comment]
@fnattino if it's ok with you, I'm going to take this + add a couple of commits to fix + extend the testing slightly.
Then we can bank it.
Because we're intending to cut Iris 3.9.0.rc0 today

**Comment by trexfeathers** [comment]
>Because we're intending to cut Iris 3.9.0.rc0 today

tomorrow*

**Comment by ESadek-MO** [comment]
Completed in #5896 .

**Comment by fnattino** [comment]
Many apologies for the lack of response, I have been busy with other things recently and away for the last week or so. Thanks a lot @pp-mo for picking this up, happy to hear #5896 has been merged.

**Comment by pp-mo** [comment]
> Many apologies for the lack of response, I have been busy with other things recently and away for the last week or so. Thanks a lot @pp-mo for picking this up, happy to hear #5896 has been merged.

No problem at all.  Thanks for contributing !

**Pull request closed without merging**
