### PR TITLE
Heuristically determine if saving a NetCDF attribute as a string or unicode.

### PR DESCRIPTION
**Pull request by pelson**
An alternative approach to #2133.

### CODE REVIEW

**Comment by pelson** [comment]
Please discuss this as part of #2133, rather than forking the conversation in this PR.

**Comment by marqh** [comment]
```
(unpinmpl) 
> python -s -m unittest iris.tests.integration.test_netcdf
Ran 20 tests in 2.010s
OK


(unpinmpl)
> python -s -m unittest iris.tests.test_netcdf
Ran 56 tests in 14.233s
OK

```


looking good to me :)

**Comment by marqh** [comment]
https://github.com/SciTools/iris/pull/2133#issuecomment-252014830

**Comment by pelson** [comment]
Have updated this to behave consistently for all cases of attribute creation.

**Comment by marqh** [comment]
@QuLogic in #2133 you requested that the test change be aimed at 1.10.x

My view is that this change is more suitable for Iris, explicitly controlling behaviour, rather than putting an 'ignore difference' pattern into our testing strategy.

Either of these would be slightly challenging to label a 'bugfix' but I feel more strongly about this one.  whilst we are trying to preserve behaviour through changes in netcdf4-python, the result could be that people who already use a more up to date version of netcdf4-python than we test would see this as a behaviour change.

as such I'm not comfortable with pushing this to 1.10.x as a bug fix

please may you consider this and share with us your views on why it is so desirable to address this issue for iris 1.10?

thank you
mark

**Comment by marqh** [comment]
@pelson 
I'm pretty happy with this change, please may we have a what's new entry for it?

thank you
mark

**Comment by pelson** [comment]
I now wish to make it clear that this is my preferred approach for addressing https://github.com/SciTools/iris/pull/2133#issuecomment-251421428. The behaviour change that this is addressing covers an untested netCDF4-python, and maintains the longstanding behaviour of Iris. With this change, Iris may make the following statement about saving of NetCDF attributes: "if you provide a string that cannot be encoded as ASCII, we will save it as an NC_STRING, otherwise we will save it as NC_CHAR in all cases".

**Comment by pelson** [comment]
No tests were added or deleted in this PR simply because this is a "continuation of behaviour" change - essentially all functionality should continue as was originally intended at the time of writing the original functionality.

@marqh - if you are ready to merge, please merge. :+1:

**Pull request merged**
