### PR TITLE
Perserve dtype of source cube with area weighted regridder

### PR DESCRIPTION
**Pull request by djkirkham**
This PR makes the AreaWeighted regridding scheme use the data type of the source cube for the output cube, bringing it in line with Nearest and Linear regridding schemes.

I have made no effort to fix failing tests yet.

### CODE REVIEW

**Comment by cpelley** [comment]
Thanks @djkirkham, this is in keeping with discussions previous in #1478 and with the changes proposed in #2058.  Hopefully it does not effect too may tests.....

**Comment by marqh** [comment]
Hi @djkirkham 

you've added some npy files here, but we've recently been trying to remove all these

Please may you rebase and refactor your tests if required, to avoid putting npy files into the source tree?
thank you

**Comment by djkirkham** [comment]
@marqh This PR doesn't add any .npy files, just modifies existing ones (I tried removing them but predictably the tests failed). If the work to remove the .npy files is ongoing, feel free to hold off on merging this and I'll rebase and refactor to remove the reliance on the files.

**Comment by marqh** [comment]
> This PR doesn't add any .npy files, just modifies existing ones (I tried removing them but predictably the tests failed). If the work to remove the .npy files is ongoing, feel free to hold off on merging this and I'll rebase and refactor to remove the reliance on the files.

Hi @djkirkham 

i had not noticed that this targets master, where as #2213 was merged onto v1.11.x

i've put up #2236 to address this.  perhaps you could wait for this to be merged, then rebase?

apologies for the faff and confusion

mark

**Comment by pelson** [comment]
@djkirkham - is this PR still wanted? I noticed you updated it recently...

If you want me to review it, please feel free to assign me as a reviewer (or just ping me). If not, let's close this.

**Pull request merged**
