### PR TITLE
Mergeback 2.2.x

### PR DESCRIPTION
**Pull request by pp-mo**
Brings #3247 to master

### CODE REVIEW

**Comment by bjlittle** [comment]
@pp-mo LGTM, thanks for doing this... once travis-ci is happy, then so am I :+1:

**Comment by pp-mo** [comment]
Now waiting on #3257, to fix v2.2.x (!)
ping @bjlittle

**Comment by bjlittle** [comment]
@pp-mo Just merged https://github.com/SciTools/iris/pull/3257 to unblock you... time to rebase, and we'll take it from there :smile:

**Comment by pp-mo** [comment]
ping @bjlittle all good !

**Comment by bjlittle** [comment]
@pp-mo Awesome, thanks! :smile:

**Pull request merged**
