### PR TITLE
Fix concatenate tests

### LINKED ISSUE #2715: Fix concatenate test failures
cube data fill value is wrong
- [ ] FAIL: test_concat_masked_2y2d_int16 (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_concat_masked_2y2d_int16_with_concrete_and_lazy (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_concat_masked_2y2d_int16_with_lazy_and_concrete (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__all_None (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__different_non_None (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__mixed (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_fill_value_invariant_to_order__same_non_None (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_masked_and_unmasked__fill_value_equal (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_masked_and_unmasked_int16__fill_value_equal (iris.tests.test_concatenate.Test2D)
- [ ] FAIL: test_masked_with_data_fill_value_difference_on_arrays (iris.tests.test_concatenate.Test2D)

### PR DESCRIPTION
**Pull request by djkirkham**
Closes #2715 

I've initially reverted the file to how it was in version v1.13 since the file is now more similar to that version. I've then re-added tests which I thought still had value.

### CODE REVIEW

**Comment by pelson** [comment]
@djkirkham - are we still testing the ability to concatenate cubes of different dtypes?

**Comment by djkirkham** [comment]
@pelson No, but following out offline discussion I'll re-add them

**Comment by djkirkham** [comment]
@pelson Actually, it turns out we were never testing that. The tests that specify a dtype (the int16 ones) specify the same dtype for both cubes.

**Comment by pelson** [comment]
Do some result files need moving / removing?

**Pull request merged**
