### PR TITLE
pp.py - add new example of string comparison

### PR DESCRIPTION
**Pull request by nhsavage**
Relates to issue #3063 - adds one extra example to doctests for iris.fileformats.pp.STASH

### CODE REVIEW

**Comment by nhsavage** [comment]
I'll get on to the CLA ASAP. I also need to fix the actual doctest I added - I blindly copied and pasted code from issue.
I need to work out how to run doctests myself from this Windows box....

**Comment by pelson** [comment]
First things first: Congratulations on your first Iris PR (pull request)! :tada: :beers: :tada:

With regards to the CLA, I've just added you to the list at https://github.com/SciTools/scitools.org.uk/pull/208. We should find that percolate through to the CLA checker in the next hour or so (so that we get a green tick, rather than a scary red cross next to the SCiTools-CLA-checker. :x: :arrow_right: :heavy_check_mark: 

Finally, regarding the change itself: looks great! It may make sense for us to target the ``v2.1.x`` branch, rather than master, that way we would get this in the ``v2.1.1`` release if we chose to make one. It is a relatively painless process (with luck) on your side if you want to give it a shot, otherwise I can do it from my side:

```
# Make sure you actually have a remote called upstream...
git fetch upstream

# Take the 2 commits you've made, and apply them to a different "base"
git rebase upstream/v2.1.x

# That magic line changed the position of the commits in the Iris repository,
# which is the same as changing the history (for your 2 commits).
# We therefore need to "force" push the changes to your GitHub remote.
git push -f origin stasheq_doc
```

That is all that is needed on the git front. On the **GitHub** side of things, hit "edit" on this PR, and change the base branch to ``v2.1.x`` instead of ``master``.

Don't worry if you mess any of this up, I've taken a copy of your PR just in case it goes wrong, and I'm on hand if you need a pointer. :wink:

**Comment by nhsavage** [comment]
Thanks I'll have a go tonight

Nick

**Comment by nhsavage** [comment]
I think I have done the right thing, although I'm having problems trying to work out if I have.

**Comment by pelson** [comment]
> I think I have done the right thing, although I'm having problems trying to work out if I have.

Not quite I don't think. Did you ``git rebase upstream/v2.1.x``? It looks like you might have done ``git rebase upstream/master`` accidentally?

**Comment by nhsavage** [comment]
hmm. I thought I had copied and pasted the command you sent but possibly not. I won't have time to look at this tonight though as it seems quite fiddly to undo a rebase. How do I check what I actually did and how can I test the rebase before pushing?

**Comment by nhsavage** [comment]
would it be easier to make a new branch from upstream/v2.1.x instead of master?

**Comment by pelson** [comment]
I've just merged this in #3072. Thanks for persevering @nhsavage, and congratulations on your first commit! 👍

**Pull request closed without merging**
