### PR TITLE
Add iris.FUTURE.netcf_promote=False warning

### LINKED ISSUE #1740: Warn when iris.FUTURE.netcdf_promote=False

### PR DESCRIPTION
**Pull request by lbdreyer**
Closes #1740.

### CODE REVIEW

**Comment by rhattersley** [comment]
The new warning is causing some count-the-warnings checks to fail. I suggest you modify those tests to run under with `netcdf_promote=True`, and add your own tests to check just this warning.

**Comment by rhattersley** [comment]
I've tried restarting the Travis-CI job but nothing seems to be happening. Perhaps you could push up an amended commit instead?

**Comment by lbdreyer** [comment]
I amended the commit.

I don't get the errors it got when I run the tests locally.

**Comment by rhattersley** [comment]
> I don't get the errors it got when I run the tests locally.

Looks like the modification of `iris.FUTURE.netcdf_promote` in `lib/iris/tests/unit/unit/test_suppress_unit_warnings.py` is leaking out and affecting other tests. https://github.com/lbdreyer/iris/pull/2 should fix it.

**Comment by lbdreyer** [comment]
:tada: Tests are now passing!! :tada:

**Pull request merged**
