### PR TITLE
Adaptions for Matplotlib 3.6

### PR DESCRIPTION
**Pull request by trexfeathers**
### Description

These changes address a Matplotlib deprecation warning, and should get the overnight benchmarks working again.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Review by pp-mo — APPROVED** [review]
This looks cool, though I did have a bit of a wobble about requiring Matplotlib >= 3.5.
That is now ~10months old. But I guess this is anyway not an actual Iris dependency, its only for CI, 
so I think that is fine.

**Comment by pp-mo** [comment]
Nice work @trexfeathers .  We'll see how it goes tomorrow morning !

**Comment by trexfeathers** [comment]
> This looks cool, though I did have a bit of a wobble about requiring Matplotlib >= 3.5. That is now ~10months old. But I guess this is anyway not an actual Iris dependency, its only for CI, so I think that is fine.

This is genuine. When this is released (December), Matplotlib 3.4 will not be usable with Iris

**Comment by pp-mo** [comment]
Ok, hadn't really thought of it that way.
But by then, mpl 3.5 will be  > 1 year old.

**Comment by trexfeathers** [comment]
This raises interesting questions about proactively responding to deprecation warnings. We typically don't spot them until the deprecation fully happens, and therefore don't experience the problem of very 'young' pins. In this case I spotted the warning while investigating and chose to action it, introducing this different problem!

**Pull request merged**
