### PR TITLE
Remove deprecated module interpolate.py

### LINKED ISSUE #2644: Remove deprecated lib/iris/analysis/interpolate.py
The module `lib/iris/analysis/interpolate.py` was deprecated in 1.10.

Replacement: use methods cube.regrid() and cube.interpolate() instead.

https://github.com/SciTools/iris/blob/master/lib/iris/analysis/interpolate.py#L22

### PR DESCRIPTION
**Pull request by dkillick**
Closes #2644

### CODE REVIEW

**Comment by corinnebosley** [comment]
@dkillick You've got a 'from iris.tests.test_interpolation import normalise_order' left in iris.tests.test_analysis_calculus.py.

**Comment by dkillick** [comment]
To avoid importing `iris.tests.test_interpolation.normalise_order` in `iris.tests.analysis.test_interpolate.py` I've just deleted this test module. The tests contained in it fail locally regardless of whether I introduce `normalise_order` back into the test module or not, and we're going to need to delete this test module anyway as part of upcoming work, so I thought I'd get ahead.

**Comment by corinnebosley** [comment]
@dkillick Hang on a minute, are we getting rid of all iris.analysis.interpolate code and just keeping regrid stuff instead?

**Comment by dkillick** [comment]
@corinnebosley Travis has gone green!! :grinning: :tada:

**Comment by corinnebosley** [comment]
Boom!

**Pull request merged**
