### PR TITLE
Expose method of regridding to Regridder API.

### PR DESCRIPTION
**Pull request by bjlittle**
This PR exposes the `method` of regridding to the API of the new `RectilinearRegridder` class.

The `method` may be `linear` or `nearest`, where the default behaviour is `linear`.

The `nearest` functionality has not yet been implemented. This PR exposes the means to select the method of regridding. ~~A following PR will implement and test the required underlying nearest-neighbour functionality.~~

This PR essentially:
 + Re-brands the `Rectilinear._regrid_bilinear_array` method to be `Rectilinear._regrid`,
 + Adds the **new** `method` argument to the `Rectilinear.__init__` and `Rectilinear._regrid` methods,
 + Deals with the testing fall-out from the above changes.

The addition of the `method` argument aligns the new `RectilinearRegridder` API with the signature and usage of the associated `RectilinearInterpolator` API.

### CODE REVIEW

**Comment by bjlittle** [comment]
@rhattersley Can I tempt you again? :pray:

**Comment by rhattersley** [comment]
This PR would make more sense if the new `method` argument actually did anything (and had some corresponding tests). To avoid repeating existing work, how about you just roll your next PR straight into this one. It'll get a bit chunky but at least it won't waste time.

**Comment by bjlittle** [comment]
Yup, will do, thanks @rhattersley

**Comment by bjlittle** [comment]
@rhattersley hooked in the underlying nearest regridding and ported most tests for coverage.

A following PR will join up to `Nearest` class to expose the `regridder` method.

Another follow-on PR will move `_linear.py` to `_regrid.py` and move the tests from `tests/analysis/test_linear.py` down to `tests/unit/analysis/linear/test_RectilinearRegridder.py`

**Comment by bjlittle** [comment]
It's totally `_` test name madness ... so all is forgiven.

**Comment by rhattersley** [comment]
I'm kinda disappointed that I can't find anything really wrong with this! :wink: It looks like a big PR, but the actual code change is really small so I guess that makes sense. So ... I'm :+1: to merge.

Nice job @bjlittle! :grinning:

**Comment by bjlittle** [comment]
Whoop! Thanks @rhattersley :smile:

**Pull request merged**
