### PR TITLE
TEST: Ensure PP FF and NetCDF data proxies are pickleable

### PR DESCRIPTION
**Pull request by cpelley**

### CODE REVIEW

**Comment by cpelley** [comment]
driven by #2262

**Comment by pelson** [comment]
Easy to merge. 👍 
Out of interest, you've ensured you can pickle them, but do they *unpickle*? (a question for another PR maybe?)

@bjlittle - please merge when this is not inconvenient for the dask branch.

**Comment by cpelley** [comment]
> Out of interest, you've ensured you can pickle them, but do they unpickle?

Good point, I'll add another PR after merge if you prefer.  Thanks @pelson

**Comment by cpelley** [comment]
Thanks @pelson

**Pull request merged**
