### PR TITLE
Merge back v1.11.x

### PR DESCRIPTION
**Pull request by marqh**
return v1.11.x changes to master

### CODE REVIEW

**Comment by bjlittle** [comment]
@marqh You should rebase to include https://github.com/SciTools/iris/pull/2240 when it's merged ... particularly because it adjusts the `process-timeout` in our `nose` tests and significantly reduces the runtime of the `TEST_TARGET=default` runners ... thanks goodness! From `~18m` down to `<8m` :smile:

**Comment by QuLogic** [comment]
Merges back from release branches shouldn't need rebasing...

**Comment by bjlittle** [comment]
@marqh Is using a branch cut from `v1.11.x` to merge back here in this PR ...

**Comment by QuLogic** [comment]
Yes, that only requires a fast-forward merge.

**Comment by marqh** [comment]
i have pulled in recent changes from v1.11.x

please ensure that this is included with all teh commit, if appropriate

do not 'squash and merge'

**Pull request merged**
