### PR TITLE
Ensure nsigma_slice is a tuple.

### LINKED ISSUE #1593: Biggus v0.9.0 breaks sigma_over_z
All other Ocean Dimensionless Coordinates are OK.  Only sigma_over_z is broken when using the latest biggus.  I think that @pelson already expected this, but I am reporting anyways :grinning:

```python
>>> url = "http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/ncom/ncom_sigma_over_z.nc"
>>> cube = iris.load_cube(url, 'sea_water_potential_temperature')
>>> coord = cube.coord('sea_surface_height_above_reference_ellipsoid')
>>> coord
<repr(<iris.coords.AuxCoord at 0x7f487f153250>) failed: IndexError: index slice(None, None, None) is out of bounds for axis 0 with size 1>
```

Full notebook:

http://nbviewer.ipython.org/gist/ocefpaf/1b7cf19e1e6c783d9edc#ocean_sigma_coordinate

### PR DESCRIPTION
**Pull request by rhattersley**
Fixes #1593 - @ocefpaf can you confirm?

### CODE REVIEW

**Comment by bjlittle** [comment]
SInce it was a hum-dinger :hankey: , perhaps add a comment to mark the significance?

**Comment by rhattersley** [comment]
I guess we could, but there are plenty of other places where we do the same thing - it's pretty standard practice.

**Comment by rhattersley** [comment]
Updated to fix `nsigma_slice_bounds` as well.

**Comment by rhattersley** [comment]
Travis has given it the :+1: ... @ocefpaf?

**Comment by ocefpaf** [comment]
:+1:

It seems OK to me, but I cannot test it right now, my internet is choking on that dataset :unamused:

**Comment by rhattersley** [comment]
For what it's worth, I didn't fancy trying to download 800 MB of coordinate data either, so I tested it with a cut-down version of the cube and it didn't crash.
```python
>>> import iris
>>> url = "http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/ncom/ncom_sigma_over_z.nc"
>>> cube = iris.load_cube(url, 'sea_water_potential_temperature')
>>> cube
<iris 'Cube' of sea_water_potential_temperature / (degC) (time: 1; -- : 40; -- : 1280; -- : 2048)>
>>> cube = cube[:, :, :10, :10]
>>> cube
<iris 'Cube' of sea_water_potential_temperature / (degC) (time: 1; -- : 40; -- : 10; -- : 10)>
>>> coord = cube.coord('sea_surface_height_above_reference_ellipsoid')
>>> print(coord)
AuxCoord(array([[[[    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         ..., 
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ]],

        [[    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         ..., 
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ]],

        [[    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         ..., 
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ]],

        ..., 
        [[-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         ..., 
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062]],

        [[-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         ..., 
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906]],

        [[-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         ..., 
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406]]]], dtype=float32), standard_name='sea_surface_height_above_reference_ellipsoid', units=Unit('m'), attributes={'positive': 'up'})
```

**Comment by ocefpaf** [comment]
Interesting, I was trying to do:

```python
>>> import iris
>>> url = "http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/ncom/ncom_sigma_over_z.nc"
>>> cube = iris.load_cube(url, 'sea_water_potential_temperature')
>>> coord = cube.coord('sea_surface_height_above_reference_ellipsoid')
>>> print(coord.points[0, :, 0, 0])
```

to get one profile and I hope it would be as fast as your approach, but it wasn't...  Maybe it is just my :hankey: internet.

**Comment by rhattersley** [comment]
> `coord.points[0, :, 0, 0]`

Coordinates aren't as lazy as cubes (yet?). So that will try to download *all* the data and then extract a one profile.

**Comment by ocefpaf** [comment]
Ah!!!  So it makes sense to slice the cube as much as you can before loading them, right?  Thanks a lot!

**Comment by pelson** [comment]
Needs backporting to v1.8.x. @bjlittle - do you want to do that or shall I (no PR needed)?

**Comment by bjlittle** [comment]
@pelson Thanks, I'll cherrypick the commit as recommended.

**Comment by pelson** [comment]
Cool. For the record, please add the commit sha to this ticket as a comment.

**Comment by bjlittle** [comment]
Cherry-picked master commit 02cdf3ede687b829cbe964c2132266983c71340e into v1.8.x commit 740e96971685ed049a601bb3174c9ac6d64552e6

**Pull request merged**
