### PR TITLE
Update documentation references

### PR DESCRIPTION
**Pull request by jeixav**
- 2010 submission published
 - add digital object identifiers

### CODE REVIEW

**Comment by pelson** [comment]
Thanks @jeixav.

**Comment by pelson** [comment]
Hi @jeixav. I'd like to merge this PR, but would like to fix the commit so that we can reference it back to you. It appears that your git configuration might be out (your name and email are both in the email field). 

Two things:
 * Are you able to amend your commit with the correct details?
 * Could you sign the scitools contributor license as described at http://scitools.org.uk/governance.html?

Thanks!

**Comment by jeixav** [comment]
Hi @pelson. Sorry about the bad email configuration. I think this is now fixed. For the CLA, I am still trying to get approval; see https://github.com/SciTools/cartopy/pull/869#issuecomment-302579873.

**Comment by pelson** [comment]
Given the limited docs change, I'm happy to take this on without the CLA - please do keep going on getting approval, as your contributions are really appreciated. 👍

**Comment by jeixav** [comment]
That is reasonable @pelson; this contribution is minimal.

I contacted the Environment Canada Intellectual Property Office. It seems the Director General of the Atmospheric Science and Technology Directorate can approve signature of the CLA.

If anyone from Environment Canada or the Government of Canada signs the CLA, please let me know.

**Pull request merged**
