### PR TITLE
Sparse interpolation over sub-ndims.

### PR DESCRIPTION
**Pull request by bjlittle**
Fix to allow sparse matrix interpolation over fewer dimensions than the data ndims.

### CODE REVIEW

**Comment by bjlittle** [comment]
@rhattersley This is looking good ... waiting on Travis for a clean bill of health ...

I can confirm this PR is working for a troublesome euro-bgd pressure job :smile:

**Comment by rhattersley** [comment]
> waiting on Travis for a clean bill of health ...

`FAIL: test_no_coord_system (iris.tests.test_analysis.TestProject)`

**Comment by bjlittle** [comment]
This seems to be a cartopy/proj.4 issue and nothing to do with the changes of this PR ... :confused:

**Comment by rhattersley** [comment]
That's what I'd hoped, but I couldn't (quickly) see it happening with other PRs ... ?

**Pull request merged**
