### PR TITLE
Remove dask docs from developer's guide

### PR DESCRIPTION
**Pull request by dkillick**
No docs are better than wrong docs and the dev guide page on dask integration to Iris was seriously out of date. Removing this page does not imply that dask does not need a dev guide page at all, however. Instead, when time allows, a page of similar content that remains factually accurate should be introduced.

Partly deals with #2939.

### CODE REVIEW

**Comment by dkillick** [comment]
> Did you check

Nope! I'll do that.

**Comment by dkillick** [comment]
> references to this file were removed

References to this file have been removed.

**Comment by QuLogic** [comment]
> @dkillick dkillick added this to the v2.0.0 milestone 12 hours ago

Should target `v2.0.x` if you want it to go into 2.0.0.

**Comment by pelson** [comment]
Agreed. @dkillick could you rebase against v2.0.x please?

**Comment by pelson** [comment]
Merged with 88d1a901 into v2.0.x.

**Pull request closed without merging**
