### PR TITLE
Make further topics obviously different

### PR DESCRIPTION
**Pull request by trexfeathers**
### Description

A very simple way to make it obvious in a TOC-tree that `Further Topics` is not just a page, but a subsection of its own.

I chose to edit the title itself, rather than an alias in the existing TOC-tree, so that this will also apply if included in other TOC-trees. I also kinda like the title being this way 😁

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Review by ESadek-MO — COMMENTED** [review]
I wonder if we should apply this to all nested toc-members? I found the below all expand out when clicked:
- Dask Best Practices
- Mesh Support
- Gallery

I think we should maintain consistency throughout the docs, which'd also mean we'd have to remember the format if creating new nests later down the line (which is a good habit, just thought it was worth noting).

It's a good idea though, and a simple change!

**Comment by tkknight** [comment]
There maybe an option in the pydata theme to do this.  I will check.

**Comment by trexfeathers** [comment]
> There maybe an option in the pydata theme to do this. I will check.

There is! I'm just checking the blame for why we turned it off originally...

**Comment by trexfeathers** [comment]
> > There maybe an option in the pydata theme to do this. I will check.
> 
> There is! I'm just checking the blame for why we turned it off originally...

@tkknight looks like this line was introduced when we introduced PyData Theme (#4661). Would you be comfortable with turning it off?

https://github.com/SciTools/iris/blob/2bfaebda62b22d3203cfa737a5f017d68800a5c8/docs/src/conf.py#L294

[ref](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/navigation.html#remove-reveal-buttons-for-sidebar-items)

**Comment by tkknight** [comment]
Try removing this line and rebuild the docs. 

https://github.com/SciTools/iris/blob/main/docs/src/conf.py#L294

**Comment by trexfeathers** [comment]
I like it

image

**Review by ESadek-MO — CHANGES_REQUESTED** [review]
I really like this new version. Adds a lot of functionality with a single line of code imo, and doesn't seem to break anything. 

Just need to add a whatsnew then I'm happy for this to go!

**Review by ESadek-MO — APPROVED** [review]
Super happy with this, thanks @trexfeathers!

**Pull request merged**
