### PR TITLE
1.10- whats new

### PR DESCRIPTION
**Pull request by marqh**
compiled the what's new for 1.10

### CODE REVIEW

**Comment by ajdawson** [comment]
Missing an entry for #2075, my bad...

**Comment by ajdawson** [comment]
Also, should this be targeted on the 1.10.x branch?

**Comment by ajdawson** [comment]
An extra what's new entry is in #2093.

**Comment by marqh** [comment]
> Also, should this be targeted on the 1.10.x branch?

indeed it should, I'll aim to close this branch and wait for any identified what's new entries missing

i'll try to raise a PR against 1.10.x as soon as I sensibly can

thanks @ajdawson

**Pull request closed without merging**
