### PR TITLE
Mergeback the v3.2.x branch onto main

### PR DESCRIPTION
**Pull request by lbdreyer**
### Description
Mergeback after the v3.2.1 release.

Note: to merge this in we will need to switch off the setting that only allows "squash and commit" merges, as we have done with previous mergebacks

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Review by trexfeathers — APPROVED** [review]
This has everything I would expect to see, and nothing I wouldn't expect to see.

>Note: to merge this in we will need to switch off the setting that only allows "squash and commit" merges, as we have done with previous mergebacks

I don't have this power, so I'll just leave my approval here.

**Comment by pp-mo** [comment]
> > Note: to merge this in we will need to switch off the setting that only allows "squash and commit" merges, as we have done with previous mergebacks

> I don't have this power, so I'll just leave my approval here.

Ping @bjlittle.  I think you are the one with "the power" ? 🏋️‍♂️

**Comment by pp-mo** [comment]
Ping @bjlittle : I think you are the one with "the power" ? 🏋️

**Review by bjlittle — APPROVED** [review]
@lbdreyer Awesome, thanks! LGTM 👍

**Pull request merged**
