### PR TITLE
Use numpy.linspace to generate grids built with reference point and spacings 

### LINKED ISSUE #3559: Improve floating point representation in generation of regular grids that use a reference point and spacings
Some regular grids in Iris are generated from a reference point in x-y space along with an x-spacing and a y-spacing. 

The way this is currently implemented uses numpy.arange as follows:

https://github.com/SciTools/iris/blob/b2ce2a34e2eef7e3d6203c77ada7ed4ce89e3145/lib/iris/coords.py#L2293

Where **zeroth** is the value *prior* to the first point value, **step** is the numeric difference between successive point values and **count** is the number of point values.

As discussed at https://stackoverflow.com/questions/47243190/numpy-arange-how-to-make-precise-array-of-floats (amongst other places), this results in grids that contain fractionally incorrectly represented floats. E.g. using zeroth = 352.84, step = 0.11, count = 146, it produces the following array:

`array([352.95   , 353.06   , 353.17   , 353.28   , 353.39   , 353.5    ,
       353.61002, 353.72   , 353.83002, 353.94   , 354.05002, 354.16   ,
       354.27002, 354.38   , 354.49002, 354.6    , 354.71002, 354.82   ,
       354.93002, 355.04   , 355.15002, 355.26   , 355.37003, 355.48   ,
       355.59003, 355.7    , 355.81   , 355.92   , 356.03   , 356.14   ,
       356.25   , 356.36002, 356.47   , 356.58002, 356.69   , 356.80002,
       356.91   , 357.02002, 357.13   , 357.24002, 357.35   , 357.46002,
       357.57   , 357.68002, 357.79   , 357.90002, 358.01   , 358.12003,
       358.23   , 358.34003, 358.45   , 358.56   , 358.67   , 358.78   ,
       358.89   , 359.     , 359.11002, 359.22   , 359.33002, 359.44   ,
       359.55002, 359.66   , 359.77002, 359.88   , 359.99002, 360.1    ,
       360.21002, 360.32   , 360.43002, 360.54   , 360.65002, 360.76   ],
      dtype=float32)`

One consequence of this is that two grids that *should* be identical cannot be manipulated together (e.g. subtract one from the other) if one is fully specified from a source file, and the other is generated in this way from a reference point and spacings.

A potential solution as mentioned in the above link is to use and approach involving numpy.**linspace** instead such as:

`start = zeroth + step`
`end = zeroth + (count * step)`
`points = np.linspace(start, end, num=count, dtype=np.float32)`

Using the same values of zeroth, step and count as above this produces the following array:

`array([352.95, 353.06, 353.17, 353.28, 353.39, 353.5 , 353.61, 353.72,
       353.83, 353.94, 354.05, 354.16, 354.27, 354.38, 354.49, 354.6 ,
       354.71, 354.82, 354.93, 355.04, 355.15, 355.26, 355.37, 355.48,
       355.59, 355.7 , 355.81, 355.92, 356.03, 356.14, 356.25, 356.36,
       356.47, 356.58, 356.69, 356.8 , 356.91, 357.02, 357.13, 357.24,
       357.35, 357.46, 357.57, 357.68, 357.79, 357.9 , 358.01, 358.12,
       358.23, 358.34, 358.45, 358.56, 358.67, 358.78, 358.89, 359.  ,
       359.11, 359.22, 359.33, 359.44, 359.55, 359.66, 359.77, 359.88,
       359.99, 360.1 , 360.21, 360.32, 360.43, 360.54, 360.65, 360.76])`

### PR DESCRIPTION
**Pull request by gcaria**
Close #3559

A very simple fix taken straight from the issue's only comment.

### CODE REVIEW

**Comment by rcomer** [comment]
Hi @gcaria, thanks for this.  We are currently having multiple problems with our Cirrus CI testing, so the test output will be showing a whole raft of failures that are not linked to your change.  To get everything working again, we need to merge #4108, #4104, #4112 and probably something to address #3993.  Once all that’s done, you can rebase and someone can have a proper look at this.

Again, thanks for your contribution!

**Comment by rcomer** [comment]
Hi @gcaria, we have now got the tests all passing on `master`, so please rebase at your convenience 🙂

**Comment by gcaria** [comment]
Thanks for the feedback @rcomer !

It seems that the test failures are then caused by this commit, although it's hard to believe such a simple edit can break anything. Maybe this has to do with some expected reference data that doesn't match the actual one anymore?

I admit I have some difficulties running the test suite on my own, since I get a lot of `AssertionError: CML do not match` (I velieve I have followed the instructions on the "contributing" page)

**Comment by rcomer** [comment]
Thanks for the update @gcaria.  Yes, it looks like this is causing very small changes all over the place, and in some cases it does look for the worse.  E.g. [here](https://cirrus-ci.com/task/5391637611282432?logs=tests#L5999) the latitude points change from round multiples of 0.5 to ?.?999.

Some of the test input files are in pp-format, and the pp file headers only specify latitude/longitude by their "zeroth" value, step and number of rows/columns.  So that probably explains why so many unrelated tests are affected.

I'm not sure what the right thing to do here is.  It seems like a computer science question to me, and I am very much not a computer scientist!  Perhaps @alastair-gemmell might have some ideas, since he opened the original issue.

**Comment by ESadek-MO** [comment]
We have discussed this @SciTools/peloton and have decided to close this; please feel free to reopen! Thanks for your work on this!

**Pull request closed without merging**
