### PR TITLE
Another readthedocs.io update

### PR DESCRIPTION
**Pull request by rhattersley**
Fixes https://github.com/SciTools/iris/pull/1990#issuecomment-216833153

### CODE REVIEW

**Comment by rhattersley** [comment]
Ping @dkillick

**Comment by dkillick** [comment]
BOSH! #2000 :grinning: Sometimes [a bit of forgetfulness](https://github.com/SciTools/iris/pull/1990#issuecomment-216833153) has its reward.

**Comment by rhattersley** [comment]
> BOSH! #2000

I almost didn't create this PR for that very reason! I'd rather #2000 had gone to something more constructive! :wink:

**Comment by dkillick** [comment]
@rhattersley good stuff! I now can't find any instances of `readthedocs.org` in Iris code, and running a clean build of the docs clears out all the instances of `readthedocs.org` (there are 8 in total) within the built docs.

**Comment by dkillick** [comment]
Woop! Travis says :+1: and so do I.

**Comment by rhattersley** [comment]
Thanks @dkillick :smile:

**Pull request merged**
