### PR TITLE
Made initial use of the travis cache.

### PR DESCRIPTION
**Pull request by pelson**
Work in progress to give Iris cached travis testing.

### CODE REVIEW

**Comment by pelson** [comment]
I'll close this until it is good to go.

**Comment by pelson** [comment]
There is at least 200MB of downloaded distributions which can be cached.

**Comment by pelson** [comment]
Cache of packages is taking around 25s to prepare.

**Comment by pelson** [comment]
Install is down from ~40s to 4s.

**Comment by pelson** [comment]
It seems there is huge variation on conda's linking speed on travis. I just had an installation take 60s *without* having to download anything. Additionally, not able to re-open the PR for some reason.

**Comment by ajdawson** [comment]
You can't reopen a closed PR if you force pushed to the branch while the PR was closed.

**Comment by rhattersley** [comment]
> I just had an installation take 60s without having to download anything.

Another unrelated Iris PR just suffered from timeouts. Possibly Travis-CI is experiencing some issues.

**Pull request closed without merging**
