### PR TITLE
Remove newline to satisfy setuptools

### PR DESCRIPTION
**Pull request by wjbenfold**
### Description

In 59.0.0, on 12/11/21, setuptools introduced a [breaking change](https://setuptools.pypa.io/en/latest/history.html?highlight=description%2059%20breaking#breaking-changes) that no longer allows multi-line descriptions. This has caused `nox` to fail when running the tests with a `ValueError`.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Review by jamesp — APPROVED** [review]
Approved, we might want to change this back later for stylistic reasons when the setuptools bug has been fixed.  @wjbenfold can you add a todo to check back on it in a few weeks?

**Comment by wjbenfold** [comment]
> Approved, we might want to change this back later for stylistic reasons when the setuptools bug has been fixed. @wjbenfold can you add a todo to check back on it in a few weeks?

Will do

**Comment by wjbenfold** [comment]
> Approved, we might want to change this back later for stylistic reasons when the setuptools bug has been fixed. @wjbenfold can you add a todo to check back on it in a few weeks?

Doesn't look like setuptools have any [intention to revert or change this](https://github.com/pypa/setuptools/pull/2870) - we could propose a change to their code but this is minor enough that it doesn't seem worth it

**Comment by trexfeathers** [comment]
>we could propose a change to their code but this is minor enough that it doesn't seem worth it

Agreed, particularly since the conversation elsewhere has generally been highlighting that the chance to act was during the long period while `DeprecationWarning` was being raised.

**Pull request merged**
