### PR TITLE
[TST] Unpin dask

### LINKED ISSUE #3147: Remove dask pinning
Remove the dask pin introduced by #3127 
~Assuming they have a new release by then (should be dask 0.18.3 or later)~
**Good to go :** dask v 0.19 is now out, and fixes it

To check : the key failing test was 
```python lib/iris/tests/unit/cube/test_Cube.py -v Test_data_dtype_fillvalue.test_lazydata___getitem__dtype```

**UPDATE:** dask 0.19 fixes original, but seems to cause new problems with Iris tests :disappointed: 
See : https://github.com/SciTools/iris/pull/3159 and [its checks](https://travis-ci.org/SciTools/iris/builds/424243234?utm_source=github_status&utm_medium=notification)

### PR DESCRIPTION
**Pull request by dkillick**
Explore how much breaks if we unpin dask to use the latest master.

cc @corinnebosley @pp-mo 

Closes #3147

### CODE REVIEW

**Comment by dkillick** [comment]
Unpinning dask caused three test failures in both Python 2.7 and 3.6:

```
======================================================================
FAIL: test_dim0_lazy (iris.tests.unit.cube.test_Cube.Test_collapsed__lazy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0a0-py3.6.egg/iris/tests/unit/cube/test_Cube.py", line 288, in test_dim0_lazy
    self.assertTrue(cube_collapsed.has_lazy_data())
AssertionError: False is not true

======================================================================
FAIL: test_dim1_lazy (iris.tests.unit.cube.test_Cube.Test_collapsed__lazy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0a0-py3.6.egg/iris/tests/unit/cube/test_Cube.py", line 294, in test_dim1_lazy
    self.assertTrue(cube_collapsed.has_lazy_data())
AssertionError: False is not true

======================================================================
FAIL: test_multidims (iris.tests.unit.cube.test_Cube.Test_collapsed__lazy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.2.0a0-py3.6.egg/iris/tests/unit/cube/test_Cube.py", line 301, in test_multidims
    self.assertTrue(cube_collapsed.has_lazy_data())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 3869 tests in 220.910s
FAILED (SKIP=115, failures=3)
```

See https://travis-ci.org/SciTools/iris/jobs/436602113#L5603-L5628.

**Comment by dkillick** [comment]
Looks like the test failures reported here are at most only incidentally related to dask and more to do with an oversight in `Cube.collapsed`. I've corrected that, so now eagerly awaiting further knock-ons from so doing.

**Comment by corinnebosley** [comment]
@dkillick Wow this is exciting!  I really want to push the button.

**Comment by corinnebosley** [comment]
Boom! That's so satisfying.

Thanks @dkillick, good job!

**Pull request merged**
