### PR TITLE
Weighted percentile aggregator

### PR DESCRIPTION
**Pull request by rcomer**
A new weighted aggregator for calculating percentiles, iris.analysis.WPERCENTILE.

A point to consider: if no data point lies on the requested percentile value, this aggregator simply takes a linear interpolation between the two nearest points.  This is consistent with setting alphap=0.5, betap=0.5 when using iris.analysis.PERCENTILE, but by default the two aggregators can give inconsistent results.  I'm not sure whether this would be a problem (the linear interpolation is good enough for my purposes).

### CODE REVIEW

**Comment by rhattersley** [comment]
Superb! :clap: It's clear, documented, tested ... can't ask for more than that!

Thank you for the contribution! :+1:

**Comment by pelson** [comment]
@rcomer - I completely agree with @rhattersley, awesome contribution! :+1: 
To simplify the release process in the future, would you mind adding a what's new entry in https://github.com/SciTools/iris/tree/master/docs/iris/src/whatsnew/contributions_1.9? It should be fairly short - it isn't documentation per-se, but a pointer to tell people about all of the new functionality.

Thanks!

**Comment by rhattersley** [comment]
> would you mind adding a what's new entry

Sorry - my mistake. I'll try to remember next time... :unamused:

**Comment by rcomer** [comment]
Thanks - I had a lot of help from @dkillick so can't take all the credit!

How do I add the what's new entry? I've just added it to my existing branch but I guess that's not coming through because it's already merged?

**Comment by dkillick** [comment]
:+1: good stuff @rcomer!

**Comment by rhattersley** [comment]
> How do I add the what's new entry? I've just added it to my existing branch but I guess that's not coming through because it's already merged?

You're right - once a PR is merged new commits don't appear on it. If you create a new PR from your branch it should have just the new commit.

**Pull request merged**
