### PR TITLE
Get licence header test working again.

### PR DESCRIPTION
**Pull request by pp-mo**
**WIP: DO NOT MERGE (yet) !**

We seem to have lost this functionality with #3036
Since some time before that point, the run in the 'main' test sequence was giving a "SKIP: Iris installation did not look like a git repo." message [(here, for instance)](https://travis-ci.org/SciTools/iris/jobs/386110444#L4496)

I think this is because you need to be in the right directory when running the test.

### CODE REVIEW

**Comment by pp-mo** [comment]
Yay, fixed at last !!! 😀 

@lbdreyer this was triggered by [your comment on #3259](https://github.com/SciTools/iris/pull/3259#discussion_r258432362)
I think it's probably simplest to do this, then rebase the others (the ones that are going to master, anyway)

Can you check it out ?

**Comment by lbdreyer** [comment]
Yep, this looks good! Thanks @pp-mo :)

**Comment by pelson** [comment]
FYI the header rules were significantly relaxed a few weeks ago in https://github.com/SciTools/scitools.org.uk/blob/master/documents/scitools_licensing.md.

Essentially the year is entirely superfluous in the header and can be removed entirely. I've avoided doing it wholesale to any of the projects as I don't want to be touching every single file for no reason. The cartopy test has been updated though to support the new guidelines: https://github.com/SciTools/cartopy/pull/1267/files#diff-6545369fccb2d4d7897214fa6787e86d 

No action needed, just wanted to share the knowledge. 👍 on the change here.

**Comment by pp-mo** [comment]
> @pelson No action needed, just wanted to share the knowledge

Thanks, perhaps all devs need to push this..
Instead of checking/updating a header year, whenever you touch a sourcefile, you can update the header to new standards, removing the year altogether.
We can all push that agenda as reviewers too, if we can only remember to. :elephant: :bowtie:

**Pull request merged**
