### PR TITLE
Save and load bools as bytes with valid_range (0, 1) in netCDF format

### PR DESCRIPTION
**Pull request by djkirkham**
Bools are not supported in netCDF, and attempting to save a cube with with boolean data raises and error. This PR causes them to be saved as bytes instead.

### CODE REVIEW

**Comment by cpelley** [comment]
I think #2099 is a relevant discussion around the changes proposed in this PR.  In that, a cube with boolean type data, if converted to a int8 dtype on save, needs a way of recording the fact the the fields represent logical fields.

**Comment by cpelley** [comment]
Thanks @djkirkham for looking at this!  I raised it quite a while ago (#1920) but it gained no traction at that time.  We override the iris NetCDF fileformats module with our own for this very purpose to perform type coercion on save.  It would be great to do away with our module.

Regarding `valid_min` and `valid_max`.  On save, this is great as a means to 'indicate' datatypes which are otherwise not supported by the NetCDF saver (whether NetCDF classic or otherwise).  However, since as `valid_min` and `valid_max` can also indicate missing data, I'm not 100% that this can give a definitive answer to the intended type.  Sorry, it's been quite a while since I looked at these things.  I'll see if I can fish out some more information if I can.

**Comment by cpelley** [comment]
Looks like [netcdf-python](https://github.com/Unidata/netcdf4-python) interprets valid_min/max now for determining mask:
"6/10/2017: Version 1.2.9 released. Fixes for auto-scaling and masking when _Unsigned and/or valid_min, valid_max attributes present."

**Comment by pelson** [comment]
@djkirkham - needs a what's new and a test, and its good to go.

I do agree with @cpelley, in that this change will result in the round trip of the dtype not being preserved, but I also know that you don't have that context in the function you have modified. Are you in a position to look into the options on that front?

If we were to break the problem into two stories:

 * I want to save boolean Iris data to netcdf
 * I want to save boolean data to netcdf and preserve its boolean dtype on load

Then clearly you have done the first, and I'm reasonably happy to start with that. The second I think we should be looking at though, medium-term.

**Comment by djkirkham** [comment]
I discussed this with @cpelley and we thought a case could be made that it's sensible to save booleans as byte data with a `valid_min` of 0 and a `valid_max` of 1, and interpret this as boolean on load.

**Comment by cpelley** [comment]
I think the recent change in the netcdf4-python library is relevant in the context of this change:
https://github.com/Unidata/netcdf4-python#news

"6/10/2017: Version 1.2.9 released. Fixes for auto-scaling and masking when _Unsigned and/or valid_min, valid_max attributes present. ..."

This seems to confirm my concerns highlighted in my above comment, that is: "However, since as valid_min and valid_max can also indicate missing data, I'm not 100% that this can give a definitive answer to the intended type."

Cheers

**Comment by djkirkham** [comment]
I'm not sure I understand the problem. It seems to me we can take the practical decision to interpret byte data with valid_range [0,1] to be boolean on load (perhaps we could also take scale_factor into account). It seems unlikely to me that anyone would ever want a byte/int8 dataset with only zeros and ones.

**Comment by cpelley** [comment]
Hi @djkirkham, sorry my comment wasn't very helpful.  If there is no opposition to this I should confirm that I am personally happy.  As you say, its the most common usecase of a byte array with valid range [0, 1] to be represented as a logical field _I think_ rather than as a masked field.

However, In my experience, people are reluctant to get into a discussion around a specifications especially when there is ambiguity present.  @pelson may have been hinting toward this issue by encouraging this to be split into two with the first change being straight forward (sorry Phil if I have taken the wrong message).  I'm more than happy to review this for you though I feel we need another @SciTools/iris-devs to confirm that they are on board with our top-level approach?

@marqh may be best placed to help in this regards with his familiarity and involvement of the NetCDF specifications?

Thanks @djkirkham

**Comment by pelson** [comment]
@djkirkham - I'm in favour of the 0-1 range interpretation at load-time, if you want to go ahead and implement it. Would need a what's new, and some tests.

**Comment by corinnebosley** [comment]
@djkirkham Just a check again; if you don't reply to this by the time I look at it again I'm taking it over.  Thanks for your work on this.

**Pull request closed without merging**
