### PR TITLE
Correct STASH regular expression

### LINKED ISSUE #2624: STASH regular expression
I was just wondering whether there was a reason for using the regular expression `^\s*m(.*)s(.*)i(.*)\s*$` to determine whether a string contains a STASH code (see 
https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L308), rather than something more explicit like `^\s*m(\d{2})s(\d{2})i(\d{3})\s*$` (or even `^\s*m(\d*)s(\d*)i(\d*)\s*$`)? I have a case where the string I was checking contained the netCDF variable name `mlotstmin`, which matches with the current regular expression, even though it is not a STASH code!

### PR DESCRIPTION
**Pull request by ehogan**
Attempts to fix #2624.

However, some of the `test_pp_cf.py` tests fail because the test files (located [here](https://github.com/SciTools/iris-test-data/tree/master/test_data/PP/cf_processing)) now have invalid STASH codes; `002000000000.44.101.131200.1920.09.01.00.00.b.pp` and `008000000000.44.101.000128.1890.09.01.00.00.b.pp` have a STASH code of `44101` (`ValueError: Expected STASH code MSI string "mXXsXXiXXX", got u'm??s44i101'`) and `st0fc942.b.pp` and `st0fc699.b.pp` have a STASH code of `0` (`ValueError: Expected STASH code MSI string "mXXsXXiXXX", got u'm02s00i???'`)

Would it be possible for someone to help? What should I do now?

### CODE REVIEW

**Comment by marqh** [comment]
hello @ehogan 

the code lines
```
if msi_match is None:
    raise ValueError('Expected STASH code MSI string "mXXsXXiXXX", '
```

are being hit in these test cases

perhaps you could add a test, using one of these partial strings, e.g.
```
u'm??s44i101'
```

and compare behaviour of the current regular expression to your proposed change; perhaps there's a small behaviour tweak that you could implement

**Comment by ehogan** [comment]
Just one set of tests failed due to time out errors. Do the tests need to be restarted? I'm pretty sure everything is ok though. Thank you for the help @marqh! :)

**Comment by dkillick** [comment]
Ah - the tests have _actually_ failed now rather than erroring and it looks like there are [a couple of failing tests](https://travis-ci.org/SciTools/iris/jobs/255184041#L6033-L6100) that need to be addressed before this can be merged...

**Comment by ehogan** [comment]
Thanks for the review @dkillick, all the tests are passing now :)

**Comment by dkillick** [comment]
@ehogan good stuff :+1: I just need to check your most recent changes and we need to get you added to the contributors list, but neither of those things should be too arduous!

**Comment by djkirkham** [comment]
Are we sure we want to lose handling cases such as `m1s1i1`, where the numeric parts are longer or shorter than they should be?

**Comment by ehogan** [comment]
Thanks for the PR @djkirkham :) However, a lot of tests are failing :( (I'm not sure they're related to the changes in this branch though?)

**Comment by djkirkham** [comment]
@ehogan It's a problem with the testing environment (see https://github.com/SciTools/iris/pull/2769). As soon as there's a resolution for that I'll kick off the tests again and hopefully this can be merged.

**Pull request merged**
