### PR TITLE
Correction to curl function

### PR DESCRIPTION
**Pull request by djkirkham**
The sign of the r component of the curl function is wrong when using spherical coordinates. This change reverses the sign.

This needs to be checked by someone who understands the maths better than I do.

### CODE REVIEW

**Comment by djkirkham** [comment]
@marqh Please review this

**Comment by marqh** [comment]
please add a what's new entry to
https://github.com/SciTools/iris/tree/master/docs/iris/src/whatsnew/contributions_1.10

describing this change (it's a bug fix, in my book)

**Comment by marqh** [comment]
I agree with the analysis and the change

the comment in the test
https://github.com/SciTools/iris/blob/master/lib/iris/tests/test_analysis_calculus.py#L521
explicitly differs from the calculated result which is checked
https://github.com/SciTools/iris/blob/master/lib/iris/tests/test_analysis_calculus.py#L556
by a factor -1

this part of the codebase is unchanged for as long as it has been in github; i think it is just a mistake

please can we also add a little documentation, in the form of code comments, at line
https://github.com/SciTools/iris/blob/master/lib/iris/tests/test_analysis_calculus.py#L556

highlighting the expected result

I have plotted vector field to get a visual clue on the curl sign and I think it should be negative (into the page, right hand rule) near the centre of the plot, as this PR defines

curl

**Comment by marqh** [comment]
for my reference
```
        import matplotlib.pyplot as plt
        plt.quiver(u.data[::3, ::3], v.data[::3, ::3],
               pivot='mid', color='r', units='inches')
        #plt.show()
        plt.savefig('/tmp/curl.png')
```

**Comment by marqh** [comment]
this looks good to go, please squish your commits @djkirkham and I'll look to merge

**Comment by pelson** [comment]
I presume you've had the advice of a local expert @marqh? I'd hate to fix the sign only to find that a Meteorological convention switches means that it was already in the right direction...

**Comment by marqh** [comment]
> I presume you've had the advice of a local expert @marqh? I'd hate to fix the sign only to find that a Meteorological convention switches means that it was already in the right direction...

@pelson we have had advice, this originated in a bug report from a library user

the doc string in the test also has a '-' sign, but the test result doesn't implement this.

Based on research to date, I think the change is correct; i'll go back and check my working before i hit merge

**Comment by marqh** [comment]
examining the figure posted and applying the right hand rule, we can see that the transition from +ve curl to -ve curl should occur along the lat=0 line moving positively in lon between lon=-2 and lon=-1

```
>>> import math
>>> -2 * math.cos(-2) * math.cos(0)
0.8322936730942848
>>> -2 * math.cos(-1) * math.cos(0)
-1.0806046117362795

``` 

illustrating that the updated formula is correct and that this is a long standing bug in our current code

**Pull request merged**
