### PR TITLE
Remove biggus from test comment.

### PR DESCRIPTION
**Pull request by bjlittle**
Simply remove a reference to biggus in a test case comment.

### CODE REVIEW

**Comment by bjlittle** [comment]
Ping @dkillick and @corinnebosley

**Comment by dkillick** [comment]
@bjlittle I like it! Just waiting on Travis now... (which I'm sure will be fine!)

**Comment by bjlittle** [comment]
something on the travis side is chocking ... *sigh*

**Comment by bjlittle** [comment]
@dkillick Travis is happy. I'm pretty happy. Are you happy?

**Pull request merged**
