### PR TITLE
Py3k unicode slicers

### PR DESCRIPTION
**Pull request by pp-mo**
A step towards an alternative version of #1782 which conserves existing Python 2 behaviour : see [comment there](https://github.com/SciTools/iris/pull/1782#issuecomment-154050680)

An adjusted version of @QuLogic ["b759876 py3k: Correctly handle string input to slicers. "](https://github.com/QuLogic/iris/commit/b7598762531c727bb6939a2017c15fa6cac86183)
The implementation is somewhat rewritten, as I previously suggested : [comment on #1782](https://github.com/SciTools/iris/pull/1782#discussion_r43653959)
This should make *no* functional difference.

TO TEST :
```python3 -m unittest iris.tests.unit.cube.test_Cube``` fails before this, succeeds after

NOTE :
As the second commit efffectively reverts some changes from the first one,  it probably makes good sense to squish before merging.

### CODE REVIEW

**Comment by QuLogic** [comment]
Makes sense to me.

**Comment by pp-mo** [comment]
Is this ok, shall I skwish it ?

**Comment by QuLogic** [comment]
Sure (you can even claim authorship on this one; it's mostly your work.)

**Comment by pp-mo** [comment]
Done that.
Thanks @QuLogic

**Pull request merged**
