### PR TITLE
Creq tidy

### PR DESCRIPTION
**Pull request by marqh**
tiyd up INSTALL and conda-requirements

reduce the scope of minimal-conda-requirements, which isn't especially minimal at the moment

i wonder whether our graphics test skip patterns are such that we could remove matplotlib as a dependency, but I think that cartopy might bring it in anyway via conda. I have not investigated this further

### CODE REVIEW

**Comment by marqh** [comment]
treading on #2197 's toes, sorry @corinnebosley

**Comment by marqh** [comment]
useful tidy up perhaps, but I'm a bit disappointed that i have barely touched teh minimal test run times

**Comment by corinnebosley** [comment]
@marqh At least you've dumped gdal.  That can't be a bad thing.

**Comment by bjlittle** [comment]
I agree. Minimal isn't quite minimal.

Thanks @marqh :+1:

**Pull request merged**
