### PR TITLE
Expose cell method parsing.

### PR DESCRIPTION
**Pull request by rhattersley**

### CODE REVIEW

**Comment by pelson** [comment]
👍 in principle.

**Comment by rhattersley** [comment]
> :+1: in principle.

But not in practice? :wink: I've fixed the problem with the copyright period.

@bjlittle - thoughts welcome on the choice of location, etc.

**Comment by pelson** [comment]
>  I've fixed the problem with the copyright period.

Then also in practice :smile: 

@bjlittle - over to you to merge when happy.

**Comment by rhattersley** [comment]
> rhattersley modified the milestone: v1.10, v1.9 just now

It's a new API, so it goes in the next minor release.

**Comment by rhattersley** [comment]
Go on then @bjlittle ... I dare you! Merge! Merge! Merge! :stuck_out_tongue:

**Comment by pp-mo** [comment]
I suppose it's all ok, but I wonder if it wants a bit more quality now it's going public ?

The interface seems a bit odd because the 'cf_var_name' appears redundant -- which it actually is, except for being used to construct a warning message.  Maybe you can just document that.

I'm also wishing there was some type of statement about the operational scope too, as it's possibly a bit obscure .  Do we support "everything" ??
Maybe a simple usage example is helpful, like
```
>>> parse_cell_methods('varname', 'x: sum(interval:1 hr)')
(CellMethod(method='sum', coord_names=('x',), intervals=('1 hr',), comments=()),)
>>> 
```

**Comment by rhattersley** [comment]
I've raised a related question on the xarray PR.

**Comment by dkillick** [comment]
This functionality has been added through the now-merged #2039, so I'm going to close this PR.

**Pull request closed without merging**
