### PR TITLE
TEST: Regrid test timeout on travis failure

### PR DESCRIPTION
**Pull request by cpelley**
This concerns `iris.tests.experimental.regrid.test_regrid_area_weighted_rectilinear_src_and_grid.TestAreaWeightedRegrid`.
1. Optimise tests (reduction).
2. Possible removal of some tests.
3. Possible increase of nosetests timeout.

**NOT FOR MERGING**

### CODE REVIEW

**Comment by cpelley** [comment]
Regardless of the complete solution, the work on test reduction has already made minor progress (see [commit](https://github.com/SciTools/iris/pull/1986/commits/11e777b0ebefbe54ef42ee5ab78d7793367b3a69)).  Either way, I think this is worth using rather than throwing away.

**Comment by rhattersley** [comment]
Thanks for making progress on this @cpelley :+1: :smile:

**Comment by cpelley** [comment]
Just in case it is not know, I am unlikely to commit more time to this.

**Comment by cpelley** [comment]
The intention of this PR was to make a partial step towards tidying the regridding tests in order to remedy the issue of timeout tests related to regridding.
This PR is now in conflict.  Closing for now as I can't justify picking this back up.

**Pull request closed without merging**
