### PR TITLE
Linkcheck update

### LINKED ISSUE #4103: Linkcheck failures
## 📰 Custom Issue

Two link checks seem to be consistently failing across PRs.

* http://matthew-brett.github.com/pydagogue/gh_delete_master.html
  Looks like there is a straight substitution for this: https://matthew-brett.github.io/pydagogue/gh_delete_master.html
* https://readthedocs.org/dashboard/scitools-iris/version/v3.0.0rc0/
   No idea what to do about this one 🙁

### PR DESCRIPTION
**Pull request by tkknight**
### Description

Fix linkcheck.  

This should close #4103 

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by tkknight** [comment]
The linkcheck is passing but the standard tests are timing out on cirrus-ci. Not sure why.

**Comment by pp-mo** [comment]
I re-spun the failing tests this morning, but something very odd is happening.
It currently suggests that py3.8 full tests have been running for over 3 hours.
And I can't see why these won't run, when checks on #4099 re-ran several times this morning, and ran OK.

I don't think this can be due to the actual changes here.  Maybe it is something odd in Cirrus, linked to this PR or this commit specifically
**@tkknight Do you think it could be worth adding a new commit here with a minor change ?**

**Comment by tkknight** [comment]
test commit https://github.com/SciTools/iris/pull/4104/commits/e9026a58d01f9f370f082ad00df7c266e82f20a0 to kick cirrus.....

**Comment by tkknight** [comment]
the linkchceck failed but I expect that to pass if re-reun.  However the python 3.6 tests (minimal and full) seem to be stuck on the command:

`conda env update --prefix=/tmp/cirrus-ci-build/.nox/tests --file=requirements/ci/py36.yml --prune`

**Comment by trexfeathers** [comment]
Is there a chance that it's trying to use a cache that is in some way faulty? Although if that's true I don't know what we might do, short of a new PR...

**Comment by tkknight** [comment]
> Is there a chance that it's trying to use a cache that is in some way faulty? Although if that's true I don't know what we might do, short of a new PR...

Possibly.   Speaking with @jamesp there may be an option to avoid cirrus-ci resolving environments (it takes more time than creating it imho).  We could use conda-lock to fix our environment definition for a period of time (like a cache).  @jamesp  is exploring this here: https://github.com/SciTools/iris/issues/4105 (ticket still being composed!).

Pinging @bjlittle for awareness, he has the most recent experience with cirrus-ci

I will trigger another cirrus build tomorrow for this PR to see if it has resolved itself for the interrim.

**Comment by jamesp** [comment]
I've updated #4105 with a couple of thoughts on using lock files instead of resolving environments each run of CI.

**Review by trexfeathers — APPROVED** [review]
Does what it says on the tin 👍

**Pull request merged**
