### PR TITLE
[WIP] Silence userwarnings

### LINKED ISSUE #3078: silence intended UserWarnings in tests
The testing logs contain hundreds of `UserWarnings`. The vast majority seems to be:

```python
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.1.0.dev0-py3.6.egg/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:2029: 
UserWarning: Gracefully filling 'lat' dimension coordinate masked points
```
and
```python
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.1.0.dev0-py3.6.egg/iris/coords.py:1210: 
UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'latitude'.
```

Expected warnings that are intended should be silenced. As an example, Improver has a [decorator](https://github.com/metoppv/improver/blob/master/lib/improver/utilities/warnings_handler.py) that does this.

If there are no objections I will have a go at creating a pull request.

### PR DESCRIPTION
**Pull request by tv3141**
Closes #3078

- create `IrisUserWarning` and uses it where a `UserWarning` was raised before. This allows the silencing of all `IrisUserWarnings` from Iris without silencing `UserWarnings` from other libraries.
- silence all `IrisUserWarnings` (this can be made more specific)

### CODE REVIEW

**Comment by dkillick** [comment]
Hi @tv3141 - thanks for this work to fix an outstanding Iris issue! Looks like some changes to master mean that your PR now has some merge conflicts; would you mind rebasing to fix these conflicts? Thanks!

**Comment by corinnebosley** [comment]
@tv3141 This PR still looks good to me, but we need you to rebase please.  This isn't as straightforward as the last two that I've rebased for you; I'll need you to make sure the conflicts are resolved correctly.

**Comment by tv3141** [comment]
@corinnebosley @dkillick I will rebase this as soon as I can.

**Comment by tv3141** [comment]
This still needs a bit of work. 

Also some tests fail because of `ncdump`. I do not know how my changes cause that yet.

```
ERROR: test_conflicting_global_attributes (iris.tests.test_netcdf.TestNetCDFSave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.3.0.dev0-py3.6.egg/iris/tests/test_netcdf.py", line 779, in test_conflicting_global_attributes
    ('netcdf', 'netcdf_save_confl_global_attr.cdl'))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.3.0.dev0-py3.6.egg/iris/tests/__init__.py", line 355, in assertCDL
    stderr=cdl_file, stdout=cdl_file)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ncdump', '-h', '/tmp/tmpaa88ge1z.nc']' returned non-zero exit status 1.
```

**Comment by corinnebosley** [comment]
On second thoughts I'll leave it a bit and have another look if and when that's the only test which fails.

**Comment by tv3141** [comment]
> Yeah that's a bit worrying isn't it? I'll look into the testing environment; could be that something's been updated which has broken subprocess.

The problem was that the file did not exists. The root cause was missing indentation. I added #3219 to make this more verbose.

**Comment by bjlittle** [comment]
@tv3141 Firstly,  thanks for this awesome PR :+1: 

Sadly it's went rather stale. Also, we've decided to adopt `logging` as an alternative strategy, and reserve `warnings` for limited use throughout the code base. As such I'm going to close this PR, but reference it's efforts in an associated issue. 

Thanks again

**Pull request closed without merging**
