### PR TITLE
BUG: Intersection points are no longer contiguous

### PR DESCRIPTION
**Pull request by cpelley**
BUG: Intersection for points at period + base

Currently while intersecting points/bounds which coincide at (period + base)
these are wrapped around which results in a once contiguous coordinate
being not contiguous any more.

I have yet to add unittests as it would be good to get confirmation as to whether I am correct in modifying `cube.intersection` and not `iris.analysis.cartography.wrap_lons`.
My feeling is that `wrap_lons` is neither correct or incorrect.  Also, modifying wrap_lons would have a greater impact reliant on its current behaviour.
However, when utilising `wrap_lons` within `cube.intersection`, this clearly identifies itself as a bug within this specific context (i.e. its an issue with how `cube.intersection` uses these points).

**DO NOT MERGE: once I get confirmation of the above, I'll be happy to write some unittests.**

```Python
>>> import numpy as np
>>> from iris.analysis.cartography import wrap_lons
>>> lons = np.array([-180., -90., 0., 90., 180.])
>>> res = wrap_lons(lons, -180., 360.)
>>> res == lons
array([ True,  True,  True,  True, False], dtype=bool)
>>> print res
[-180.  -90.    0.   90. -180.]
>>> assert np.all(lons == res)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

Here is the gist when attempting an intersection:
https://gist.github.com/cpelley/05cde98a251d467e9cd2

When running on 1.7.x:
```Python
[...]$  python2.7 intersection_bug.py 

Traceback (most recent call last):
  File "intersection_bug.py", line 50, in <module>
    overlap = source.intersection(x_ext, y_ext)
  File "/.../git/iris/lib/iris/cube.py", line 2051, in intersection
    result = result._intersect(*arg)
  File "/.../git/iris/lib/iris/cube.py", line 2090, in _intersect
    chunks = [make_chunk(key) for key in subsets]
  File "/.../git/iris/lib/iris/cube.py", line 2085, in make_chunk
    chunk_coord.bounds = bounds[(key,)]
  File "/.../git/iris/lib/iris/coords.py", line 1447, in bounds
    raise ValueError('The bounds array must be strictly '
ValueError: The bounds array must be strictly monotonic.
```

When running on master: - we can see that the coordinates and the corresponding data has been unexpectedly wrapped, but now at least the monotonic bounds except is not raised.
```Python
Traceback (most recent call last):
  File "intersection_bug.py", line 52, in <module>
    assert source == overlap
AssertionError

print source.coord('longitude')
DimCoord(array([-135.,  -45.,   45.,  135.]), bounds=array([[-180.,  -90.],
       [ -90.,    0.],
       [   0.,   90.],
       [  90.,  180.]]), standard_name='longitude', units=Unit('degree_east'), coord_system=GeogCS(6371229.0), circular=True)
print overlap.coord('longitude')
DimCoord(array([-225., -135.,  -45.,   45.]), bounds=array([[-270., -180.],
       [-180.,  -90.],
       [ -90.,    0.],
       [   0.,   90.]]), standard_name='longitude', units=Unit('degree_east'), coord_system=GeogCS(6371229.0), circular=True)
```

I believe the common cause to both these problems lies in the correct handling of points that lie at the (base + period).  The issue is that this base moves as a result of the extended minimum.

**I should point out that I have mistakenly pointed this to master, I will change to 1.7.x after confirmation.**

### CODE REVIEW

**Comment by pelson** [comment]
Do you have a SSCCE to go with it?

**Comment by cpelley** [comment]
> Do you have a SSCCE to go with it?

Appologies, yes I do.  For `wrap_lons`:

```Python
>>> import numpy as np
>>> from iris.analysis.cartography import wrap_lons
>>> lons = np.array([-180., -90., 0., 90., 180.])
>>> res = wrap_lons(lons, -180., 360.)
>>> res == lons
array([ True,  True,  True,  True, False], dtype=bool)
>>> print res
[-180.  -90.    0.   90. -180.]
```

**Comment by cpelley** [comment]
Just realised that I pointed this to master when I meant to point it to 1.7.x  No matter I'll change that once I get confirmation of the change.  I'll post an SSCCE for intersection too.

**Comment by rhattersley** [comment]
From your example, `wrap_lons` looks to be doing exactly what I'd expect.

**Comment by cpelley** [comment]
> From your example, wrap_lons looks to be doing exactly what I'd expect.

Thanks @rhattersley, this confirms my feeling also.  I have updated the PR description with the intersection example.  I'll write the tests for intersection then push back up (this time pointing to 1.7.x).

**Comment by cpelley** [comment]
I have added the unit tests, however I have been struggling all morning to get my fix working in combination with the extended minimum stuff but to no avail (https://github.com/cpelley/iris/blob/ce73d5e735b5bf03a4287855e7a619bf1e1e4d7f/lib/iris/cube.py#L2191).  The existing unit test framework for this area contains coordinates with hundreds of points so I'm struggling to see the wood from the trees.

Does anyone remember enough about this area of the code to point me in the right direction?
Thanks in any case.

**Comment by cpelley** [comment]
The reason behind the difference in behaviour between v1.7.x and master is:
https://github.com/SciTools/iris/blob/03b932cc4cee06a640d85467a0b44abd40b745de/lib/iris/cube.py#L2248-L2249

However the underlying issue is still there.

**Comment by cpelley** [comment]
Possibly getting close, looks like it might now be to do with the subsets that `_intersect_modulus` returns.  I'll follow this up in the morning.

**Comment by pelson** [comment]
@cpelley - how do you sit with this PR? Is this still something you are looking into?

**Comment by cpelley** [comment]
Hi @pelson thanks for pinging this.

Coming up with a generalised solution for 'Intersection' ended up being difficult as there were numerous corner cases, the details of which I can no longer remember.  I have since put this on hold as its not stopping me doing anything right now.

**Comment by pelson** [comment]
Closing for now then. Thanks @cpelley

**Comment by cpelley** [comment]
Can I have this opened again please.  For my current application of intersection, this issue means that I am unable to use it (I need the extracted region unaltered to be defined on the unaltered grid).  Intersection redefines the coordinates because the max bound is at base + period.

Referring to my gist:

The coordinates have been altered by intersection:
{{{
print overlap.coord('longitude').bounds.min(), overlap.coord('longitude').bounds.max()
print source.coord('longitude').bounds.min(), source.coord('longitude').bounds.max()
}}}

The data has been wrapped around because of the choice of changes to the coordinates:
{{{
print source.data
print
print overlap.data
}}}

**Pull request closed without merging**
