### PR TITLE
mesh-data-model dev version + purge plotting

### PR DESCRIPTION
**Pull request by bjlittle**
### Description
This PR backs out `iris.experimental.ugrid.plot` and bumps the `mesh-data-model` feature branch version back to `3.1.dev0` after the `3.1a0` engineering tag.

This unblocks the `mesh-data-model` feature branch and allows it to be merged to `master`.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Review by pp-mo — APPROVED** [review]
This all looks pretty clean + sensible.

The only thing I can find amiss is that there is still [a mention of experimental.irsi.ugrid.plot in the file `docs/src/sphinxext/generate_package_rst.py`](https://github.com/SciTools/iris/blob/f9f17fbdbf0813a08b7c7b645fc5ba699f3714e6/docs/src/sphinxext/generate_package_rst.py#L17), which I think should have got "pruned out".  

I don't that can do any actual harm, though ?
Fix if you fancy, or merge at will !

**Comment by bjlittle** [comment]
@pp-mo Yup, thanks 👍

Forgot to remove that piece of connective tissue. I'll push that change, then we'll be good to go. Nice one

**Comment by bjlittle** [comment]
Merging with CI test failures is fine atm

**Comment by pp-mo** [comment]
The outstanding test failures should resolve when we fix other problems

**Comment by bjlittle** [comment]
Awesome, thanks @pp-mo :beers:

**Pull request merged**
