### PR TITLE
Mergeback v3.3.0

### PR DESCRIPTION
**Pull request by stephenworsley**
### Description

Merge the 3.3.x branch back into main after the release of 3.3.0.

### Note: to be merged without squashing!

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by pp-mo** [comment]
The tox documentation on RTD is completely unavailable just now.
I guess we don't want to remove, so we'll wait for it to be fixed ?

**Comment by pp-mo** [comment]
> The tox documentation on RTD is completely unavailable just now. I guess we don't want to remove, so we'll wait for it to be fixed ?

I think it's now fixed
@stephenworsley 👈 bump !

**Review by pp-mo — APPROVED** [review]
:+1:

**Comment by pp-mo** [comment]
Just checked what happened on v3.3.x + confirmed this is good.

Ping @bjlittle : can you please enable merge-commits on main, temporarily ?

**Comment by bjlittle** [comment]
@pp-mo Go for it :+1:

**Pull request merged**
