### PR TITLE
update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bjlittle**
### Description
Minor update to our `CONTRIBUTING.md`

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by bjlittle** [comment]
Okay, so I can only suggest that there is a `nose` testing race condition occurring in `py37` as #4166 is cut from the same `master` commit as this PR.

This is addressed in #4163

**Comment by bjlittle** [comment]
I'll rebase this PR once #4163 lands...

**Comment by bjlittle** [comment]
We should also complement this with a [SUPPORT.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project) ... but I'll do that as a separate PR :+1:

**Comment by bjlittle** [comment]
@trexfeathers I waxed it somewhat more lyrical :laughing:

**Comment by trexfeathers** [comment]
image

**Comment by trexfeathers** [comment]
I still have no idea how to fix the above, but I just thought I'd put it there.

**Review by trexfeathers — APPROVED** [review]

**Comment by bjlittle** [comment]
I don't know if anything needs fixed... but maybe we could streamline somehow.

That said, if all roads lead to new contributions and GH discussions... then I'm not going to complain a jot :wink:

**Pull request merged**
