### PR TITLE
Fixes for tests where we expect a masked array but get a NaN array

### PR DESCRIPTION
**Pull request by djkirkham**
All of these fixes simply replace the CML with the new result. They are all cases where the data _should_ contain NaNs, but Iris was interpreting them as a mask. Diffing with the v1.13.0 cml files shows them to be identical bar core-dtype.

### CODE REVIEW

**Comment by pelson** [comment]
To be clear, these contain NaNs because we ask them to when we do some form of interpolation.

**Comment by pelson** [comment]
👍  once the tests are passing.

**Comment by djkirkham** [comment]
Quick, merge this before Travis changes its mind!

**Comment by pp-mo** [comment]
@djkirkham just to be clear, does this cover all of (+ so close) #2714 ?

**Comment by pp-mo** [comment]
I checked + found that `test_cube_mask (iris.tests.integration.test_ff.TestLBC)` is still not yet fixed,
that is now the one thing is outstanding from #2714.

**Pull request merged**
