### PR TITLE
unpin matplotlib

### PR DESCRIPTION
**Pull request by marqh**

### CODE REVIEW

**Comment by QuLogic** [comment]
No way it's that easy :stuck_out_tongue:

**Comment by marqh** [comment]
indeed :/

**Comment by djkirkham** [comment]
Going to start looking at the `TypeError: data type "i16" not understood` errors.

**Comment by djkirkham** [comment]
PR: https://github.com/SciTools/iris/pull/2127

**Comment by djkirkham** [comment]
Now looking at `TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'`

**Comment by djkirkham** [comment]
Now working on datetime rounding errors

**Comment by djkirkham** [comment]
PR: https://github.com/SciTools/iris/pull/2128

**Comment by djkirkham** [comment]
Now working on datetime rounding errors.

**Comment by marqh** [comment]
I am working on testCDL failures linked to ncdump output

**Comment by marqh** [comment]
> I am working on testCDL failures linked to ncdump output

#2133

**Comment by djkirkham** [comment]
PR for datetime rounding errors: https://github.com/SciTools/iris/pull/2134

**Comment by djkirkham** [comment]
Now looking into PANDAS errors

**Comment by djkirkham** [comment]
pandas PR: https://github.com/SciTools/iris/pull/2136

**Comment by marqh** [comment]
#2135 is a step into matplotlib check_graphic tests space
it is not a solution by a long way

**Comment by marqh** [comment]
#2139 has more check_graphic updates

**Comment by marqh** [comment]
#2141 has a whole swathe of check_graphic removals, whilst attempting to maintain test coverage

**Comment by djkirkham** [comment]
another PR related to pandas tests: https://github.com/SciTools/iris/pull/2142

**Comment by marqh** [comment]
@bjlittle tests rerunning

**Comment by dkillick** [comment]
Note that the datetime rounding errors fix (#2134) was moved to a cf_units change (SciTools/cf_units#66).

**Comment by dkillick** [comment]
I have proposed a different approach for dealing with the failing graphics tests, which is captured in #2150.

**Comment by dkillick** [comment]
@marqh the only test that's now failing was due to changes in cf_units. I just merged the fix for this in #2144, so I've restarted the tests once more and then they should pass.

**Comment by marqh** [comment]
Outstanding test failures, as of
https://github.com/SciTools/iris/commit/f53fc6f62ace71d3a2d2166c29697d17a2ab332e
* [ ] image comparison: check_graphic:
 * many (most)
* [ ] Geotiff:
 * test_masked (iris.tests.experimental.test_raster.TestGeoTiffExport) 
  * https://travis-ci.org/SciTools/iris/jobs/164579404#L4998
 * FAIL: test_ellipsoid (iris.tests.unit.experimental.raster.test_export_geotiff.TestProjection)
  * https://travis-ci.org/SciTools/iris/jobs/164579404#L5049
* [ ] netcdf4-python - `string`
 * #2133 
 * test_save (iris.tests.integration.test_netcdf.TestHybridPressure)
  * https://travis-ci.org/SciTools/iris/jobs/164579404#L5023
 * FAIL: test_netcdf_save_ndim_auxiliary (iris.tests.test_netcdf.TestNetCDFSave) 
  * https://travis-ci.org/SciTools/iris/jobs/164579404#L6483

@bjlittle

**Comment by QuLogic** [comment]
So how imminent is 1.11? I ask because I basically cannot build 1.10 _with tests_ because of all of the above compatibility issues with the latest packages. I'd vote for there to be a release as soon as these compatibility issues are corrected, without regard to any other outstanding features, whether that be 1.10.1 or 1.11.0.

**Comment by pelson** [comment]
> So how imminent is 1.11? I ask because I basically cannot build 1.10 with tests because of all of the above compatibility issues with the latest packages.

Same story here. A release needs to happen, ideally in the next 10 days, that can be said to support newer dependency versions (i.e. can be *tested* with them). Looking at the changes that are coming out of the woodwork, it is a healthier thing to call it v1.11 than v1.10.1 IMO (there are some behaviour changes needed). We are fortunate in that there is no social/political drive to release a v1.10.1 vs v1.11, so let's call a duck a duck and aim for ```v1.11.0```.

You are right to be concerned (in another comment) by the time it took to get v1.10 out. My sole aspiration for v1.11 is to be able to claim "support" for unpinned dependency versions, and anything else represents a distraction from this extremely important aim. I have updated the v1.11 milestone with some dates, as well as a clear goal - as a group, we need to learn the lesson of release little and often and it is my hope that we are turning the corner in that direction.

Ping @SciTools/iris-devs - please be aware once this PR is merged, we will be *extremely* close to releasing Iris v1.11.

**Comment by ajdawson** [comment]
>please be aware once this PR is merged, we will be extremely close to releasing Iris v1.11

Sounds like a good plan. There are/will be some commits on v1.10.x that need to be merged into master before cutting v1.11.x branch, just a heads up so we can avoid a headache.

**Comment by marqh** [comment]
> Sounds like a good plan. There are/will be some commits on v1.10.x that need to be merged into master before cutting v1.11.x branch, just a heads up so we can avoid a headache.

#2177

**Comment by marqh** [comment]
> QuLogic commented on 31 Aug

> No way it's that easy :stuck_out_tongue: 

as easy as six weeks hard labour

/me points at a travis green tick \o/

**Comment by bjlittle** [comment]
@marqh Really, really? :astonished:

**Comment by corinnebosley** [comment]
@bjlittle Don't be asking that question Bill, especially not twice.  If the big green tick says it's OK, then it must be OK.

**Comment by bjlittle** [comment]
@marqh and @corinnebosley whoop! :tada: :smile:

**Pull request merged**
