### PR TITLE
Catch up with upstream changes in netcdftime

### PR DESCRIPTION
**Pull request by ocefpaf**
Fix #165

PS: This fix  is already in `cf_units` :wink:

### CODE REVIEW

**Comment by rhattersley** [comment]
> Fix #165

I guess you mean #1654?

**Comment by rhattersley** [comment]
> PS: This fix is already in cf_units :wink:

As SciTools/cf_units#16

**Comment by rhattersley** [comment]
Does this work with old *and* new versions of netcdftime?

**Comment by ocefpaf** [comment]
> I guess you mean #1654?

Oops :flushed:

> Does this work with old and new versions of netcdftime?

Yes: http://nbviewer.ipython.org/gist/ocefpaf/bb9c3d4b114c4033de10

**Comment by rhattersley** [comment]
>> Does this work with old and new versions of netcdftime?
> 
> Yes: http://nbviewer.ipython.org/gist/ocefpaf/bb9c3d4b114c4033de10

Super. :smile: 

:+1:

**Comment by rhattersley** [comment]
Thank you @ocefpaf!

**Pull request merged**
