### PR TITLE
 Preserve dtype for wrap_lons 

### LINKED ISSUE #4119: Preserve dtype for wrap_lons
## 📰 Custom Issue

Currently, `iris.analysis.cartography.wrap_lons` promotes dtype to `np.float64`. This is causing some users to have to manually change the dtype back to its original version.
https://github.com/SciTools/iris/blob/98baee21721826a2a3c25d9169ed7e97e16e5e12/lib/iris/analysis/cartography.py#L70-L73
I believe this is done to avoid rounding errors within the calculation. If this is the case, It may be worth converting back to the original dtype after the calculation with something like the following code:

```
orig_dtype = lons.dtype
lons = lons.astype(np.float64)
return (((lons – base + period * 2) % period) + base).astype(orig_dtype)
```

### PR DESCRIPTION
**Pull request by Rohansjamadagni**
### Description
Fixes #4119  

NOTE: Adding this change resulted in a failure of the cube unit test,  so I have added the changes necessary to account the changes in the dtype

### CODE REVIEW

**Comment by Rohansjamadagni** [comment]
I have now signed the CLA

**Comment by rcomer** [comment]
Hi @Rohansjamadagni and @jeffreypaul15 , thanks for contributing!  Sorry that nobody responded to this sooner - Team Iris have been very busy.  There are just a few things to address to get our checks passing:

* Because this change also includes a commit from @jeffreypaul15, he will also need to sign the CLA.
* The `main` branch has moved on since you created your branch, so you will need to rebase to pick up those changes.  If you've not done that before, this should work:
```
git checkout bug-fix-issue-4119
git fetch upstream
git rebase upstream/main
```
* Thanks for fixing the unit test to reflect the new behaviour.  There is also a doctest that needs updating [here](https://github.com/SciTools/iris/blob/6109cfb64ddfe9bf50a8a34e21eb9f9c62a077c5/lib/iris/analysis/cartography.py#L67).  I think it should just be a case of removing the decimal points.

**Comment by rcomer** [comment]
Hi @jeffreypaul15, are you able to sign our [CLA](https://scitools.org.uk/cla/v4/form)?  We appreciate that you both might not have time to work on this PR anymore, and we can make the required branch changes ourselves if that is the case.  However, we are not allowed to accept any commit without a CLA from the author, so we can't take this any further without that.

**Comment by rcomer** [comment]
This one has now stalled for some time so I will close it.  We can re-open if there is interest but, given that there is now a conflict in `cartography.py`, it may be just as easy to start again with a new branch and new PR.

**Pull request closed without merging**
