### PR TITLE
Pp little endian

### PR DESCRIPTION
**Pull request by pp-mo**

### CODE REVIEW

**Comment by pelson** [comment]
Sorry, but I'm completely 👎  on doing this. PP is big endian 32-bit - it says so in the spec (UMDP F03, which unfortunately I can't link to here).

**Comment by marqh** [comment]
> Sorry, but I'm completely :-1: on doing this. PP is big endian 32-bit - it says so in the spec (UMDP F03, which unfortunately I can't link to here).

I am taking an action to propose an update to UMDPF03 (which is not publicly linkable) which will highlight this usage within the Unified Model Community to address this concern

**Comment by pelson** [comment]
Thanks @marqh - I agree. FWIW, I have not looked at the implementation detail here.

**Comment by marqh** [comment]
The Unified Model Documentation updates are under discussion, I will shepherd these through the governance process

In the meantime, I am happy with this change

@pp-mo please squish and I will merge

**Comment by pp-mo** [comment]
Thanks @marqh 
Sqwished...

**Comment by marqh** [comment]
thanks @pp-mo

**Pull request merged**
