### PR TITLE
Patch page 404 mailing list url replaced

### PR DESCRIPTION
**Pull request by corinnebosley**
@pelson: 
I have changed the mailing list url (that was harder to find than I expected, but I feel good about myself now).

Hope this is ok.

### CODE REVIEW

**Comment by ajdawson** [comment]
I thought this was auto-generated from [docs/iris/src/developers_guide/gitwash_build.sh](https://github.com/SciTools/iris/blob/master/docs/iris/src/developers_guide/gitwash_build.sh)...

**Comment by corinnebosley** [comment]
Is it? Should I have changed something else instead?

**Comment by ajdawson** [comment]
My understanding of gitwash is that the project name, url and mailing list are specified when you build the dev guide using gitwash. If you change the mailing list in the wrapper script I mentioned then run it, I think it should regenerate the file you have changed with the correct mailing list address.

**Comment by ajdawson** [comment]
Closing after merge of #1957 which fixes the same issue.

**Pull request closed without merging**
