### PR TITLE
PI-3745: Stereographic plotting example using netcdf instead of GRIB data

### LINKED ISSUE #3745: Completely remove iris-grib from Iris testing
The reason this is important, is because as long as Iris testing uses Iris-grib, the testing has a problem with a "vicious circle" of dependencies :
  1. iris-grib tests must pass when run against an install of Iris, i.e. a release version (naturally, as iris is a key dependency) 
  1. but also, likewise, iris tests must pass with a particular version of iris-grib
      (if iris-grib is a **_test_**-dependency of iris)
  1. but sometimes, parallel changes are required to fix a problem -- i.e. neither new version will work with the old version of the other .  
    Then, **_one_** of them must be released first, despite it not passing in Travis :worried: 

By breaking the link, we can make necessary changes in Iris, which will still pass the Iris tests.
Releasing that may then break iris-grib, which can be fixed afterwards.

----
Background:
#3742  failed to fix this completely, as seen in [this comment](https://github.com/SciTools/iris/pull/3742#issuecomment-645941686)
> ... the GRIB data this [[example]] ... I can't replace with a netcdf version 

So to free **_all_** Iris testing from dependency on iris-grib,
 we need to amend the 'polar_stereo' example (or delete it)
#3746 proposes to do that.

### PR DESCRIPTION
**Pull request by pp-mo**
This finally addresses #3745, by providing a replacement for the example plot that was relying on GRIB source data.  The new plot uses different data (in netcdf).  
Hopefully, the alternative is good enough.

Closes #3745

### CODE REVIEW

**Comment by trexfeathers** [comment]
[Can also confirm that Travis is passing](https://travis-ci.org/github/SciTools/iris/builds/699724059). Link may have been broken by the PR name change.

**Comment by trexfeathers** [comment]
@pp-mo now that I've merged SciTools/iris-sample-data#27, are you happy that this PR is no longer **WIP**?

**Comment by pp-mo** [comment]
> are you happy that this PR is no longer WIP?

Absolutely :grin:

**Comment by trexfeathers** [comment]
I'm holding off until #3742 is merged as that seems like the less confusing sequence IMO

**Comment by pp-mo** [comment]
Thanks @trexfeathers 
So, I pushed an extra merge commit to restart the testing (since withdrawn..)
I have applied @abooton method here : producing a manual merge commit to fix problems, _instead_ of rebasing.
Dead easy in this case !

Unfortunately though .. it seems the conflict isn't the *whole* remaining problem...
What we missed was that the original green tick above was missing a Travis test (don't ask me why, this continues to happend sporadically).
The problem is that we need to ***release*** a new iris-sample-data to get this working.
Watch this space ...

**Comment by pp-mo** [comment]
https://github.com/SciTools/iris-sample-data/pull/28 refers.
If someone can address that, then I'll cut a new iris-sample-data version 2.3.

Then, of course, we will need ***another*** PR to bump the sample-data version to "2.4.0dev".

**Comment by pp-mo** [comment]
> If someone can address that, then I'll cut a new iris-sample-data version 2.3.

Actually no, now we need a friendly reviewer on the conda-forge feedstock : https://github.com/conda-forge/iris-sample-data-feedstock/pull/9
Not you or me, as we don't have merge there.  Possibly @bjlittle if he gets there first.

Quite a little dance, isn't it ?

**Comment by pp-mo** [comment]
Next to do: check for availability on conda-forge channel, then re-spin here...

**Comment by pp-mo** [comment]
Oh bother :tired_face:  
It seems we need a new image hash, and a new file in test-iris-imagehash too.
I think I only ran the docs build, not the example tests.
 - so, now that seems obvious !

**Comment by pp-mo** [comment]
>  @trexfeathers  I wasn't aware that we did graphics tests on the examples

Sorry, missed your update when I posted my latest.
Yes, for each sourcefile in `./docs/iris/example_code` there is a matching runnable test in `./docs/iris/example_tests` (though the division into separate subfolders is bot preserved).

I just hadn't run them.  And of course it wouldn't run on Travis till we got the new sample-data release.

**Comment by pp-mo** [comment]
Here we go ... https://github.com/SciTools/test-iris-imagehash/pull/34

**Comment by pp-mo** [comment]
> "New image hash"

This is going to fail again.
But should be OK on respin, once https://github.com/SciTools/test-iris-imagehash/pull/34 is merged.

**Comment by trexfeathers** [comment]
Hooray! 🎉
Merging before anything else happens

**Pull request merged**
