### PR TITLE
Add pseudo_level_type to entries in STASH_TRANS

### PR DESCRIPTION
**Pull request by jkettleb**
This is a bit speculative - I'm very happy to take comments and revise or drop.  Thanks to @marqh for helping put this one together. (@marqh I'm working from home so can not see if you have emailed me on this today - but the sparql query appears to be working

The pull request adds the pseudo level type to the information recorded against stash code in the STASH_TRANS dictionary.  The motivation for doing this is to allow applications to understand what the pseudo levels mean for a particular stash code.  This implementation is pretty minimalist - it does not attempt to assign the pseudo level type to any part of the cube or its pseudo level coordinate meta data.

The particular case that prompted this was a callback that needed to take action depending on the pseudo level type - in order to help interpret what the pseudo level values mean.

I'm a bit unsure of how the production of '_ff_cross_references' is managed.  I don't think its part of the setup.py like standard names as the resulting file is revision controlled in the repository.  So I'm guessing you just run it every now and again when you want to make changes to the content of STASH_TRANS. Sorry if I have this wrong.

### CODE REVIEW

**Comment by jkettleb** [comment]
Hello, I've added a gist to demonstrate a use of this pull request: https://gist.github.com/jkettleb/9ad83aba80dac288c377       I hope that gives a little more context.

any comments on this pull request?

Thanks, Jamie

**Comment by marqh** [comment]
thank you for the input @jkettleb 

Adding the pseudo_level type clearly has application for your case, I can see your use in the example gist

I expect that we would like to see some richer pseudo level comprehension over time, but this is a good first step.

the code to collect the cross references looks fine to me.

please may you add a new text file into 
https://github.com/jkettleb/iris/tree/pseudoT/docs/iris/src/whatsnew/contributions_1.9
briefly describing the change, for our documentation?

once you've done this, you can 'squash' your commits into 1 and then push the result to this PR (let me know if you're not sure about this step)
then I think this should be ready to commit

cheers
mark

**Comment by jkettleb** [comment]
thanks @marqh - I agree this is only a small next step for clearer pseudo level handling - there should be more to follow.

I'll add to that text file and squash.  Its likely to be next week now though.

**Comment by pelson** [comment]
:+1: with @marqh's suggested change.

**Comment by bjlittle** [comment]
Thanks @jkettleb :+1:

**Pull request merged**
