### PR TITLE
Deprecate legacy_custom_rules

### PR DESCRIPTION
**Pull request by rhattersley**
1. Deprecates use of `legacy_custom_rules`.
2. Gets rid of related unused bits:
 - `iris.fileformats.grib._load_rules`
 - `iris.fileformats.pp._load_rules`
 - `iris.fileformats.pp._ensure_load_rules_loaded`

### CODE REVIEW

**Comment by rhattersley** [comment]
I've added this to the 1.9 milestone to make sure we get the deprecation out before 2.0. Does that seem reasonable?

**Comment by pp-mo** [comment]
> @rhattersley  I've added this to the 1.9 milestone ... Does that seem reasonable?

Absolutely.

Could we not do more, though?
We still have supported (but essentially unused) functions for handling text rules
i.e. ```pp.add_save_rules``` + ```pp.reset_save_rules```.

If we deprecated **all**  this stuff, I think we are then free to reimplement the pp save rules + remove all the text rules legacy ?

**Comment by rhattersley** [comment]
> Could we not do more, though?

Absolutely. :wink:

But I'd prefer to chip away at it in multiple PRs.

> If we deprecated all this stuff, I think we are then free to reimplement the pp save rules + remove all the text rules legacy ?

:+1:

NB. Just because we've deprecated something doesn't mean we *have* to remove in v2.0, so we're not committing ourselves to anything.

**Comment by pp-mo** [comment]
> Just because we've deprecated something doesn't mean we have to remove in v2.0, so we're not committing ourselves to anything.

No, but we need to move sharp if we want to leave the option open.

**Comment by rhattersley** [comment]
Indeed. Are you going to put up a PR for the deprecations you suggest then?

**Comment by rhattersley** [comment]
@pp-mo - I've rebased to get rid of the #1837 problem (and snuck in some tests while I was at it!). All tests pass. :smile:

**Comment by pp-mo** [comment]
Good for me :-)

**Pull request merged**
