### PR TITLE
Remove deprecated module ff.py

### LINKED ISSUE #2641: Remove deprecated lib/iris/fileformats/ff.py
The module `lib/iris/fileformats/ff` was deprecated in Iris 1.10

https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/ff.py#L20

### PR DESCRIPTION
**Pull request by dkillick**
Removes the deprecated module `iris.fileformats.ff`, and the test module `test__ff_equivalents`, which existed to check that `ff.py` and `_ff.py` behaved the same. Now that `ff.py` has been removed, we don't need that test module.

Fixes #2641.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@dkillick What about the module iris.fileformats._ff.py and iris.fileformats._ff_cross_references.py? Do we still need them?

**Comment by dkillick** [comment]
@corinnebosley see https://github.com/SciTools/iris/issues/2641#issuecomment-317415157 for more detail.

**Comment by corinnebosley** [comment]
@dkillick Sorted.  In that case I'm happy to merge this.

**Comment by corinnebosley** [comment]
Build failed due to Travis Python version issue: https://github.com/SciTools/iris/pull/2769#issuecomment-335147830

Issue has been resolved, but I am unsure of next steps...

**Pull request merged**
