### PR TITLE
Update copyright years in license headers

### PR DESCRIPTION
**Pull request by lbdreyer**
The license header check doesn't run in this branch so we missed a few copyright years that need updating.

This is needed so before we can do the mergeback of this branch (see #3316 )

### CODE REVIEW

**Comment by QuLogic** [comment]
License check is skipped because this branch is [missing](https://github.com/SciTools/iris/blob/v2.2.x/.travis.yml#L128) the setting of `IRIS_REPO_DIR`, which is there on [master](https://github.com/SciTools/iris/blob/master/.travis.yml#L133).

**Comment by corinnebosley** [comment]
@lbdreyer What's the strategy here?  Are we bothered that some of the license headers are still wrong?  Surely the main thing here is that the checks are working.

What do you want to do?

**Comment by lbdreyer** [comment]
> License check is skipped because this branch is [missing](https://github.com/SciTools/iris/blob/v2.2.x/.travis.yml#L128) the setting of `IRIS_REPO_DIR`, which is there on [master](https://github.com/SciTools/iris/blob/master/.travis.yml#L133).
> 
> If you re-add that, it should run here.

Thank you @QuLogic. I have cherry-picked the commit that made that change to this PR.

We will just need to skip that commit when we do the mergeback onto master!



> @lbdreyer What's the strategy here? Are we bothered that some of the license headers are still wrong? Surely the main thing here is that the checks are working.
> 
> What do you want to do?

I'm going to update the license headers that the license header check is complaing about so that this won't be an issue to further PRs to this branch.
I'll fix this shortly!

**Comment by corinnebosley** [comment]
Thanks @lbdreyer!

**Pull request merged**
