### PR TITLE
Release branch close (v1.13.x, v2.0.x)

### PR DESCRIPTION
**Pull request by pelson**
No changes from me in this PR, simply merging v1.13.x and v2.0.x into master (hence these aren't my commits). I'm pushing here for transparency and Travis testing, but am comfortable merging this myself.

Once merged, I'll go ahead and remove the v1.13.x and v2.0.x branches, which are currently at a6d2764a71f21e9c5a4a7ac897a9efc654f735ad and 70a4052299a6c135990098ccbad006a57458be70 respectively.

### CODE REVIEW

**Comment by bjlittle** [comment]
@pelson For this PR does it matter if we `merge` or `squash and merge` ?

**Comment by QuLogic** [comment]
Do _not_ squash and merge; that would lose all merge parenting and the original commits. It would be best to just push from the command-line on this one.

**Comment by pelson** [comment]
> @pelson For this PR does it matter if we merge or squash and merge ?

Great question! I think we need to actually merge, not squash.

**Comment by pelson** [comment]
P.S. Go and do nice things on your week off!

**Comment by pelson** [comment]
> It would be best to just push from the command-line on this one.

Simply merging this as a PR is fine, but I agree, pushing directly doesn't concern me either. I'll go ahead and follow your suggestion though for good measure. 👍

**Comment by pelson** [comment]
Turns out I'm already behind, so I'll just do standard merge.

**Pull request merged**
