### PR TITLE
Quick demo method to handle unicode strings in units.

### PR DESCRIPTION
**Pull request by mo-g**
Hi all,

So, I'm looking at a situation where an api is returning a netCDF file which has unicode characters in the units. A little bit of research suggests to me that this is not discouraged, though it obviously isn't udunits-friendly.

This is presumably something that needs a slightly wider approach than just putting a fix in for this specific case - but thought it was worth raising this to discuss.

The below just tests for unicode characters in units and escapes them if it finds them.
E.G. ♫ would be \u266b

Not pretty, but relatively non-destructive as a conversation starter.

Thoughts?

### CODE REVIEW

**Comment by pelson** [comment]
Ability for the unit class to handle unicode input :+1: 
Doing it in the NetCDF loader :-1: 

This would make a good addition to https://github.com/SciTools/cf_units IMHO.

**Comment by ocefpaf** [comment]
Hi @mo-g,

If I understood what you are doing you want an elegant way to preserve the unit in the `attributes['invalid_units'] = attr_units` instead of failing, right?

Suppose you had u'℃' the loader will return `_UNKNOWN_UNIT_STRING`, but the `attributes['invalid_units']` will keep `'\\u2103'`.

I have to say that I have mixed feelings about this.  On one hand I would like it to fail early and tell the data provider to fix the netCDF attribute\*.  On the other hand, it is a nice idea to load the dataset, figure out the unit, and fix it yourself.

\*To me, the best way to fix transgressions to the cf_rules, is via iris `callback`.  Loading a non-cf dataset and fixing it afterwards might give the user the wrong idea that the data is compliant.  Maybe it boils down to what the cf_rules have to say about unicode units.

I guess that the relevant part of `cf_units` for your PR would be:

https://github.com/SciTools/cf_units/blob/master/cf_units/cf_units.py#L907

**Comment by mo-g** [comment]
@ocefpaf You're correct, that's what I'm trying to do. Currently trying to load a netCDF file with a unicode unit throws an exception.

CF conventions suggest that only UDUNITS-compatible (plus a few special values) units are compliant - as such the metadata being provided aren't CF compliant. I think it's preferable to handle this, as Iris already handles non-CF compliant units that are ASCII-formatted.

@pelson, I think this is possibly the right place for it after all. As @ocefpaf noted, the problem is not the unit class itself because a unicode unit is not a UDUNIT - so it is already not CF compliant and falls back to unknown. The loader however is trying to print a warning and add a cube attribute to notify the user, and these are raising exceptions. So, it's the loader that needs to be fixed.

I've tested the fix on my sample data and it works as expected:

Output of iris.load()
iris/lib/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:1303: UserWarning: Ignoring netCDF variable 'Precipitation_rate' invalid units 'kg/m\\xb2s'
  warnings.warn(msg.format(msg_name, msg_units))
[<iris 'Cube' of Precipitation rate / (unknown) (model run base time: 1; time: 1; latitude: 720; longitude: 647)>]

Cube attributes:
          invalid_standard_name: Precipitation_rate
          invalid_units: kg/m\xb2s

Think this is a plausible for pulling (with some polishing)?

**Comment by pelson** [comment]
> Think this is a plausible for pulling (with some polishing)?

Yep. I'm on board. A simple unit test would push this through IMHO.

**Comment by ocefpaf** [comment]
:+1:

**Comment by mo-g** [comment]
I'm thinking here: https://github.com/SciTools/iris-test-data/blob/master/test_data/NetCDF/testing/units.nc is a good place to add an extra cube with ♫ invalid units ♫ of some description (m³)? I'll investigate how I can do that, and put up a PR.

**Comment by mo-g** [comment]
@pelson Ok, this is passing tests (including the one I wrote). Should I add a test to check it handles ASCII input as well, or is this acceptable? (Integration tests are currently testing that.)

**Comment by pelson** [comment]
Looks like this is being targeted against v1.8.x.

**Pull request closed without merging**
