### PR TITLE
V3.7.x.updates

### PR DESCRIPTION
**Pull request by pp-mo**
Whatsnew text finalisation + renames, suitable for release branch docs

### CODE REVIEW

**Comment by pp-mo** [comment]
Hi @HGWright 
Named you again !
Please see if you like this. Especially, check out the docs (from the tests tick, when they've built)

This step is almost entirely about getting the docs to look right.
FWIW I'm not totally happy about the "no major highlights", but I can't see what else to say.
If you think it looks better, we can remove the highlights section altogether for this one.

**Comment by pp-mo** [comment]
Sorry, please hold off.  Fixing a docs-build problem ...
(converted to Draft)

**Comment by pp-mo** [comment]
Ok fixed !
Here's the whats-new from the built docs : https://scitools-iris--5424.org.readthedocs.build/en/5424/whatsnew/index.html

Please review @HGWright !

**Review by HGWright — APPROVED** [review]
Good to see RTD working on this PR. I think that there are 2 option with regards to the 'Major Highlights' of the release, and I will leave the decision to you @pp-mo.

1. Leave it as is, because there is nothing of the size that usually constitutes a major highlight.
2. Take the oppertunity to highlight some more niche but still good/important changes.

**Comment by pp-mo** [comment]
Ok thanks @HGWright 
See what you think of this approach ...

**Comment by HGWright** [comment]
Looks better! Very happy for this to be merged.

**Pull request merged**
