### PR TITLE
re-added fix for netcdf datasets always returning as MaskedArrays

### PR DESCRIPTION
**Pull request by corinnebosley**
This fix caused errors previously with versions of something or other.  Fix has been rebased (effectively).

I wonder what will happen...

### CODE REVIEW

**Comment by corinnebosley** [comment]
@pp-mo It looks very much like the attribute `set_always_mask` doesn't exist in netcdf4 1.4 for python 2.7.

I don't know how that can be so, but it is.  Probably.

**Comment by corinnebosley** [comment]
Raised the issue as a question really with netcdf4 people:
https://github.com/Unidata/netcdf4-python/issues/848

Don't really want to wait for them to fox it and release it before we fix this our end though.  But it may be the case that we can only apply this fix to Python 3.6 environments though.  How do you feel about that?

**Comment by pp-mo** [comment]
The problem here is that netcdf gets DOWNgraded when we install the grib api !
See the output in the logfile following the command 
`$ if [[ "$TEST_MINIMAL" != true && ${TRAVIS_PYTHON_VERSION} == 2* ]]; then conda install --quiet -n $ENV_NAME python-ecmwf_grib; pip install git+https://github.com/SciTools/iris-grib.git@v0.11.0; fi`

Of course, that only happens in Python 2 because we have no Python 3 grib api ...

**Comment by corinnebosley** [comment]
@pp-mo aah, I see... well I'm still a bit confused about the conda list of packages that constituted the environment, but that certainly explains a lot.  OK, I'll close this and we'll continue with https://github.com/SciTools/iris/pull/3181

**Comment by pp-mo** [comment]
> a bit confused about the conda list of packages that constituted the environment

The output from the first "conda list" command is ok, but it turns out not the final word as if iris-grib gets installed (Python2 only), that is done separately _and later_, so that modifies the original conda environment.

**Pull request closed without merging**
