### PR TITLE
removed CMAttribute and very old text file

### LINKED ISSUE #2670: Remove deprecated class `iris.fileformats.rules.CMAttribute`
The class `iris.fileformats.rules.CMAttribute` was deprecated in Iris 1.10

https://github.com/lbdreyer/iris/blob/015cee9877df87d64e84146975feb9eefea84591/lib/iris/fileformats/rules.py#L235

### PR DESCRIPTION
**Pull request by corinnebosley**
This mosig codes text file used to be used for loading, but has not been used since 2013, just got left lying around dying slowly and painfully.

I'm putting it out of its misery.  It's the kindest thing to do.

Also:
Closes #2670

### CODE REVIEW

**Comment by dkillick** [comment]
@corinnebosley you haven't removed the unused imports from `rules.py` ⚠️ Could you do so and then we can get this merged.

**Comment by corinnebosley** [comment]
@dkillick So it turns out I pushed up the change you requested to the wrong branch, so I'll just make the same change to this one instead.

I apparently also have to rebase...

**Comment by corinnebosley** [comment]
@dkillick No I don't. No rebasing necessary.  I wonder where I saw that conflict message then...

**Comment by corinnebosley** [comment]
@dkillick I had messed up a couple of things in the confusing rebase, so I have tried to correct them now.  I hope there's no other mistakes that I (and most of the tests, worryingly) have missed...

**Comment by corinnebosley** [comment]
Please GitHub, please please find my commit and tell Travis to run the tests on it...

**Pull request merged**
