### PR TITLE
Daskversionfix 1v2

### PR DESCRIPTION
**Pull request by pp-mo**
**WIP** do not merge

### CODE REVIEW

**Comment by lbdreyer** [comment]
It works ... So I wonder why #3431 doesn't pick up dask 1.2 ? :confused:

**Comment by pp-mo** [comment]
>  I wonder why #3431 doesn't pick up dask 1.2 ?

😕 indeed.  N.B. the commit is exactly the same as the first one here.

However, it _does_ seem to be an adequate fix ...

**Comment by pp-mo** [comment]
> why #3431 doesn't pick up dask 1.2 ?

Comparing the `conda list` output, the ***only*** differences are ...

| package | "OLD" pin dask>=1.1 | | | // |  "NEW" pin dask>=1.2  | | | |
| ---- | - | - | - | - | ---- | - | - | - |
| dask (AND dask-core) | 1.1.4 | py27_1 | defaults | //  | 1.2.2 | py_3 | conda-forge |
| pyproj | 1.9.6 | py27h14380d9_0  | defaults |  // | 1.9.6 | py27h516909a_1002 | conda-forge |

In fact that's so odd I don't believe it.
Maybe the underlying channels have  just shifted ??
I will re-spin the original checks ...

**Comment by pp-mo** [comment]
> I will re-spin the original checks ...

Nope, still does the same.
:sigh:

**Pull request closed without merging**
