### PR TITLE
Run Travis tests in serial

### PR DESCRIPTION
**Pull request by djkirkham**
Fix to get the tests passing while we investigate why there are now so many time-outs.

### CODE REVIEW

**Comment by djkirkham** [comment]
Closes #2752

**Comment by djkirkham** [comment]
The tests do still time out sometimes, but if the --process-timeout value is set too high Travis itself times out. I think this is the best we're gonna get.

@lbdreyer @pp-mo

**Comment by lbdreyer** [comment]
@ajdawson If you look at the travis output for the python 2.7 job you can see that running it in serial completed without a problem in just under 15 mins

**Comment by ajdawson** [comment]
There may be a happy medium somewhere. I've also never seen timeouts locally, but I've never used more than 8 cores for testing. I think Travis nodes present 64 cores which our tests will use. How do things look on 4 cores say?

**Comment by lbdreyer** [comment]
@djkirkham can you make an issue to remind us to revert this to ensure it is only temporary?

**Comment by lbdreyer** [comment]
I tested it with different numbers of processors and got the following results (note that I only ran each test once so the timings won't be that reliable):

|No. of Cores|py27 default tests|py27 min test|py27 coding|py27 example|py27 doctests|py35 default tests|py35 minimum test|py35 coding tests|py35 example tests|py35 doctests| 
|---|---|---|---|---|---|---|---|---|---|---|
|[1](https://travis-ci.org/lbdreyer/iris/builds/267998225)|15m11|5m41|6m16|8m11|9m22|11m55|4m13|8m10|7m23|10m24|
|[4](https://travis-ci.org/lbdreyer/iris/builds/267997533)|6m56|5m29|6m3|6m57|10m8|6m|6m12|6m56|7m4|10m17|
|[8](https://travis-ci.org/lbdreyer/iris/builds/267989912)|5m23|5m31|6m32|6m19|6m37|4m26|3m47|6m9|6m34|9m29|
|[16](https://travis-ci.org/lbdreyer/iris/builds/267998524)|TimedOut|3m59|4m19|6m40|10m25|TimedOut|5m49|6m47|7m28|9m51|

I could do more testing but I think setting 8 processors might be our best bet

**Pull request merged**
