### PR TITLE
Adapt to the latest setuptools editable configuration.

### PR DESCRIPTION
**Pull request by trexfeathers**
### Description

[See the release log for setuptools `v64`](https://setuptools.pypa.io/en/latest/history.html#v64-0-0). Basically `self.build_lib` is no longer a reliable way of telling whether we are doing a build or an in-place install, but `setuptools` now provides `self.editable_mode` so we can use that instead.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by bjlittle** [comment]
@trexfeathers You also require to update the `requitements/ci/*.yml` files and the `setup.cfg` for the `setuptools` min pin 👍

**Comment by trexfeathers** [comment]
> @trexfeathers You also require to update the `requitements/ci/*.yml` files and the `setup.cfg` for the `setuptools` min pin 👍

Thanks @bjlittle, I had forgotten setuptools was in there too 😳

2b322899ca6148532c81cb4f0b3c97786e86de98

**Review by bjlittle — APPROVED** [review]
@trexfeathers Awesome fix 💯

Merging on the Eurostar 🤓

I 💜 OS development

**Comment by rcomer** [comment]
> Merging on the Eurostar 🤓

Bon Voyage @bjlittle!

**Pull request merged**
