### PR TITLE
Define Iris 2.4

### PR DESCRIPTION
**Pull request by pp-mo**
@pp-mo replacement for #3636, because @trexfeathers is absent today.

I have implicitly accepted the commits from #3636,
and will be completing remaining tasks ..
  * [x] fix remaining grib test failures  (since https://github.com/SciTools/iris/pull/3638/commits/1148b3740a224fffbf56f3566fec9b02a25c7fee)
  * [x] review all commits inherited from #3636 (i.e, up to https://github.com/SciTools/iris/commit/57d82fab3a458b55d4bd16c24a54b0d92eee407a), and if needed ...
    * ~[ ] add further corrections~
    * ~[ ] get additional independent review ?~
    * [x] okay to go
  * [x] complete release notes

Next + afterwards (todo on 2.4.x branch) ...
  * fix version string
  * tag RC
  * make release

### CODE REVIEW

**Comment by pp-mo** [comment]
**Grib tests fixing**

**Problem:**
We include above the [commit 6735245 "Fixes required due to the release of iris-grib v0.15.0 (#3582)"](https://github.com/SciTools/iris/pull/3638/commits/67352455734eaf8328024292f728bce3b068ed6b), which is cherry-picked from master :  This PR fixed outstanding problems with several Iris grib tests (which had gone stale), and ***also*** made key changes for compatibility with iris-grib v 0.15.
The problem is that while it "fixes" all the iris grib tests, it also means they now only work with iris-grib >= 0.15 -- ***which is not compatible with python 2***.

So... this all works ok when testing under python3 with iris-grib v0.15 
See : [all-phases Travis test page](https://travis-ci.org/SciTools/iris/builds/636989422?utm_source=github_status&utm_medium=notification)

... but when run in python2, against iris-grib 0.14, it introduces a bunch of problems
See : [Travis log for initial results in python2](https://travis-ci.org/SciTools/iris/jobs/636989425?utm_medium=notification&utm_source=github_status)
What is notable here :
  1. tests with python3 and iris-grib v0.15 all pass
  1. tests with python2 and iris-grib v0.14 have a bunch of problems :
    a) one test not running because it expects to import iris_grib.GRIBcode (>=0.15 only)
    b) a lot of tests failing because they expect the GRIB_PARAM attribute
      * either explitly in test code
      * or in results files used in a `tests.assertCML()` 

**Fixing:**
Now added [commit 76afe7c "Hacked tests.integration.test_grib2 to avoid import error from iris-grib version < 0.15."](https://github.com/SciTools/iris/pull/3638/commits/76afe7ca946f9a7e33db7591d9be72ec59bd5731) to enable `iris.tests.integration.test_grib2` to function with iris=grib v.0.14 (in python2 testing).
Re-spun tests ... [Travis page showing python2/python3 test results](https://travis-ci.org/SciTools/iris/builds/637377190?utm_source=github_status&utm_medium=notification)
... shows python3 still working, and python2 problems now reduced to "expected" differences, as checked against  changes in iris-grib 0.15, listed in [0.15 release notes](https://github.com/SciTools/iris-grib/releases/tag/v0.15.0).

**Comment by pp-mo** [comment]
Latest commit https://github.com/SciTools/iris/pull/3638/commits/1148b3740a224fffbf56f3566fec9b02a25c7fee prevents install of iris-grib in Python 2.
This means all the grib testing is skipped in Python 2, to avoid the known test problems with iris-grib v0.14.

The [above comment](https://github.com/SciTools/iris/pull/3638#issuecomment-574629052) demonstrates that iris 2.4 does "work" with iris-grib v0.14, though the tests do not all pass for reasons given.  
This **should be good enough**, as we don't expect to develop any further beyond Iris 2.4

**Comment by pp-mo** [comment]
@lbdreyer @trexfeathers 
Good to merge now, I hope.
See list of following TODOs above in main PR description -- these to be done in separate PRs I think

**Comment by trexfeathers** [comment]
> Latest commit 1148b37 prevents install of iris-grib in Python 2.
> This means all the grib testing is skipped in Python 2, to avoid the known test problems with iris-grib v0.14.
> The above comment demonstrates that iris 2.4 does "work" with iris-grib v0.14, though the tests do not all pass for reasons given.
> This should be good enough, as we don't expect to develop any further beyond Iris 2.4

Agreed. The tests failed exactly how we would predict them to. No other failures occurred

**Pull request merged**
