### PR TITLE
Bump version to 2.3.0rc0

### PR DESCRIPTION
**Pull request by lbdreyer**

### CODE REVIEW

**Comment by bjlittle** [comment]
Waiting for travis-ci...

**Comment by bjlittle** [comment]
@lbdreyer Nice one, thanks!

Can https://github.com/SciTools/iris/pull/3441 make the cut before we tag?

**Comment by bjlittle** [comment]
@lbdreyer Did you now want to follow-up this PR with a PR to `master`, bumping the version to `3.0dev0` ?

**Comment by lbdreyer** [comment]
> @lbdreyer Nice one, thanks!
> 
> Can #3441 make the cut before we tag?

Don't worry! Still got a few little things to do before tagging! Then I'll do a final check that we haven't missed anything

**Pull request merged**
