### PR TITLE
LinearRegridder rebrand.

### PR DESCRIPTION
**Pull request by bjlittle**
First baby step forward to incorporating nearest neighbour regrid via the new API.

Rebrand the `LinearRegridder` as `RectilinearRegridder` akin to `RectilinearInterpolator`, so that we have a consistent API.

### CODE REVIEW

**Comment by bjlittle** [comment]
Heads up @rhattersley  ...

**Comment by rhattersley** [comment]
:+1: 

Do you plan to rename `iris.analysis._linear`? Or even merge it into `iris.analysis._interpolation`?

**Comment by bjlittle** [comment]
@rhattersley Yup. 

I'll rename it later, most likely as one of the last PRs. It'll make sense to do this when I actually fold in the connective tissue for the nearest regridding capability. At that point the filename won't make sense because it'll be handling `linear` and `nearest`. :smiley:

**Comment by rhattersley** [comment]
OK, thanks.

**Comment by bjlittle** [comment]
BTW do you have a preference? A rename or merge into `_interpolation` ? I never considered it as an option ...

**Comment by rhattersley** [comment]
> BTW do you have a preference?

No, not really.

**Comment by bjlittle** [comment]
:+1: Fab, thanks @rhattersley !

**Pull request merged**
