### PR TITLE
Prevent color bar from being misplaced

### PR DESCRIPTION
**Pull request by krikru**
Currently, if `plt.gca()` gives a different Axes object than `axes` in the function `_label`, the color bar will be malpositioned, ending up either on another subfigure, or in another figure window altogether. Specifying the `ax` argument when calling `plt.colorbar` prevents this.

### Description

This code edit specifies the `ax` argument to the `plt.colorbar` function, which can be necessary in case matplotlib adds the colorbar to the wrong subfigure.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by bjlittle** [comment]
Hey @krikru! Thanks for the contribution to `iris` :+1: 

If possible, could you sign our CLA, then we'll be able to accept your pull-request. See https://scitools.org.uk/cla/v4/form

**Comment by krikru** [comment]
@bjlittle I signed the CLA now, and used "krikru@users.noreply.github.com" in the "Email" field (the same address as I use for my Git commits). I hope that's okay?

**Comment by bjlittle** [comment]
@krikru Awesome, thanks for doing that so quickly :beers: 

I think that should be okay. I'm going to close this PR and then re-open it. That should nudge the `bot` that performs the CLA check, to re-check the signed CLAs, which I can see that you've successfully signed :+1:

**Comment by bjlittle** [comment]
I'll also look through our unit tests to see if there is any additional tests that we can add to cover your change.

I'm happy to do that on your behalf. If I do find any suitable additions, then I'll make a pull-request on your development branch, so that you can see the changes I'm proposing. If you're happy, then simply merge my pull-request and it'll automatically become part of this pull-request.

Additionally, I'll also make an entry in our documentation [whatsnew](https://scitools-iris.readthedocs.io/en/latest/whatsnew/index.html#iris-whatsnew) highlighting your awesome contribution :partying_face: 

Also, you're timing is just perfect! We're scheduled to release `iris` 3.3 at the beginning of September, so your change will go live very soon :smile:

**Comment by bjlittle** [comment]
@krikru Looks like our CLA bot is happy! So, welcome to `iris` :beers:

**Comment by krikru** [comment]
> I'll also look through our unit tests to see if there is any additional tests that we can add to cover your change.

What I'm doing is creating two figures with subfigures, then calling [iris.quickplot.pcolormesh](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/quickplot.html#iris.quickplot.pcolormesh) with the `axes` argument set to the axes object of a subfigure in the first figure. This originally caused the colorbar to be drawn in the second figure. Maybe you can create a test based on that description.

> Also, your timing is just perfect! We're scheduled to release `iris` 3.3 at the beginning of September, so your change will go live very soon 😄

That's great!

> @krikru Looks like our CLA bot is happy! So, welcome to `iris` 🍻

Thanks!

**Comment by bjlittle** [comment]
Hey @krikru, I've just pushed the pull-request https://github.com/krikru/iris/pull/1 on this pull-request `patch-1` branch. Take a look, review and merge if your happy :+1:

**Review by bjlittle — APPROVED** [review]
@krikru Great first contribution to `iris`, many thanks :beers: :partying_face:

**Pull request merged**
