### PR TITLE
fix setup.py std_names building

### LINKED ISSUE #4951: Failure to build CF Standard Names with setup.py std_names
## 🐛 Bug Report
Since the introduction of #4903 we are now are unable to successfully perform the commands:
 - `python setup.py develop`
 - `python setup.py std_names`

Note that, 
 - `pip install --editable .` does work and successfully builds the `iris.std_names`
 - The `iris.std_names` are successfully built when performing `python setup.py build` or `python -m build --wheel`

These failures are due to the `editable_mode` attribute being unavailable from `setuptools` commands or custom commands.

## How To Reproduce
Steps to reproduce the behaviour:

<details><summary> python setup.py develop</summary>
...

Using /net/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages
Finished processing dependencies for scitools-iris==3.4.0.dev18
Traceback (most recent call last):
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 123, in <module>
    setup(
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 96, in run
    if self.editable_mode:
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: editable_mode
</details>

<details><summary> python setup.py std_names</summary>
running std_names
Traceback (most recent call last):
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 123, in <module>
    setup(
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 96, in run
    if self.editable_mode:
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: editable_mode
</details>

## Expected behaviour
Expect to successfully perform an "editable" install using `develop`, and build the CF Standard Names as part of that installation, or standalone with the `std_names` custom command. 

## Environment 
 - Iris Version: `main`, `3.3.0`
</details>

### PR DESCRIPTION
**Pull request by bjlittle**
### Description
This PR adds the `editable_mode` attribute (defaulting to `True`) to the [setuptools.command.develop.develop](https://github.com/pypa/setuptools/blob/main/setuptools/command/develop.py#L14) command subclass and custom `setup.BaseCommand` command class.

Closes #4951

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by bjlittle** [comment]
@lbdreyer I've resolved the conflicts, and I'll add a suitably beefed=up `whatsnew` entry.

Also, I may just experiment with a slightly different approach, so I'll pop the PR into `draft` for the moment until I've finished experimenting, then I'll ping you when I'm done :+1:

**Comment by bjlittle** [comment]
@lbdreyer The difficulty with this stuff is that we generally don't have infrastructure testing... and to be fair, if we did it would be a bit OTT IMHO.

Anyways, you can certainly kick the tyres of the changes here by performing the following commands:
- `pip install --no-deps --editable .`
- `python setup.py std_names`
- `python setup.py develop`
- `python setup.py build`
- `python -m build` (if you have `build` installed from pypa)

**Review by lbdreyer — COMMENTED** [review]
Could you explain a bit about why you have taken this approach of incorporating the `build_std_names`  into `CustomCommand` as this means that any custom command we create will always include `build_std_names`. I suppose I can't think of an example command where we wouldn't want to build the std_names. 

I just wanted to check with you first, but otherwise it looks good to me

**Comment by bjlittle** [comment]
> Could you explain a bit about why you have taken this approach of incorporating the `build_std_names` into `CustomCommand` as this means that any custom command we create will always include `build_std_names`. I suppose I can't think of an example command where we wouldn't want to build the std_names so maybe the code duplication saving is worth it

Good question.

TBH I just saw it as an opportunity to rationalise what we have. I don't see the point in having a generic mechanism that's simply not being used. Essentially all the remaining commands are following the same pattern i.e., require to create the standard names, so I've pulled that behaviour together within the `CustomCommand` class to make things honest and hopefully more obvious. 

I think overall the `setup.py` is now looking a lot simpler, given what it used to look like over its history. 

Happy to make any changes that you recommend, if you want to take a different approach. But at the end of the day, if we find we do indeed need generic command behaviour, then we can simply address that when it arises. Otherwise I'd be keen to keep things as simple as possible (and yeah, `setuptools` is a world that's far from simple :exploding_head:).

**Comment by lbdreyer** [comment]
>I don't see the point in having a generic mechanism that's simply not being used.

That all does make sense to me and I agree that it's nicer to keep it simple.

Alright,  I'll go ahead and merge this in! Thanks @bjlittle !

**Review by lbdreyer — APPROVED** [review]

**Comment by trexfeathers** [comment]
>The difficulty with this stuff is that we generally don't have infrastructure testing... and to be fair, if we did it would be a bit OTT IMHO.

Related: https://github.com/SciTools/iris/issues/4730#issuecomment-1119550639

**Pull request merged**
