### PR TITLE
Python 3 __dict__ inheritance

### PR DESCRIPTION
**Pull request by QuLogic**
For whatever reason, the `__dict__` property does not get inherited, so it needs to be re-implemented in a few classes.

### CODE REVIEW

**Comment by rhattersley** [comment]
It might be better to fix this by defining `__slots__ = ()` for these classes (instead of defining the `__dict__` property.)

**Comment by QuLogic** [comment]
I'm not sure that would do anything as I think that's already true:
```
In [1]: from collections import namedtuple
In [2]: Foo = namedtuple('Foo', 'foo bar')
In [3]: class Bar(Foo): __eq__ = lambda self, other: True

In [4]: f = Foo(1, 2)
In [5]: f.__slots__
Out[5]: ()

In [6]: b = Bar(1, 2)
In [7]: b.__slots__
Out[7]: ()
```

**Comment by rhattersley** [comment]
> I'm not sure that would do anything as I think that's already true:

Without getting in to the subtleties of it all (I'd have to spend a while researching them!):
```python
>>> class Wibble(Foo): pass
>>> Wibble(1, 2).__dict__
{}

>>> class Wobble(Foo): __slots__ = ()
>>> Wobble(1, 2).__dict__
OrderedDict([('foo', 1), ('bar', 2)])
```

**Comment by QuLogic** [comment]
Oh, of course, I tested it by setting `__slots__` after class creation and not during.

**Comment by QuLogic** [comment]
OK, switched to `__slots__`, but only where necessary. Does it make sense to add it on all the `namedtuple` derivatives?

**Comment by rhattersley** [comment]
> Does it make sense to add it on all the namedtuple derivatives?

Not sure... probably yes. It appeals from a consistency point of view, and the derivatives were all intended to be immutable.

Out of interest, how did you spot the need for this PR? (I'm trying to recreate the relevant test failures so I can better understand the possible impact.)

**Comment by rhattersley** [comment]
> Out of interest, how did you spot the need for this PR? (I'm trying to recreate the relevant test failures so I can better understand the possible impact.)

I think I've tracked this down to things like `_CoordMetaData.__eq__` failing because its calls to `self._asdict()` and `other._asdict()` return `{}` on Python 3 without this PR.

**Comment by rhattersley** [comment]
>> Does it make sense to add it on all the namedtuple derivatives?
> 
> Not sure... probably yes

Enough vagueness! If I have to choose an option, then :+1: for slots. :wink:

**Comment by QuLogic** [comment]
I added it to everything except `ArrayStructure`, where it cannot be added because the `__new__` sets the `self.size` attribute.

**Comment by QuLogic** [comment]
Tests currently broken by ContinuumIO/anaconda-issues#445.

**Comment by rhattersley** [comment]
> I added it to everything except ArrayStructure, where it cannot be added because the __new__ sets the self.size attribute.

We could define `size` as a property instead?

**Comment by QuLogic** [comment]
Yep, seems to work alright.

**Comment by rhattersley** [comment]
Looks good. :+1:

**Pull request merged**
