### PR TITLE
https://github.com/metarelate/metOcean/issues/66

### PR DESCRIPTION
**Pull request by marqh**
updates to translations from
https://github.com/metarelate/metOcean/issues/66

### CODE REVIEW

**Comment by rhattersley** [comment]
Looks good from a content point of view. :+1: 

@pp-mo - do you want this against 1.9.x or master?

**Comment by pp-mo** [comment]
I suppose it has to be an improvement on the existing, so please target 1.9.x and I'll include it

**Comment by marqh** [comment]
> I suppose it has to be an improvement on the existing, so please target 1.9.x and I'll include it
@pp-mo 
it is targeting 1.9.x so we should be good to go

**Comment by rhattersley** [comment]
Are updates to these mappings ever mentioned in the "what's new" pages?

**Comment by pp-mo** [comment]
Sorry, missed that !

**Pull request merged**
