### PR TITLE
Delete equalise_cubes.py and add whatsnew

### PR DESCRIPTION
**Pull request by wjbenfold**
### Description

Remove `iris.experimental.equalise_cube`, closing #3528

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by wjbenfold** [comment]
Not sure where in what's new this belongs - is it Internal or a Deprecation (which I assumed were things we're deprecating now, not removing having previously deprecated them)

**Comment by lbdreyer** [comment]
I'm tempted to say it may make more sense for the whats new to be added to deprecations. We state that something will be deprecated, and then follow this up by confirming it has actually been removed, and no longer available. As a user, if I wanted to check when it was actually removed, my first port of call would be to look under the "deprecations" section as it is related to that. 
I wouldn't think a user should necessarily have to concern themself with what goes in "internal" so they may not look there

**Comment by lbdreyer** [comment]
Don't think I made myself so clear in the lat comment, so to follow up: I think removing code is _part of the deprecation_ process so the what's new should live under the deprecations heading

**Review by rcomer — APPROVED** [review]
I agree it makes sense to have the whatsnew in internal.  The user will see no functional change (other than a different error message if they try to import this module).

Edit: x-post with @lbdreyer and will defer to her!

**Comment by lbdreyer** [comment]
> Edit: x-post with @lbdreyer and will defer to her!

Whoops! danger of commenting at the same time! But I suppose this proves there's no correct answer; both have valid reasons.

Another point I wanted to mention though: I think this is a bit of a strange deprecation, in that we changed the code of the old function. Normally I would expect, when using the function, to get a deprecation warning, but to still be able to use it, until its eventual removal. In that example, I would say it definitely belongs in deprecations

**Comment by lbdreyer** [comment]
Thanks @wjbenfold !

**Pull request merged**
