### PR TITLE
Enable Python 3

### PR DESCRIPTION
**Pull request by QuLogic**
Some minor last fixups; add to Travis, fix doc build, add what's new.

### CODE REVIEW

**Comment by QuLogic** [comment]
Hmm, seems like grib is still installed on Python 3 even though you say it's removed?

**Comment by rhattersley** [comment]
> Hmm, seems like grib is still installed on Python 3 even though you say it's removed?

I've removed the Python 3 builds, so that shouldn't happen any more. On my machine I now get:
```
Solving package specifications: ........................................................
Error: Unsatisfiable package specifications.

...

Hint: the following packages conflict with each other:
  - ecmwf_grib 1.12.1
  - python 3.4*
```

So your fix to avoid installing ecmwf_grib is still useful.

**Comment by rhattersley** [comment]
The only remaining failure is from the `doctest` testing mode. Ideally we should modify it to skip the `iris.fileformats.grib` package. This would let the doctests run.

A simple hack would be:
```
--- a/docs/iris/src/sphinxext/generate_package_rst.py
+++ b/docs/iris/src/sphinxext/generate_package_rst.py
@@ -259,7 +259,11 @@ def do_package(package_name):
                      for imp_name, path in module_folders.get(package, []))
 
         paths.sort()
-        doc = auto_doc_package(package_path, package, root_package, paths)
+        try:
+            doc = auto_doc_package(package_path, package, root_package, paths)
+        except ImportError:
+            print('Skipping document for {} ...'.format(package))
+            continue
 
         package_dir = out_dir + package.replace('.', os.path.sep)
         if not os.path.exists(package_dir):
```

(There's also [sphinx-apidoc](http://sphinx-doc.org/man/sphinx-apidoc.html) which has a command line option to exclude certain paths. But I don't know how similar that is to our current auto-generation.)

**Comment by QuLogic** [comment]
I added something a little lower in the generation to produce a short error message in the documentation instead of what would normally be there for an import error. This should make the Python 3 build pass, too.

**Comment by rhattersley** [comment]
> I added something a little lower in the generation to produce a short error message for an import error in the documentation

That's a nice touch. :+1: :smile:

**Comment by rhattersley** [comment]
I've had a look at the built docs on my Python 3 installation and it works like a charm. :smile:

**Comment by rhattersley** [comment]
Thanks @QuLogic !

**Pull request merged**
