### PR TITLE
remove pp_packing.c

### PR DESCRIPTION
**Pull request by ocefpaf**
I believe that with https://github.com/SciTools/iris/blob/master/minimal-conda-requirements.txt#L27 `iris` no longer needs `pp_packing.c`, right?

### CODE REVIEW

**Comment by marqh** [comment]
Hello @ocefpaf 

we have removed the build of this from build channels and deprecated it, but I would rather delay the removal of this until a major version change.  I hope there will be such a major version change, potentially this will be the next release.

I would like to hold off on this change until the 'major version' is confirmed and we are handling the list of deprecation changes as a set.

**Comment by ocefpaf** [comment]
No problem @marqh. The only reason I sent this is b/c it was a low hanging fruit and I love PRs that removes code :smile: 

Feel free to close this or wait for the right moment. (As far as I know both `conda-forge` and SciTools recipes are already using the `mo_pack` and removed the dependency on `numpy`'s ABI from `iris`.)

**Comment by pelson** [comment]
Looks like this got done in another PR in #2689.
Thanks for this @ocefpaf - sorry we missed it and you didn't get an Iris commit from it 😞

**Comment by ocefpaf** [comment]
No problem. I'm anxiously waiting for the new version with dask ;-)

**Pull request closed without merging**
