### PR TITLE
Add m01s03i227 to the STASHCODE_IMPLIED_HEIGHTS dictionary

### PR DESCRIPTION
**Pull request by ehogan**
I have added `m01s03i227` with a height of `10.0` to the `STASHCODE_IMPLIED_HEIGHTS` dictionary. There is evidence that this STASH code has an implied height of 10.0m; the [STASHmaster](https://code.metoffice.gov.uk/trac/um/browser/main/trunk/rose-meta/um-atmos/HEAD/etc/stash/STASHmaster/STASHmaster_A) file (line 4680) states that the name for `m01s03i227` is `10 METRE WIND SPEED ON B GRID`. The `STASHCODE_IMPLIED_HEIGHTS` dictionary already has entries for the STASH codes `m01s03i225` and `m01s03i226`, which have the names `10 METRE WIND U-COMP` and `10 METRE WIND V-COMP`, respectively.

### CODE REVIEW

**Comment by pelson** [comment]
Ping @marqh

**Comment by marqh** [comment]
HI @ehogan 

this file is to be edited by an automated process, (tools/gen_translations.py) , so that we can maintain consistency with the metarelate metOcean database.

I'll get in touch with you directly with some tips on how to propose this update through that route

mark

**Comment by ajdawson** [comment]
Can you record the steps here once you are done so we have some reference on how this is completed?

**Comment by ehogan** [comment]
Apologies, I just noticed the nice big message saying `DO NOT EDIT` at the top of https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/um_cf_map.py#L18. \*facepalm\*

@ajdawson, I've written up what I did:

1. Go to http://www.metarelate.net/metOcean/search/
2. Type `m01s03i227` in the "Rdfobject:" box and click the "Search" button
3. Click on the link presented on the "search results" page
4. Right-click on the "Download a JSON-LD encoding of this mapping" link at the bottom of the page and "Save Link As..." (the name of the file is not important)
5. Repeat steps 1-3 for a STASH code already in `STASHCODE_IMPLIED_HEIGHTS` dictionary (I used `m01s03i225`), then click on the "Download a JSON-LD encoding of this mapping" link at the bottom of the page
6. Edit the `m01s03i227` file appropriately using the information for `m01s03i225` i.e., copy the height specific information for `m01s03i225` and update the `dc:replaces` entry so that the value equals the link provided on the `m01s03i227` "search results" page (it's ok to ignore the `@id` entries)
7. Go to http://www.metarelate.net/metOcean/ and click "login"
8. Click the "Create branch" button
9. Click on the "General translation." link (near the bottom of the page)
10. Click the "Browse..." button and select the edited file for `m01s03i227`
11. Click the "upload batch input file" button
12. Click on the link at the end of the sentence "To raise a ticket requesting that this branch be merged onto the project, please copy the text below and a link to this page to a new issue on our github page.", then copy and paste the text in the box underneath this sentence and add it to the new issue.

I think that was everything! @marqh please let me know if I missed anything.

**Comment by marqh** [comment]
I have made a replacement PR for this: i'll close this PR, to avoid any confusion.

Please continue the discussion about suitable information and ping me if there opinions on places where documentation updates would be valuable 

many thanks
mark

**Pull request closed without merging**
