### PR TITLE
[DOC] Whatsnew update (notebook repr entry)

### PR DESCRIPTION
**Pull request by dkillick**
Increase the resolution and adjust the cropping of the cube notebook repr image, and add a note that explicitly states that cube printing is not affected by this new functionality.

### CODE REVIEW

**Comment by pelson** [comment]
Thanks for the fantastic reviews @kaedonkers. Keep them coming! 👍

**Comment by pelson** [comment]
@dkillick - could you rebase against ``v2.1.x`` please? Also, happy for you to integrate the commit from #3056 as a cherry-pick too.

Also, a decision on whether you want to retro fit these to https://github.com/SciTools/scitools.org.uk/tree/master/iris/docs/v2.1 would be useful too.

👍

**Comment by pelson** [comment]
Just merged this (and #3056) onto v2.1.x. From d888eb6b I've added 648376161e111dfa0083bc034d78cc2759651705 and 64928421.

**Comment by pelson** [comment]
And tracked v2.1.x back to master with add8e471.

**Comment by dkillick** [comment]
Thanks @pelson 👍

**Pull request closed without merging**
