### PR TITLE
Removed all deprecation comments from _ff.py

### PR DESCRIPTION
**Pull request by LukeC92**

### CODE REVIEW

**Comment by LukeC92** [comment]
@dkillick would you be able to review the changes I've made please.

**Comment by dkillick** [comment]
@LukeC92 unfortunately you've picked up a failing doctest that is probably nothing to do with this PR, but we're going to have to wait until that's fixed until this can be merged 😒  I've recorded this failing doctest in #2837.

**Comment by pp-mo** [comment]
> @dkillick tests are failing

It's just the broken doctest, cf. #2837 
Good to go !

**Comment by pp-mo** [comment]
Nice + tidy.
Thanks @LukeC92 !

**Comment by dkillick** [comment]
@LukeC92 the failing doctest has now been resolved, so you'll need to rebase to pick up those changes.

**Pull request merged**
