### PR TITLE
iris image: crop and resize plus add favicons

### PR DESCRIPTION
**Pull request by bjlittle**
This PR crops the colourised `iris` images, and also converts the cropped images to `16x16` and `32x32` favicons.

### CODE REVIEW

**Comment by bjlittle** [comment]
Also need to update the [logo_banner.png](https://github.com/SciTools/iris/blob/master/docs/iris/src/_static/logo_banner.png), but I'll do that in a separate PR

**Comment by bjlittle** [comment]
@meganfitzsimons @kaedonkers @DPeterK Do you have the associated original `svg`? That would be handy :wink:

**Comment by pp-mo** [comment]
Ok 4 me.
Are we waiting on anything else to merge @bjlittle ?

**Comment by bjlittle** [comment]
@pp-mo This is good to go, as far as I'm concerned :+1:

**Comment by bjlittle** [comment]
Awesome, thanks @pp-mo 😁

**Pull request merged**
