### PR TITLE
Purge use of old _lazy_array functionality.

### LINKED ISSUE #2706: Remove usages of convert_nans_array, array_masked_to_nans and nans_array_type
`iris._lazy_data.convert_nans_array`, `iris._lazy_data.array_masked_to_nans` and `iris._lazy_data.nans_array_type` were removed in #2699 so we need to address the test fall out.

The bits that need removing are outlined in [this comment](https://github.com/SciTools/iris/pull/2699#issuecomment-319345179)

### PR DESCRIPTION
**Pull request by bjlittle**
Closes #2706

### CODE REVIEW

**Comment by lbdreyer** [comment]
If you say "Fixes #2706" somewhere in the PR description, I believe it automatically closes that issue when this PR get merged.
ALthough, maybe "closes #2706" works too?

**Comment by lbdreyer** [comment]
Looking good @bjlittle !

**Comment by bjlittle** [comment]
@lbdreyer See https://help.github.com/articles/closing-issues-using-keywords/

**Comment by bjlittle** [comment]
Although it may need to be in a comment rather than the description ...

**Pull request merged**
