### PR TITLE
Enable Travis' container based builds.

### PR DESCRIPTION
**Pull request by QuLogic**
Should start faster, and have better specs too. (See [here](http://docs.travis-ci.com/user/workers/container-based-infrastructure/).)

### CODE REVIEW

**Comment by QuLogic** [comment]
That looks to be about half the time for the defaults, and 2/3 overall. Not sure if that win will be consistent, but it does seem pretty nice.

**Comment by QuLogic** [comment]
Looks like those test failures are due to the Proj4 updates not yet getting to `master`.

**Comment by rhattersley** [comment]
Thanks @QuLogic :+1: 

Their docs state:
> The default behavior when no sudo usage is detected is to send Linux builds to this infrastructure.

But for whatever reason that doesn't seem to have been happening. :+1: for setting it explicitly!

**Comment by rhattersley** [comment]
> Looks like those test failures are due to the Proj4 updates not yet getting to master.

#1677 should take care of that.

**Comment by QuLogic** [comment]
Updated (and passing now).

**Pull request merged**
