### PR TITLE
Update version number on master

### PR DESCRIPTION
**Pull request by ajdawson**
Simply update the version number on master. Doesn't matter if it ends up being 2.0.0, this will do for now, the crucial thing is that v1.10.0 already left the building so the version number on master must be increased.

### CODE REVIEW

**Comment by ajdawson** [comment]
Ping @lbdreyer

**Comment by ajdawson** [comment]
(PR to merge changes from v1.10.x into master inbound once this is done.)

**Comment by lbdreyer** [comment]
I'm just going to let travis finish then I will merge this in (expecting to get the error we are getting in #1738, the fix of which isn't on master yet).

**Comment by lbdreyer** [comment]
Another unexpected error:
```
ERROR: test_all (iris.tests.test_analysis.TestRotatedPole)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/Iris-1.11.0.dev0-py2.7-linux-x86_64.egg/iris/tests/test_analysis.py", line 561, in test_all

    self._check_both_conversions(cube)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/Iris-1.11.0.dev0-py2.7-linux-x86_64.egg/iris/tests/test_analysis.py", line 546, in _check_both_conversions

    self.check_graphic()

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/Iris-1.11.0.dev0-py2.7-linux-x86_64.egg/iris/tests/__init__.py", line 696, in check_graphic

    figure.savefig(result_fname)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/matplotlib/figure.py", line 1421, in savefig

    self.canvas.print_figure(*args, **kwargs)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2220, in print_figure

    **kwargs)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 517, in print_png

    filename_or_obj, self.figure.dpi)

RuntimeError: Error building image
```

But I think that should be fixed in a different PR.

**Pull request merged**
