### PR TITLE
v2.2.x branch mergeback

### PR DESCRIPTION
**Pull request by lbdreyer**
There has been a fair amount of additions to the 2.2.x branch that should be merged back into master (especially since we just cut the 2.2.1 release).

To create this PR I did the following commands:

```$ git checkout upstream/v2.2.x -b 221_mergeback_rebase```
Then I did an interactive release to select the commits that were missing 
```$ git rebase -i --onto upstream/master HEAD~12```
Which were all the commits since `c3048cbf Fix for numpy 1v16. (#3257)` as this and `b0d5512b BLD: Pinning cftime to 1.0.1 (#3247)` were included in the last mergeback.

### CODE REVIEW

**Comment by lbdreyer** [comment]
This is currently failing as some of the license headers need updating.

I found it a bit strange that the license header checks passed when the PRs were made to the `v2.2.x` branch, but it turns out they weren't even running!
For example in #3310, the file's license header has the dates `2010 - 2015` and yet, in that PR the travis job claims to have passed as the [license header check is skipped](https://travis-ci.org/SciTools/iris/jobs/530288040#L4544)!
```
test_license_headers (iris.tests.test_coding_standards.TestLicenseHeaders) ... SKIP: Iris installation did not look like a git repo.
```


So the license header check is only done on the master branch? There may have been a fix to the master branch that deals with this...

I am going to fix the license headers on the v2.2.x branch then add that change to this PR

**Comment by lbdreyer** [comment]
I have updated this PR with the latest changed to the v2.2.x branch.

However, the tests are failing due to a missing import from sphinx. See #3322 for the fix.

Once the fix is in I will update this PR and hopefully get this PR in!

**Comment by bjlittle** [comment]
Talked through this with @lbdreyer, as the merge back is complicated due to cherry-picking from master to 2.2.x and vice versa - hence the sha changes on the merge back commits from 2.2.x to master.
Let's go with this LGTM

**Comment by bjlittle** [comment]
Awesome, thanks @lbdreyer :+1:

**Pull request merged**
