### PR TITLE
Added a what's new for #1942.

### PR DESCRIPTION
**Pull request by pelson**
Adds the final piece from #1942. Ping @philippjfr.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ah, sorry about that, just realized I'd already created a stub for this but never pushed it. Looks good though, thanks!

**Comment by pelson** [comment]
Apparently I got the format wrong. I'll push another one up in the morning.

```
UserWarning: Found contribution file(s) with unexpected names :
  /home/travis/build/SciTools/iris/docs/iris/src/whatsnew/contributions_1.10/newfeature_2016_Mar_02_axes_kwarg.txt
```

**Comment by pp-mo** [comment]
Does this fix it ?
[pelson#22](https://github.com/pelson/iris/pull/22)

**Comment by pp-mo** [comment]
Makes sense to me, anyway

**Pull request merged**
