### PR TITLE
test added to check validity of separability assessment

### PR DESCRIPTION
**Pull request by corinnebosley**
See https://exxconfigmgmt:6391/browse/EPM-1192 for context.
(Internal support request)

### CODE REVIEW

**Comment by ajdawson** [comment]
Could you put some details on this PR please, the link is internal MO only, and it is actually a bit tricky to guess what exactly the intent is.

**Comment by corinnebosley** [comment]
Well that's a pretty tricky thing to explain, you may have to give me a while to find the words...

**Comment by corinnebosley** [comment]
When Iris tries to merge cubes, it looks for the field to merge together (e.g. time) and tries to decide whether this is a function of another field or not.  If it is, it calls it separable, and if it is completely independent, it calls it inseparable.  These different assessments are thereupon treated differently.  
However, Iris only considers relationships in 2D space.  It has come to light that there may be some situations (such as that replicated by this test) in which the fields may appear to be separable when considered in 2D space, but in 3D space they are actually functionally related, making the assessment of separability inaccurate, and the treatment thereafter erroneous.  

This is an edge case, but it can and has caused merging errors.

**Comment by corinnebosley** [comment]
@pelson I'm keeping this one open, sounds like it might be valuable.

**Comment by pelson** [comment]
Just checking, does the error look like the following?

```
import iris.cube
import numpy as np


coord_vals = [(0, 30, 100),
              (0, 40, 100),
              (0, 40, 110),
              (1, 30, 110),
              (1, 30, 100),
              (1, 40, 110)]

test_raw = iris.cube.CubeList([])

for r, t, frt in coord_vals:
    r, t, frt = np.array(r), np.array(t), np.array(frt)
    cube = iris.cube.Cube(np.array([0]))
    cube.add_aux_coord(iris.coords.DimCoord(r, long_name='a'), [])
    cube.add_aux_coord(iris.coords.DimCoord(t, long_name='b'), [])
    cube.add_aux_coord(iris.coords.DimCoord(frt, long_name='c'), [])
    test_raw.append(cube)

print(test_raw.merge())

```


```
    print(test_raw.merge())
  File "/data/local/itpe/miniconda/envs/iris_py3/lib/python3.6/site-packages/iris/cube.py", line 468, in merge
    merged_cubes.extend(proto_cube.merge(unique=unique))
  File "/data/local/itpe/miniconda/envs/iris_py3/lib/python3.6/site-packages/iris/_merge.py", line 1215, in merge
    merged_data = biggus.ArrayStack(stack)
  File "/data/local/itpe/miniconda/envs/iris_py3/lib/python3.6/site-packages/biggus/_init.py", line 1733, in __init__
    raise ValueError('sub-array must be subclass of Array')
ValueError: sub-array must be subclass of Array
```

**Pull request closed without merging**
