### PR TITLE
Nearest-neighbour regrid circular tests.

### PR DESCRIPTION
**Pull request by bjlittle**
This PR extends the regrid circular unit tests for nearest-neighbour coverage.

### CODE REVIEW

**Comment by bjlittle** [comment]
@rhattersley The last one ... honest (for now)

**Comment by rhattersley** [comment]
Makes sense to me. :+1:

**Comment by bjlittle** [comment]
@rhattersley go then, merge away! I dare you ... :smiling_imp:

**Comment by rhattersley** [comment]
All right then - I will! So there!

**Comment by rhattersley** [comment]
Out of interest, have you started trying to port any of the other experimental algorithms?

**Comment by bjlittle** [comment]
The next up is the area weighted ... I'm keen to do it sooner rather than later since me head is in this space!

**Pull request merged**
