### PR TITLE
Fix #1339 (Win64 np.int64 slices)

### LINKED ISSUE #1339: single cube slice not working on Windows 64bit
I get an error when I try to slice a cube with a single value.  

I found that if I change https://github.com/SciTools/iris/blob/master/lib/iris/_constraints.py#L367 
from:
result[dim] = where_true[0]  
to
result[dim] = int(where_true[0])
then everything starts working.

without this change where_true[0] resolves to a numpy.int64 which must get caught is some type check latter on.

Thanks,
Colin

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR should fix #1339 and #1568.

### CODE REVIEW

**Comment by pelson** [comment]
:+1: - we should really backport this to v1.7.x. @rhattersley - thoughts?

**Comment by rhattersley** [comment]
Nice and simple - thanks. :+1: 

I've sent you a quick test: https://github.com/ocefpaf/iris/pull/2

**Comment by rhattersley** [comment]
@pelson - tests? This isn't cartopy ... :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
@pelson was way to quick for me to add @rhattersley tests PR :smile_cat:

**Comment by rhattersley** [comment]
> we should really backport this to v1.7.x

Or just release 1.8?

**Comment by rhattersley** [comment]
> > we should really backport this to v1.7.x
> 
> Or just release 1.8?

On second thoughts, yes ... backport to 1.7.

**Pull request merged**
