### PR TITLE
Support more data representation templates.

### PR DESCRIPTION
**Pull request by ajdawson**
The new GRIB loader currently only supports data representation section template number 0, which represents grid-point simple packing ('grid_simple' in GRIB API terminology). However, iris doesn't really do anything with this information, there is no translation process associated with it as we don't handle the unpacking, GRIB API does that for us. This PR allows iris to load any GRIB2 messages with grid-point or spectral packing supported by GRIB API:

* 0 (grid_simple)
* 1 (grid_simple_matrix, grid_simple_matrix_bitmap)
* 2 (grid_complex)
* 3 (grid_complex_spatial_differencing)
* 4 (grid_ieee)
* 40 (grid_jpeg)
* 41 (grid_png)
* 50 (spectral_simple)
* 51 (spectral complex)
* 61 (grid_simple_log_preprocessing)

Some discussion of the nature of this change and why it is considered suitable for v1.8.x is contained in #1626. This PR replaces #1626.

References:
* http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_table5-0.shtml,
* https://software.ecmwf.int/wiki/display/GRIB/Grib+API+keys

### CODE REVIEW

**Comment by ajdawson** [comment]
Ping @marqh. This version targets v1.8.x and adds support for both spectral_simple and spectral_complex packing types (50 and 51).

**Comment by marqh** [comment]
as I have already said, I think this is a problem with our newly delivered GRIB load solution and should be treated as a bug fix so I support this being added to the 1.8.1 milestone.

@bjlittle please may we have a 2nd opinion?

**Comment by marqh** [comment]
@ajdawson travis shenangians abounding today

please may you restart your test and see if it all justWorks(tm)?
ta

**Comment by ajdawson** [comment]
Looks to be to do with other issues, in particular the ones fixed by cf1bc4b and d6f21f5. I've gone for a rebase instead of restarting the tests.

**Comment by marqh** [comment]
I hope that the .npy file does not suffer from the same issue as .npz files:
https://github.com/SciTools/iris/issues/1590

Is it just a simple array definition in a file?

Other than this concern, the tests look fine to me.

**Comment by marqh** [comment]
Please could we add some documentation to the
```
data_representation_section(section):
```
function, detailing that the various data representation template details are handled by the GRIB API and so do not require specific handling within the Iris `_load_convert` module.

**Comment by marqh** [comment]
I've raised a PR
https://github.com/ajdawson/iris/pull/3
adding to the docstring as I described

I would like this to make the cut for 1.8.1, which is imminent, please may you consider if my PR can be added so I can get this PR merged?

thank you

**Comment by ajdawson** [comment]
@marqh - I've been away for 3 weeks, this branch is now updated with your updated docstring.

**Comment by marqh** [comment]
excellent, thank you @ajdawson 

This is looking good to go to me now.  Please may this PR be merged (or tell us a reason not to do so), so that this can make the 1.8.1 release?

thank you 
marqh

**Comment by bjlittle** [comment]
@ajdawson Great, thanks! :+1:

**Pull request merged**
