### PR TITLE
Fixed unicode issue for generate_std_names.

### LINKED ISSUE #1876: v1.9.0 doesn't build std_names (encoding exception)
```
bin/python tools/generate_std_names.py etc/cf-standard-name-table.xml build/lib/iris/std_names.py
Traceback (most recent call last):
  File "tools/generate_std_names.py", line 128, in <module>
    to_dict(args.input, args.output)
  File "tools/generate_std_names.py", line 102, in to_dict
    tree = ET.parse(infile)
  File "lib/python3.5/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "lib/python3.5/xml/etree/ElementTree.py", line 594, in parse
    self._root = parser._parse_whole(source)
  File "lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1162: ordinal not in range(128)
error: command 'bin/python' failed with exit status 1

```

Fix incoming.

### PR DESCRIPTION
**Pull request by pelson**
Closes #1876. This is a re-opening of #1877.

### CODE REVIEW

**Comment by pelson** [comment]
Failing on py2k with:

```
0.62s$ python setup.py --quiet --with-unpack build

Traceback (most recent call last):

  File "tools/generate_std_names.py", line 132, in <module>

    to_dict(in_fh, out_fh)

  File "tools/generate_std_names.py", line 106, in to_dict

    tree = ET.parse(infile)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse

    tree.parse(source, parser)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse

    parser.feed(data)

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed

    self._parser.Parse(data, 0)

UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 9350: ordinal not in range(128)

error: command '/home/travis/miniconda/envs/test-environment/bin/python' failed with exit status 1
```

**Comment by pelson** [comment]
:tada:  @marqh

**Comment by marqh** [comment]
this looks like the  bug which is stopping 
https://github.com/SciTools/conda-recipes-scitools/pull/140
from working

this likely means we'll need to cut a v1.9.1 in order to build effectively across platforms and versions :(

**Comment by ajdawson** [comment]
> this likely means we'll need to cut a v1.9.1 in order to build effectively across platforms and versions :(

Don't be sad @marqh! This is not necessarily such a bad thing. Perhaps it suggests that the packaging mechanism should be sprung into action for release candidates as well as final versions, though I have no idea how complex that would be to implement...

**Comment by pelson** [comment]
> Perhaps it suggests that the packaging mechanism should be sprung into action for release candidates as well as final versions, though I have no idea how complex that would be to implement...

Agree. We can test it easily by putting a PR against ``conda-recipes-scitools`` which updates Iris to use the master/another branch as the source.

**Pull request merged**
