### PR TITLE
Added implied height for stash code visibility in air (m01s03i281)

### PR DESCRIPTION
**Pull request by gm-s**
This change to iris.fileformats.pp_rules sets an implied height of 1.5m as a scalar co-ordinate for stash code 3281 - 'Visibility at Screen Height'.

This relates to https://github.com/metarelate/metOcean/issues/44, as the CF name map for this stash code is not explicit as to height, and the imported data does not include a height co-ordinate as standard. This will allow the imported cube to be self-defined as it will include an appropriate CF-name, Unit and all appropriate co-ordinates.

### CODE REVIEW

**Comment by rhattersley** [comment]
Thanks @gm-s - looks good. The only tweak needed is to update the copyright period in the pp_rules module.

**Comment by rhattersley** [comment]
> The only tweak needed is to update the copyright period in the pp_rules module.

i.e. It needs to read: `2013 - 2015`

**Comment by gm-s** [comment]
Thanks Richard, I've added 0e21465.

**Comment by rhattersley** [comment]
:+1:

**Pull request merged**
