### PR TITLE
Docs: Enable spell check

### PR DESCRIPTION
**Pull request by tkknight**
### Description

**---- WORK IN IN PROGRESS - DO NOT NOT REVIEW ----**

Enable the spell check that was primed in #3779.

Summary of changes:

- travis linkcheck renamed to checkdocs that will run `make linkcheck spelling`, instead of just `make linkcheck`
- ensured any **warnings** are raised to **errors**
- enabled extension in `conf.py`
- updated documented to include `make spelling`
- added pip dependency `sphinxcontrib-spelling`
- **TODO** updated file containing **allowed** words

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by bjlittle** [comment]
@tkknight Let's see if we can squeeze this in....

**Comment by bjlittle** [comment]
@tkknight This would be lovely to have, but there seems to be some dependency issues :thinking: 

Thanks for all you're efforts on this, much appreciated, but we're going to leaving this until `iris` 3.1, hope you don't mind?

**Comment by tkknight** [comment]
The spelling dependency only shows itself when running on travis which is somewhat odd.

```
make[1]: Entering directory '/home/travis/build/tkknight/iris/docs/iris/src'
sphinx-build -b spelling -W --keep-going . _build
Running Sphinx v3.2.1
[conf.py] Iris Version = 3.0
[conf.py] Iris Release = 3.0.dev0
pyenchant:: looking in system
pyenchant:: with name enchant-2
pyenchant:: with name libenchant-2
pyenchant:: with name enchant
pyenchant:: with name libenchant
pyenchant:: with name enchant-1
pyenchant:: with name libenchant-1
pyenchant:: looking in system
pyenchant:: with name enchant-2
pyenchant:: with name libenchant-2
pyenchant:: with name enchant
pyenchant:: with name libenchant
pyenchant:: with name enchant-1
pyenchant:: with name libenchant-1
pyenchant:: looking in system
pyenchant:: with name enchant-2
pyenchant:: with name libenchant-2
pyenchant:: with name enchant
pyenchant:: with name libenchant
pyenchant:: with name enchant-1
pyenchant:: with name libenchant-1
Extension error:
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
)
Makefile:55: recipe for target 'spelling' failed
```

**Comment by tkknight** [comment]
I am reviewing the state of this.  The issue remains in that conda needs an underlying library (enchant) available on the system else it will fail (as does pip).  If you have sudo permissions on Linux you can use the commands followed by a conda or pip install of `sphinxcontrib-spelling`:

```
sudo apt-get update -y
sudo apt-get update -y enchant
```

The above commands worked fine on WSL ubunutu 18.04.  Adding this `sphinxcontrib-spelling` dependency works fine on RHEL7 too, however when used on **travis-ci** (deprecated for this project) or **cirrus-ci** the enchant dependency is not present and cannot seem to be installed.

An alternative approach will to not include the spelling check as part of the CI tests, but only to run them manually locally (`make spelling`).  

Please let me know if anyone has other suggestions before I action the alternative approach.

**Comment by bjlittle** [comment]
@tkknight Okay, after a bit of investigation I've got an easy way forward for this so that it works on `cirrus-ci` :+1: 

We can iterate on this and finally get it across the line.

Let me focus on the `3.0.2` release, then come back to bank this in `master`... does that sound like an acceptable plan?

**Comment by bjlittle** [comment]
@tkknight Do you fancy rebasing, then I'll push a PR on your branch with some changes to address this 👍

**Comment by tkknight** [comment]
> @tkknight Do you fancy rebasing, then I'll push a PR on your branch with some changes to address this 👍

Rebased.  Ping me if you need any help testing you changes.

**Comment by tkknight** [comment]
Moving to GitHub actions for the documentation CI may resolve this.

**Comment by bjlittle** [comment]
@tkknight Ping... did you want to rebase this PR? Are we still commited to supporting this feature?

Now that we're using GHA, the new platform my play into our favour here.

**Comment by tkknight** [comment]
> @tkknight Ping... did you want to rebase this PR? Are we still commited to supporting this feature?
> 
> Now that we're using GHA, the new platform my play into our favour here.

I will rebase this PR soonish, there is no rush.

**Comment by tkknight** [comment]
I'm closing this PR now.l  The packages to enable this functionality are patchy at best with dependencies having to be manually installed and then may still not work.  Lets move on!

**Pull request closed without merging**
