### PR TITLE
Used concrete sized in shape for PP data proxy.

### PR DESCRIPTION
**Pull request by pelson**
Fixes the first problem in https://github.com/SciTools/biggus/issues/135.

### CODE REVIEW

**Comment by rhattersley** [comment]
Thanks @pelson :+1:

**Comment by rhattersley** [comment]
I'll let travis do it's thing and merge once it confirms that specific issue has gone away.

**Comment by rhattersley** [comment]
`The file header at lib/iris/tests/unit/fileformats/pp/test__create_field_data.py is out of date.` :unamused:

**Comment by pelson** [comment]
All gravy...

**Comment by pelson** [comment]
> All gravy...

Except when it isn't. I've restarted the travis build.

**Comment by bjlittle** [comment]
I like your gravy optimism though ...

**Comment by bjlittle** [comment]
Boom! Thanks @pelson !

**Pull request merged**
