### PR TITLE
WIP: ENH: Allow climatology attribute

### LINKED ISSUE #2904: Support for climatologies
Support for climatologies has a few hurdles:

- Cell method information is being discarded on load (e.g. time: mean within years time: mean over years) - #1438
- Climatology bounds coords are not supported either, not even manually as the attribute is prohibited:

```Python
>>> cube.coord('time').attributes['climatology'] = 'climatology_bnds'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/atk/_dev/environments/latest/lib/python2.7/site-packages/iris/_cube_coord_common.py", line 65, in __setitem__
    raise ValueError('%r is not a permitted attribute' % key)
ValueError: 'climatology' is not a permitted attribute
```

### PR DESCRIPTION
**Pull request by cpelley**
On the same mindset as #2098
Closes #2904 

**NOT FOR MERGING**

### CODE REVIEW

**Comment by cpelley** [comment]
- The cell methods appear to be fine.
- Looks like removing 'climatology' from the allowed set of attributes does what is wanted on save, but breaks things on load :(

```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h05/cpelley/git/iris/lib/iris/__init__.py", line 373, in load_cube
    cubes = _load_collection(uris, constraints, callback)
  File "/home/h05/cpelley/git/iris/lib/iris/__init__.py", line 313, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/home/h05/cpelley/git/iris/lib/iris/cube.py", line 143, in from_cubes
    for cube in cubes:
  File "/home/h05/cpelley/git/iris/lib/iris/__init__.py", line 300, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/home/h05/cpelley/git/iris/lib/iris/io/__init__.py", line 211, in load_files
    for cube in handling_format_spec.handler(fnames, callback):
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/netcdf.py", line 698, in load_cubes
    cube = _load_cube(engine, cf, cf_var, filename)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/netcdf.py", line 526, in _load_cube
    engine.activate(_PYKE_RULE_BASE)
  File "/data/users/cpelley/miniconda2/envs/ants_6oct/lib/python2.7/site-packages/pyke/knowledge_engine.py", line 296, in activate
    for rb_name in rb_names: self.get_rb(rb_name).activate()
  File "/data/users/cpelley/miniconda2/envs/ants_6oct/lib/python2.7/site-packages/pyke/rule_base.py", line 159, in activate
    self.run_fc_rules(current_rb)
  File "/data/users/cpelley/miniconda2/envs/ants_6oct/lib/python2.7/site-packages/pyke/rule_base.py", line 147, in run_fc_rules
    for fc_rule in rb.fc_rules: fc_rule.run()
  File "/data/users/cpelley/miniconda2/envs/ants_6oct/lib/python2.7/site-packages/pyke/fc_rule.py", line 90, in run
    self.rule_fn(self)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py", line 848, in fc_build_coordinate_time
    build_dimension_coordinate(engine, cf_coord_var)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py", line 1916, in build_dimension_coordinate
    cf_coord_var)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py", line 1891, in reorder_bounds_data
    len(vertex_dim_names)))
ValueError: Too many dimension names differ between coordinate variable 'time' and the bounds variable 'climatology_bounds'. Expected 1, got 0.
```

**Comment by cpelley** [comment]
Recreate the above exception using this branch by simply calling something like:

```Python
from datetime import datetime
import iris
import iris.tests.stock as stock


def add_climatology_bounds(cube, year_range):                                  
    time_coord = cube.coord('time')                                            
    bounds = time_coord.units.date2num([datetime(year_range[0], 1, 1),         
                                        datetime(year_range[1], 1, 1)])        
    points = sum(bounds) / 2.                                                  
    climatology_bounds = iris.coords.AuxCoord(                                 
        points, long_name='climatology_bounds', bounds=bounds,                 
        units=time_coord.units)                                                
    cube.add_aux_coord(climatology_bounds, None)                               
                                   
    time_coord.attributes['climatology'] = climatology_bounds.name()                              
    cube.add_cell_method(iris.coords.CellMethod(                               
        'time: mean within years time: mean over years'))


cube = iris.tests.stock.realistic_3d()
add_climatology_bounds(cube, [1950, 2030])
iris.save(cube, 'tmp.nc')
new_cube = iris.load_cube('tmp.nc')
```

**Comment by pelson** [comment]
Thanks @cpelley. Not reviewed this, but just wanted to say that we are closing off enhancements into v2.0.0, so this will have to wait for the next minor release.

Thanks,

**Comment by cpelley** [comment]
Sure thanks @pelson

**Comment by corinnebosley** [comment]
Hi @cpelley, would you be kind enough to rebase this please? We're gearing up for a release so it's be nice to see if this is worth squeezing in.

**Comment by cpelley** [comment]
Hi @corinnebosley, thanks for prodding this.  Apologies but I don't have the availability to kick this into touch within a day.  Can I suggest we pick this up post release of iris?

**Comment by cpelley** [comment]
Hi @corinnebosley, before I work this one back into touch, would you be able to indicate whether there is appetite in having this capability in iris?

**Comment by bjlittle** [comment]
@cpelley A **very** belated thanks for this PR. However, it's gone rather stale, indeed very stale.

That said, I understand the intent of this PR but it doesn't cover end-to-end support within `iris` for `climatology`. I'm keen that the next minor release of `iris` fully supports [climatological statistics](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#climatological-statistics), so I'm going to close this PR, then open an issue that references this PR, but also requires to be addressed for `iris` release `2.3.0`.

**Pull request closed without merging**
