### PR TITLE
Votable Issues

### PR DESCRIPTION
**Pull request by tkknight**
### Description
Adding a page to the documentation to show a list of all issues that have ~~the label [Feature: Votable](https://github.com/SciTools/iris/labels/Feature%3A%20Votable)~~ been voted for irrespective on the labels on the issue.

- Uses [datatables ](https://datatables.net/) to allow for sorting/pagination
- To avoid keeping a list of the issues in the Iris repo a json file is maintained daily (can be run manually also) from a separate repo.  This was done to avoid having Iris PRs having to deal with the json file being updated and possible merge conflicts.  See https://github.com/SciTools/voted_issues for the GitHub Action and further info.

You can view a built copy of the docs with this [new page here](https://tkknight-iris-test-doc.readthedocs.io/en/latest/voted_issues.html) 👍

Once merged I also plan to add an Iris pinned and locked issue that will look like [this one](https://github.com/tkknight/votable_issues_old/issues/1) (in a temp repo)

#### Consideration
- GitHub Actions will [only notify the last person ](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs) who edits the action, ideally it should be to @SciTools/iris-devs.  The action could email someone but I cannot fund a way to send a notification to the github group yet.  Any ideas welcome!

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Review by rcomer — COMMENTED** [review]
I can't comment on the implementation, but the end result looks nice to me!  Just one minor suggestion inline.

Also, on the proposed pinned issue, there is a suggestion to tag `@SciTools/iris-devs`.  We have this in the stale action's comments too, but I'm not sure general users actually can.  E.g. see https://github.com/SciTools/iris/issues/3820#issuecomment-1046907495, which is the only attempt I've seen so far.

Is it worth encouraging users to subscribe (as well as vote) for the issues they're interested in?  Then they will be notified of any updates (including if the issue goes stale).

**Comment by tkknight** [comment]
> I can't comment on the implementation, but the end result looks nice to me! Just one minor suggestion inline.
> 
> Also, on the proposed pinned issue, there is a suggestion to tag `@SciTools/iris-devs`. We have this in the stale action's comments too, but I'm not sure general users actually can. E.g. see [#3820 (comment)](https://github.com/SciTools/iris/issues/3820#issuecomment-1046907495), which is the only attempt I've seen so far.
> 
> Is it worth encouraging users to subscribe (as well as vote) for the issues they're interested in? Then they will be notified of any updates (including if the issue goes stale).

I have updated the draft pinned issue and the docs to suggest ensuring they are subscribed to the issue.

I will chat with @bjlittle to confirm how the mentions works as we think they do.

**Comment by fox-8** [comment]
@SciTools/iris-devs This looks great, and will be super useful for the community

**Comment by bjlittle** [comment]
@rcomer As far as I'm aware you need to be a member of an organisation to `@mention` a team... so in that regard, non-core users mentioning `@SciTools/iris-devs` in a comment won't generate a notification as intended. See [GH About Teams](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams).

So we'll need to address that here and also assumptions that we've made for the `stale` GHA.

**Comment by zklaus** [comment]
@rcomer, @bjlittle, conda-forge offers this via a bot command, see [here](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-conda-forge-team).

**Comment by tkknight** [comment]
I have updated the PR.  After some discussion and initial agreement the changes are:

- Ignore the `Feature: Votable` label, any 👍 on an issue header counts as a vote. I plan to remove this label once this PR is merged.
- The [docs page ](https://tkknight-iris-test-doc.readthedocs.io/en/latest/voted_issues.html)now has a larger list of issues, note that it excludes issues with zero votes.
- Rename `Votable Issues` to be `Voted Issues`
- Updated the [to be pinned issue](https://github.com/tkknight/votable_issues_old/issues/1) that reflects the changes as detailed here.

The GitHub mentions issue is now bypassed but is still a consideration for the stale GitHub action.  I will create another issue to capture this.

Ready for review again!

**Comment by rcomer** [comment]
I like this.  Simple is Good 👍

**Review by bjlittle — APPROVED** [review]
@tkknight Love it, love it, love it! :heart_eyes: 

Thanks, for being so patient and going the extra mile to get this across the line :beers:

**Comment by bjlittle** [comment]
@tkknight It's alive, see https://scitools-iris.readthedocs.io/en/latest/voted_issues.html :partying_face:

**Comment by bjlittle** [comment]
Note that https://github.com/SciTools/iris/issues/4133 assumes that non-core members can use the `@SciTools/iris-devs` GH team mention as a means to get our attention... which is also flawed.

I'll wrap this all up in a separate issue, as we need an agreed approach to go about this for several different use cases.

**Comment by tkknight** [comment]
> @tkknight Did you want to make a **pinned** issue on iris now advertising the voting system for the community?

Pinned issue created, all should see it when browsing issues, https://github.com/SciTools/iris/issues

**Comment by rcomer** [comment]
> Pinned issue created

Will this also be advertised on the various social media?  E.g. Twitter, MO Yammer.

**Comment by tkknight** [comment]
I will look to compose a MO Yammer post for next week sometime.  The MO VATools group will be informed too.  

I would like to wait a few days to see if any issues arise on the GitHub action or any user feedback first.

**Pull request merged**
