### PR TITLE
added radians test to cartopgraphy

### PR DESCRIPTION
**Pull request by ckmo**
This PR checks the coordinate units before attempting the conversion to radians. I've not added tests as I'm unsure.

### CODE REVIEW

**Comment by ajdawson** [comment]
This is looking good now @ckmo. Before merging I'd appreciate if you could squash the 7 commits in the PR into one. There is some documentation covering this in the developer guide: http://scitools.org.uk/iris/docs/latest/developers_guide/gitwash/development_workflow.html#rewriting-commit-history. If you need help please feel free to ask.

**Comment by ckmo** [comment]
Hi, I think I've updated it correctly but let me know if anything's missing! Cheers!

**Comment by esc24** [comment]
@ckmo - looks like your squash has gone awry. Can I help in any way?

**Comment by esc24** [comment]
Thanks to @ajdawson for all of his help and to @ckmo for persevering.

**Pull request merged**
