### PR TITLE
Test result changes for newer gdal (1.10 to 2.0).

### PR DESCRIPTION
**Pull request by pp-mo**
This fixes a couple of gdal-related tests (of iris.experimental.raster) that currently fail if matplotlib is "unpinned".
The changes amount to updating the tests to work with gdal 2.0.

The history is odd:
 * sometime between our v1.9.0 and v1.9.1 tags, we started installing gdal 2.0 (previously 1.10)
   * presumably dues to channels changes, as there are no changes in ".travis.yml" or "conda-requirements.txt"
   * however, this new gdal install has not functioned since then, for some reason 
   * import of gdal, or osgeo, fails due to a missing library
   * since then, gdal-related tests have been **all automatically skipped** (via "@skip_gdal")
   * that remains the case up to 1.10, and the current master
 * if I "unpin" matplotlib, this affects other dependencies, and somehow the gdal 2.0 install "starts working".
   * a couple of tests then produce different answers, and fail
     * the changes are apparently due to the upgrade to gdal 2.0
     * the older v1.9.0 produces the same results (errors) when run in the same environment
     * no code has been changed in iris.experimental.raster since v1.9.0

**NOTE**: As the gdal install is currently broken, you can't see these changes working until we upgrade the environment (by unpinning matplotlib?)

### CODE REVIEW

**Comment by pelson** [comment]
I guess we need to xref this with #1898. Any chance we can be less dependent upon the GDAL version?

Which numbers are *correct*? If they aren't important, maybe we shouldn't be including them in the test at all?

**Comment by pp-mo** [comment]
> @pelson I guess we need to xref this with #1898

Dead right.  It would have avoided this debt.
I thought we already had something in place for that, but I see not ...

**Comment by pp-mo** [comment]
> Any chance we can be less dependent upon the GDAL version?
> Which numbers are correct? 
> If they aren't important, maybe we shouldn't be including them in the test at all?

This is tricky...
There are two instances.
*[change to TestProjection.test_ellipsoid](https://github.com/SciTools/iris/pull/2160/files#diff-5c80f81b9e029672203f16c037fa90ac)*
Has only a small floating-point shift, but the tested result is encoded as a string, which makes it awkward.
We could use a regexp.  Proposal follows...

*[change to SMALL_total_column_co2.nc.ma.tif_header.txt, for TestGeoTiffExport.test_masked](https://github.com/SciTools/iris/pull/2160/files#diff-d9f31edd7f61f610272aa81ed5bfa0ee)*
I have no idea what those detail changes in the TIFF header mean.
At least they are integer types, so the change is probably stable.
The MDI type change looks like a policy change or even a bugfix.
I think I'd leave this one.

**Comment by marqh** [comment]
grand, thank you @pp-mo

**Pull request merged**
