### PR TITLE
Made use of biggus in iris._concatenate

### PR DESCRIPTION
**Pull request by pelson**
Concatenate now supports deferred data (and a mixture of loaded and unloaded data).

### CODE REVIEW

**Comment by cpelley** [comment]
This would be a great addition to iris for us, since it would allow us to combine domain decomposed pieces back together so that we can write a single grid to a file.  Currently we have been dropping down to the NetCDF python library to manually write these pieces into a combined grid.

**Comment by pelson** [comment]
@cpelley - I've rebased this, and hope it might be mergeable today :wink:

**Comment by bjlittle** [comment]
@pelson Touch the licence header year and I'll merge this in a heart beat ...

**Comment by pelson** [comment]
That should do the trick. Thanks @bjlittle.

**Comment by bjlittle** [comment]
Such a simple PR, but with a massive impact. Beautiful! Thanks @pelson :+1:

**Comment by bjlittle** [comment]
@cpelley Life just go simpler for you thanks to @pelson :smile:

**Comment by rhattersley** [comment]
Nice one! :grin:

**Comment by cpelley** [comment]
> @cpelley Life just go simpler for you thanks to @pelson :smile:

THANKS @pelson, I was literaly about to look into revisiting this.
Very much appreciate the addition.  Yet again overwhelmed by Biggus and how it has next to no impact on iris.  Fantastic!

**Pull request merged**
