### PR TITLE
Updated CF saver version in User Guide and docstring

### PR DESCRIPTION
**Pull request by jonseddon**
### Description
The User Guide and `iris.fileformats.netcdf.save()` docstring have been updated with the correct version of the CF version that netCDF files are saved with.

### CODE REVIEW

**Comment by jonseddon** [comment]
I'm unsure what release this change will go into. If 3.0 should I add a new whatsnew entry to the 3.0 release notes, or will it be 3.1 and so a `latest.rst` entry is preferred instead?

**Comment by jonseddon** [comment]
It's probably worth checking and closing #3926 before this PR's merged.

**Comment by lbdreyer** [comment]
Nice catch! Thanks @jonseddon !

The Iris 3 release is not out yet (still on the release candidate) so we should be able to slip it in with the Iris 3. To do so, could you edit your PR to target the `v3.0.x` branch, rather than master?

As for the what's new, the easiest option would be to edit the [3.0.rst](https://github.com/SciTools/iris/blob/v3.0.x/docs/iris/src/whatsnew/3.0.rst)

**Comment by jonseddon** [comment]
Resolves #3926

**Comment by jonseddon** [comment]
I've added a What's New but I can't manage to install xxhash successfully to test that the documentation builds (particularly the links in the What's New) :-(

**Comment by jonseddon** [comment]
I've defeated Conda and the documentation is building successfully locally and looks good.

The failing Travis tests are identical to those in #3923 and are due to the new cftime.

**Comment by lbdreyer** [comment]
Thanks @jonseddon !

**Pull request merged**
