### PR TITLE
Added basic support for climatology cell methods

### PR DESCRIPTION
**Pull request by esc24**
This PR addresses #1438 allowing loading of CF-netCDF files with rich cell methods like `time: mean within years time: mean over years` that express climatologies. I've not enhance the `CellMethod` to give atomic access to the components of the multi word method, but I still check the first part of the method is a known. I'm not good at regular expressions so any advice is welcomed.

### CODE REVIEW

**Comment by esc24** [comment]
@rockdoc - have you had time to test this on your data?

**Comment by esc24** [comment]
Anyone brave enough to take a look at some regex?

**Comment by esc24** [comment]
@rhattersley - I've tracked down why the unit tests in `lib/iris/test/unit/filesformats/pyke_rules/compiled_krb` weren't being run on travis. It's because we have code in `setup.py` to exclude the `lib/iris/fileformats/_pyke_rule/compiled_krb` directory during the build. The same logic was catching the corresponding test directory with the same name. I've added a commit to fix this.

**Comment by rockdoc** [comment]
@esc24 
> have you had time to test this on your data?

I've just had a quick shot at loading and saving a cube from one of my netcdf files containing climatological variables. The `cell_methods` attribute appears to carry over to the new file with the correct value which, if I understand correctly, was the main goal of this PR. Which is good.

However, the original CF-compliant climatology metadata seems to get lost in translation, as illustrated in the snippets of `ncdump` listings below. Specifically, the `time:climatology` attribute and the associated `climatology_bnds` variable have disappeared, and been replaced with `time:bounds` attribute and a `time_bnds` variable. It would be extremely useful if the original climatology information could be carried over from source file to destination file.

```
Original file:

variables:
    float biomass_burning_fresh(time, model_level_number, lat, lon) ;
        biomass_burning_fresh:long_name = "Biomass-burning (Fresh)" ;
        biomass_burning_fresh:units = "kg kg-1" ;
        biomass_burning_fresh:um_stash_source = "m01s00i352" ;
        biomass_burning_fresh:cell_methods = "time: mean within years time: mean over years" ;
        ...
    double time(time) ;
        time:units = "hours since 1970-01-01 00:00:00" ;
        time:standard_name = "time" ;
        time:calendar = "360_day" ;
        time:climatology = "climatology_bnds" ;
    double climatology_bnds(time, bnds) ;

Output file generated by iris.save():

variables:
    float biomass_burning_fresh(time, model_level_number, lat, lon) ;
        biomass_burning_fresh:long_name = "Biomass-burning (Fresh)" ;
        biomass_burning_fresh:units = "kg kg-1" ;
        biomass_burning_fresh:um_stash_source = "m01s00i352" ;
        biomass_burning_fresh:cell_methods = "time: mean within years time: mean over years" ;
        ...
    double time(time) ;
        time:bounds = "time_bnds" ;
        time:units = "hours since 1970-01-01 00:00:00" ;
        time:standard_name = "time" ;
        time:calendar = "360_day" ;
    double time_bnds(time, bnds) ;
```

**Comment by esc24** [comment]
Anyone care to look at this? I'd like to get it merged. I appreciate the point made by @rockdoc that we should improve the handling of climatologies when saving to CF-netCDF, but as he points out this would be in addition to this change.

**Comment by marqh** [comment]
I have been throughthis and I support the logic;  I think it handles the cases we expect to see in NetCDF files 

this looks good to merge to me

**Comment by esc24** [comment]
I'd love to see this in 1.8

**Pull request merged**
