### PR TITLE
Use https for opendap.org link, as http no longer supported.

### PR DESCRIPTION
**Pull request by pp-mo**
Should fix #5619 CI linkcheck failure

### CODE REVIEW

**Comment by pp-mo** [comment]
Hang on, now failed elsewhere, on the twitter link.
But I think that may be a one-off
Trying a re-spin ...

**Comment by bjlittle** [comment]
> Hang on, now failed elsewhere, on the twitter link. But I think that may be a one-off Trying a re-spin ...

@pp-mo I've been respinning various `iris` PR with this failure ... I'm tempted to suggest that you add the twitter link to the `conf.py` to ignore as part of the linkcheck

**Review by bjlittle — CHANGES_REQUESTED** [review]
Add the twitter link to the list of exceptions in the `docs/src/conf.py` as it's giving us serious issues atm

**Comment by bjlittle** [comment]
@pp-mo Have you rebased from `main` after #5621 landed?

**Comment by pp-mo** [comment]
> @pp-mo Have you rebased from `main` after #5621 landed?

No, this PR is not independent as it targets auto-update-lockfiles

**Review by bjlittle — APPROVED** [review]

**Comment by pp-mo** [comment]
Ok these 2 changes do seems to work around the problem.
@bjlittle is it good to merge this + #5619 
or, given your comments above about "rebased from main after https://github.com/SciTools/iris/pull/5621 landed", is it better to launch a fresh PR, based on a more recent main ?

**Pull request merged**
