### PR TITLE
Regrid integration tests.

### PR DESCRIPTION
**Pull request by bjlittle**
This PR is trivial but may need some thought from other core devs ...

It's the last regridding test shuffle/house-keeping PR. The goal was to redistribute the whole contents of `tests/analysis/test_regrid.py` to more active and appropriate areas of the testing framework.

I'm managed to collate most of the tests from `test_regrid.py` into `tests/unit/analysis/regrid/test_RectilinearRegridder.py`. However, the last test class `Test___call____visual` from `test_regrid.py` contains visual (`check_graphic`) tests, which are certainly of value and shouldn't be purged.

The question is, where should they live?

They certainly aren't unit tests, so I've opted to plonk them in `tests/integration`. This is a first, as we don't have any other visual integration tests. Are we happy to do this? Or do we need to consider a separate classification of visual integration type tests?

All thoughts welcomed, or someone could just merge this and be done with it ... :smile:

### CODE REVIEW

**Comment by bjlittle** [comment]
@rhattersley care to start the bun fight ... (or not)

**Comment by rhattersley** [comment]
I quite like having the visual tests as a sanity check. I don't want to get too hung up on whether they "really" are integration tests, validation tests, system tests, visual tests, etc, etc. So I'm :+1: for just putting them in the integration test area as long as they're still quick, simple, test something useful, etc. At least that way we know we've taken a look at them and deicded they're still useful! :+1: 

I would change some of the names however. I don't think we need an `analysis` package to put the tests in - just something like `iris.tests.integration.test_regridding` would do fine by me. This tallies with the [developer guide](http://scitools.org.uk/iris/docs/latest/developers_guide/tests.html#integration-tests) that suggests naming according to capabilities.

The test class/method names would benefit from a change. Perhaps one class for TestOSGBToLatLon and one for TestSubsampleGlobal. Each of these could then do both linear and nearest?

Getting rid of `*self.args` would be nice too.

Oh... and a [moon on a stick](https://dibbledabblesdotcom.files.wordpress.com/2012/11/i-want-the-moon-on-a-stick.png) please. :wink:

**Comment by bjlittle** [comment]
:full_moon_with_face:
:pig: 

The best I can do is the moon on a pig ... hope that'll do for now :yum:

**Comment by rhattersley** [comment]
I guess that'll have to do. :anguished:

**Pull request merged**
