### PR TITLE
Added the what's new and updated the copyright years for 2892

### PR DESCRIPTION
**Pull request by pelson**
Necessary follow-up for #2892.

cc: @zklaus

### CODE REVIEW

**Comment by pelson** [comment]
7 days old. harmless PR (apart from fixing the copyright header years again, but it merges cleanly).

@dkillick / @ajdawson would either of you mind just hitting merge if you have a second?

**Comment by dkillick** [comment]
@pelson the copyright year updates were merged in #2932...

**Comment by pelson** [comment]
Yep. 

> but it merges cleanly

😉

**Comment by pelson** [comment]
I guess it now *doesn't* merge cleanly, as master's tests are failing... I was trying to save some Travis cycles... 😄

**Comment by dkillick** [comment]
> I guess it now doesn't merge cleanly, as master's tests are failing...

Argh. Let's fix master's test problems and then I'll look away and press the green button 😉

**Comment by pelson** [comment]
Ping @dkillick. 😉  🙈

**Comment by dkillick** [comment]
@pelson I'm looking away!

**Pull request merged**
