### PR TITLE
Removed class iris.fileformats.rules.CoordAndDims

### PR DESCRIPTION
**Pull request by LukeC92**
This is to address issue #2672 . Wanted to see how this fairs against the Travis tests, further changes may be necessary.

### CODE REVIEW

**Comment by LukeC92** [comment]
This seems to solve issue #2672 and all of the tests pass. However I'd appreciate if somebody could check the changes I've made. For example are the comments I've re-written presented in an acceptable manner.

**Comment by pelson** [comment]
Is is good to go, just needs to be rebased in order to resolve the merge conflicts. @pp-mo - could you work with @LukeC92 on that please?

**Comment by corinnebosley** [comment]
Closes #2672

**Comment by corinnebosley** [comment]
@LukeC92 Good job!

**Pull request merged**
