### PR TITLE
possible new util functions: cube_rollaxis and cube_enforce_dim_position

### PR DESCRIPTION
**Pull request by kwilliams-mo**
This branch has a couple of new functions: cube_rollaxis (which rolls the axes of the cube in a similar way to numpy.rollaxis) and cube_enforce_dim_position (which checks that the position of the data dimension of a given coord is where it is expected to be). 
Submitting this for a preliminary code review to see if you think it would be useful to add them to an Iris release.

### CODE REVIEW

**Comment by ajdawson** [comment]
It looks like the `cube_enforce_dim_position` function is a very thin wrapper around the `cube_rollaxis` function. Do we really need both? Since iris is focused on metadata, I suspect it would be better to only provide one function (perhaps `roll_dimension` or just `rollaxis`) that takes the `name_or_coord` argument, and not bother with one that takes a dimension number. However, if you can provide a use case for `rollaxis` as is then that can be considered.

I will do a more thorough review of the code once this detail is discussed.

**Comment by kwilliams-mo** [comment]
Thanks for such a quick response!
I created a function to mimic the behaviour of `np.rollaxis` internally, as I think it makes sense to use the `np.rollaxis` conventions (e.g. which negative values of the keyword `start` are allowed) rather than come up with a new set that might confuse numpy users. I had originally intended to keep this cube_rollaxis function private to `util`, but then thought that maybe if there were users who were used to using `numpy.rollaxis`, they might find it handy to have this function available directly? But am happy to add the underscore to the name again.
Also happy to rename the function(s) to whatever people think is the most intuitive.

**Comment by ajdawson** [comment]
One of the problems with `iris.util` is that there is too much in there and the good stuff often isn't noticed by users who need it. This is my motivation for keeping it uncluttered. 

Keeping in-line with how numpy does things is not necessarily a bad thing, but perhaps we can think of this in a slightly different way. The basic functionality you want to provide seems to be moving a dimension coordinate to a specific slot (i.e. a managed transpose operation, for user convenience). Perhaps we can call a spade a spade and forget about rollaxis here, and provide a function with a signature like:

```python
def move_dimension(cube, name_or_coord, position)
```

that just moves a particular dimension coordinate to a particular position in the cube's dimensions. If it is already in that position the the behaviour can be to do nothing.

**Comment by kwilliams-mo** [comment]
In these latest commits, the `cube_rollaxis` function has been removed and the function `cube_enforce_dim_position` has been rewritten as `move_dimension`.

**Comment by corinnebosley** [comment]
Hi @kwilliams-mo, can you please let me know the status of this ticket?  We are happy to move it forward, but we will need you to rebase and to fill in and send us a [Contributors Licence Agreement](https://scitools.org.uk/documents/cla_form.pdf).  Please see the [SciTools Governance](https://scitools.org.uk/organisation.html#governance) page for more details about this.

**Comment by corinnebosley** [comment]
@kwilliams-mo Can you please let me know if you want to continue this PR?  I am happy to move it forward or close it, but it's been inactive for such a long time that I am inclined to close it unless you tell me otherwise.

**Comment by pelson** [comment]
Unfortunately closing, as this PR has stalled.

**Pull request closed without merging**
