### PR TITLE
Warning for PP fields with lbcode 31323

### LINKED ISSUE #1851: Issue a warning for loading certain UM files with non-standard LBCODE values
#1535 attempted to address this, but that was sidelined owing to a lack of clarity over what values we are liable to misinterpret.

Following discussion of @dkillick and @pelson with concerned parties, it was decided that this should go into 1.9 if at all possible.

### PR DESCRIPTION
**Pull request by dkillick**
Add warning when loading PP files containing any fields with `LBCODE=31323`.

Fixes #1851.

### CODE REVIEW

**Comment by dkillick** [comment]
Turns out a couple of integration tests try to get away with supplying `LBCODE` as a list rather than a `SplittableInt`. However [this change](https://github.com/dkillick/iris/blob/b3d025f50f8b0c2842ff16767db7e2ee4f64d9dd/lib/iris/fileformats/pp_rules.py#L770) requires `LBCODE` be a `SplittableInt`. I'm not a huge fan of this implementation though, so if anyone would like to suggest a better equality test here..?

**Comment by marqh** [comment]
I am not happy at first look with a warning for a particular LBCODE

In principle: if it's wrong, we should do something; I struggle to see the value of a warning.

In this particular case, 31323 seems fairly well defined.  in the UMDP F03 the description indicates that X and Y vectors may be expected, and if they are not provided then functionality may well be reduced.

So, what is the case we are trying to catch here.
Is this a PPField with 

LBCODE==31323 and X and Y exist
or
LBCODE==31323 and X and Y do not exist
?

**Comment by marqh** [comment]
Is this PR hoping to make it into the v1.9.2 release please?
#1909

**Comment by dkillick** [comment]
Actually, this can be superseded by #1893.

**Pull request closed without merging**
