### PR TITLE
New LBFC-CF mappings

### PR DESCRIPTION
**Pull request by trexfeathers**
## 🚀 Pull Request

Linked: SciTools/iris-grib#297 - Julian Heming is aiming for some additional GRIB-to-PP mappings.

I was able to confirm Julian's suggested STASH-LBFC mappings via the [Met Office Codes Registry](https://reference.metoffice.gov.uk/um). We had all the referenced STASH codes in Iris, but were missing some of the LBFC codes.

This is fresh territory for me so I'm not 100% confident. Please can the reviewer be vigilant!

I also need Julian's eyes on this before merging. I don't think he's on GitHub but I will be contacting personally.

Julian: I have not included the following from your suggestion, since they were not in the Met Office Codes Registry:

* Shear vorticity - `m01s20i101`, LBFC `1112`
* Curvature vorticity - `m01s20i102`, LBFC `1113`

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by trexfeathers** [comment]
To do: what's new entry

**Comment by trexfeathers** [comment]
I expect these mappings are all fine. To avoid staleness I propose reviewing and merging at the end of September.

**Comment by trexfeathers** [comment]
Julian has approved this as working for their tests 👍

**Review by bjlittle — APPROVED** [review]
@trexfeathers Awesome, thanks :+1:

**Pull request merged**
