### PR TITLE
Add dask-array as a requirement when pip installing.

### LINKED ISSUE #2994: add toolz as explicit dependency in installation docs
`toolz` is a dependency of `dask`, but only an "extras" dependency (per https://github.com/dask/dask/blob/master/setup.py). Although I am not familiar with dask, I assume from this it is possible to have an otherwise working version of `dask` without the extras, in which case `toolz` would not be needed -- but because iris uses `dask.array`, it is needed for iris.

Therefore it would be helpful if the iris installation documentation at http://scitools.org.uk/iris/docs/latest/installing.html explicitly listed toolz as one of the requirements.

### PR DESCRIPTION
**Pull request by pelson**
Closes #2994.

### CODE REVIEW

**Comment by bjlittle** [comment]
@pelson You're all over these `test__repr__ (iris.tests.unit.coords.test_CellMeasure.Tests)` and `test__str__ (iris.tests.unit.coords.test_CellMeasure.Tests)` failures...

Ping me on the fix :wink:

**Comment by pelson** [comment]
Waiting on #3037.

**Comment by bjlittle** [comment]
Ping @pelson 

Fancy doing a rebase?

**Comment by pelson** [comment]
Done

**Pull request merged**
