### PR TITLE
Bump version to 1.13.0

### PR DESCRIPTION
**Pull request by lbdreyer**
I *believe* these are the only version numbers I have to update.

### CODE REVIEW

**Comment by lbdreyer** [comment]
After this is merged, I will build the docs and push them up as a PR to the scitools.org.uk repo (similar to [this PR](https://github.com/SciTools/scitools.org.uk/pull/147)). Once that's merged it will update `http://scitools.org.uk/iris` and then we will be ready to tag the release.

**Comment by corinnebosley** [comment]
@lbdreyer I can't find any more '1.12's anywhere.  Happy to merge when tests pass.

**Comment by corinnebosley** [comment]
@lbdreyer Is there a reason that the default tests for python 3 haven't started when all the rest have finished?

**Comment by corinnebosley** [comment]
@lbdreyer Scrub that, they've started now.

**Pull request merged**
