### PR TITLE
Initial addition of windows tests to ci

### PR DESCRIPTION
**Pull request by wjbenfold**
### Description

Adds Windows tests to CI (see issue #4336)

Changes made to .cirrus.yml to include extra tests for python 3.7 and 3.8 on Windows.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by wjbenfold** [comment]
Would mark as WIP but I believe that prevents the CI that I'm trying to test, so not doing so

**Comment by tkknight** [comment]
Suggest to disable/comment out the non windows test to speed up for CI testing.  Also see if you can run the windows tests locally first if possible.

**Comment by bjlittle** [comment]
@wjbenfold Marking a PR as `draft` shouldn't stop CI. It hasn't for me in the past :thinking:

**Comment by trexfeathers** [comment]
I don't know if this is true or not, but if Cirrus is turning out to be a big blocker I'd like to draw your attention to #4193.

**Comment by jamesp** [comment]
@wjbenfold I'm hugely impressed with the way you've approached this (ever-expanding) problem, clearly an iceberg! 

Looking at the test failures there is a bunch we can already learn about how we both write iris and how we test it. 
e.g. int32 vs int64. Should these errors be fixed by making iris enforce loading data in the same way (a bunch of infrastructure code to support multiple os that is entirely orthogonal to the problem domain) or should our tests be more tolerant of differences in defaults in the underlying os?

I think it's worth a write-up of what you've discovered (a lot!). There may be quick wins in here the rest of the dev team could jump in and act on to help you over the next hurdle.  Great work.

**Comment by wjbenfold** [comment]
A writeup now exists in confluence of the understanding gained

**Pull request closed without merging**
