### PR TITLE
Remove deprecated PP legacy_custom_rules

### PR DESCRIPTION
**Pull request by dkillick**
The `legacy_custom_rules` in `iris.fileformats.rules` were deprecated in v1.9 and made life unnecessarily difficult in #2059. As the functionality has served its deprecation period, let's just remove it for v1.10.

### CODE REVIEW

**Comment by dkillick** [comment]
@bjlittle FYI it's just pesky timeout exceptions that are now stopping the tests from passing :unamused:

**Comment by marqh** [comment]
Hi @dkillick 

what is the purpose of the file:
.idea/uiDesigner.xml
please?

**Comment by dkillick** [comment]
@marqh that's a file for an IDE, which should not have been included in the commit. Frankly, I'm surprised it was; I'll get rid of it.

**Comment by marqh** [comment]
> The legacy_custom_rules in iris.fileformats.rules were deprecated in v1.9 and made life unnecessarily difficult in #2059. As the functionality has served its deprecation period, let's just remove it for v1.10.

I think this may be a bit hasty.  There is user feedback regarding use of this feature which we are managing.
It may be less disruptive to remove this at a later version than 1.10.
I'm not sure about this, but I think we should consider it

**Comment by pelson** [comment]
@dkillick - I think we need to understand where this one is at. Do we need it for 2.0? Can we close this PR altogether? etc.
Would you mind providing a status update?

**Comment by dkillick** [comment]
The `legacy_custom_rules` were actually removed in #2778... think this is done.

**Pull request closed without merging**
