### PR TITLE
Add per-option explanatory string to warning for deprecated FUTURE options.

### PR DESCRIPTION
**Pull request by pp-mo**
In response to #2105 

I'm not really committed to this, let's see who likes it / not.

### CODE REVIEW

**Comment by rhattersley** [comment]
I'm +0 ... using a mapping seems a little premature since there's only one entry, but it's not a big deal. It's certainly better than not having a verbose message. :smile:

**Comment by pp-mo** [comment]
> a little premature since there's only one entry

There will be a whole bunch of them in v2.0, of course, so I thought I'd just tackle it now.

**Comment by rhattersley** [comment]
> ... I thought I'd just tackle it now

Sounds like an epitaph. :stuck_out_tongue_winking_eye:

**Comment by marqh** [comment]
this looks fine to me; i'd be happy for this to be a pattern which we can use as we require it

**Comment by marqh** [comment]
however, this PR is targeting master, whilst within the 1.10 milestone

if this is a1.10 change, please may you target the v1.10.x branch @pp-mo

**Comment by QuLogic** [comment]
> @pp-mo changed the base branch to `SciTools:v1.10.x` from `SciTools:master`

Whoa, hold on, did GitHub finally fix this?

**Pull request merged**
