### PR TITLE
Remove Cube module deprecations

### LINKED ISSUE #2653: Remove deprecated `cube.regridded`
A cube has an 'analysis routine' called `regridded` that was deprecated in 1.10

https://github.com/SciTools/iris/blob/master/lib/iris/cube.py#L3183

### PR DESCRIPTION
**Pull request by dkillick**
Remove the single deprecation in the Cube module: `cube.regridded`.

Fixes #2653 and replaces #2694

### CODE REVIEW

**Comment by LukeC92** [comment]
Almost all of the Travis job failures are due to errors relating to the sudden absence of the 'regridded' attribute. The only exception is job 7370.1 which has a failed PEP8 conformity test. Job 7370.1 also has 2 TimeOutExceptions.

**Comment by corinnebosley** [comment]
Wow there are a lot of tests that use Cube.regridded....

**Comment by corinnebosley** [comment]
@dkillick Looks like you've just got a pep8 failure because the test file 'iris.tests.test_coding_standards.TestCodeFormat' is still pointing to a file which isn't there any more.  I found it on line 129 of that testing module.

**Comment by dkillick** [comment]
@corinnebosley let's hope this change gets the green tick for this PR!

**Comment by dkillick** [comment]
@corinnebosley woop another green tick! :smile:

**Comment by corinnebosley** [comment]
Yayyy!

**Pull request merged**
