### PR TITLE
Draft whatsnew for 2.0a0.

### PR DESCRIPTION
**Pull request by bjlittle**
First draft proposal for the pre-release `whatsnew` ... most likely needs some tweaking and further additions ...

### CODE REVIEW

**Comment by pelson** [comment]
What is the relationship between this and #2596?

**Comment by pp-mo** [comment]
> What is the relationship between this and #2596?

I think it intends to simply subsume + replace it.

**Comment by pp-mo** [comment]
In @bjlittle absence, I have just finished refining this content according to my own ideas
My suggestions here : https://github.com/bjlittle/iris/pull/21
This includes "solutions" to my comments above.  

That is presented as a PR-to-this-PR.
Which might be clearer, depending on your familiarity in this original version.
If not, its simple to just replace this instead.

**Comment by pelson** [comment]
@pp-mo & @bjlittle - let's try to avoid a big-bang on this. @pp-mo - would you be happy to merge this as is, and to put forward your amendments as a straight PR on master?

**Comment by pp-mo** [comment]
> @pelson would you be happy to merge this as is, and to put forward your amendments as a straight PR on master?

Good idea I think : here goes...

**Comment by pp-mo** [comment]
> amendments as a straight PR on master?

It's now here : #2627

**Pull request merged**
