### PR TITLE
Updated version to v1.8.1.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by ajdawson** [comment]
@pelson - Can I ask you to take a look at #1690 before a release is actually tagged, also #1692 I think.

**Comment by ajdawson** [comment]
Too late I guess then @pelson? #1690 is even in the milestone...

**Comment by pelson** [comment]
> Too late I guess then @pelson? #1690 is even in the milestone...

Ah - I've completely messed up there. I looked in the GH interface at the v1.8.1 milestone and it was empty - my mistake as I was looking [at issues](https://github.com/SciTools/iris/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.8.1) and apparently that doesn't include PRs.

I'll make sure that the docs we build have #1690 in them, even if the actual source for v1.8.1 doesn't have the change (but v1.8.x does).

**Comment by ajdawson** [comment]
Ah OK no worries. I always go for the milestones tab and then select the one I want which shows both. The interface will probably have changed by the next time this is done anyway!

**Comment by pelson** [comment]
> The interface will probably have changed by the next time this is done anyway!

I hope not!  :)
I've got high hopes for drastically shortening our release cycles - I'm just lacking the time to implement them! :watch:

**Comment by ajdawson** [comment]
>I've got high hopes for drastically shortening our release cycles

I'm all for that!

**Pull request merged**
