### PR TITLE
Add NETCDF4_CLASSIC to the check for formats that don't support int64…

### PR DESCRIPTION
**Pull request by MartinDix**
… and uint

### CODE REVIEW

**Comment by ajdawson** [comment]
Thanks @MartinDix, looks good except for a bit of trailing whitespace on the end of line 1247. Once that is gone this is good to go. Feel free to amend the existing commit if you want.

You'll also need to sign the CLA document and return it to the Met Office before your contribution can be merged: http://scitools.org.uk/documents/cla_form.pdf

**Comment by ajdawson** [comment]
@MartinDix - If you can send in a completed CLA and fix the white-space issue we can get this merged.

**Comment by pelson** [comment]
@MartinDix - I'm trying to round off a 2.0 release of Iris, and would be happy to merge this. Any change you could send over a CLA and rebase this PR? With that done, we can merge. 👍

**Comment by pelson** [comment]
The missing context (from the NetCDF docs) was: 

> Currently, netCDF classic and 64-bit offset formats offer a limited number of external numeric data types: 8-, 16-, 32-bit integers, or 32- or 64-bit floating-point numbers. (The netCDF-4 format adds 64-bit integer types and unsigned integer types.)

**Comment by pelson** [comment]
@MartinDix - would really appreciate a CLA for this change. Having said that, given the limited extent of the change, in this case, I think we can simply merge at this point.

**Pull request merged**
