### PR TITLE
unit update

### PR DESCRIPTION
**Pull request by marqh**
returning change from 
https://github.com/metarelate/metOcean/issues/64

to the um_cf_map

### CODE REVIEW

**Comment by marqh** [comment]
@rhattersley closing the loop, though I think that
https://github.com/SciTools/iris/pull/1750
suggests it's not something we're waiting on

**Comment by rhattersley** [comment]
Thanks @marqh. Would you mind adding a bugfix "What's new" entry.

**Comment by marqh** [comment]
hmm, a last minute comment pushed me back to STASH and it looks like the mistake is in the standard_name, not the units.

The units are correct, but the name maps to a change over a timestep, not a tendency, hence the unit of m s-1

I have updated the change, the tests and added a what's new entry

**Comment by rhattersley** [comment]
The "change_over_time_..." prefix and the corresponding lack of "s-1" component seems to be well established in the CF standard names, so it all looks :+1:

**Pull request merged**
