### PR TITLE
Ucube utils

### PR DESCRIPTION
**Pull request by pp-mo**
Tidied and pulled in the code that I wrote for the recent demo, mainly supporting the mesh subset operations based on gridded/UGRID.

I included everything from there, and added at least one simple test for each function.

This needs a new image test-iris-imagehash *and* a new testfile in iris-test-data,
so it won't pass tests until both of these PRs are in :
  * https://github.com/SciTools/test-iris-imagehash/pull/32
  * https://github.com/SciTools/iris-test-data/pull/57

**WIP**
still todo: fix iris-test-data SHA in Travis, when https://github.com/SciTools/iris-test-data/pull/57 is done.

### CODE REVIEW

**Comment by pp-mo** [comment]
I don't understand why no tests are running.

@trexfeathers @bjlittle @lbdreyer do we know why this is ?

Tests ***are*** still running on my fork : https://travis-ci.org/github/pp-mo/iris/builds/669350910
(failing because iris-test-data + test-iris-imagehash need updating)

**Comment by lbdreyer** [comment]
I think they are running (see [here](https://travis-ci.org/github/SciTools/iris/builds/669353679?utm_medium=notification&utm_source=github_status) for the results of the travis run for this PR), but for some reason travis isn't sending the results back to github?

**Comment by pp-mo** [comment]
> @lbdreyer I think they are running ... travis isn't sending the results back to github?

Thanks @lbdreyer 
That is somewhat comforting, but still pretty odd.
I'd guess that GitHub would be at fault, since it is at least triggering them (if I understand how it works, which I don't)
I'll look into it ..

**Comment by pp-mo** [comment]
Update: the testing problem is not a "glitch".
New PR with extra commit on a different branch-name just repeats the problem : #3693
Plus, same is happening in test-iris-imagehash : https://github.com/SciTools/test-iris-imagehash/pull/32#issuecomment-607195569

**Comment by pp-mo** [comment]
Created PR with small changes to this, in own repo (since merged, so appears here) : https://github.com/pp-mo/iris/pull/60

In this, on own fork, same thing of the PR not linking to the Travis tests.

**Comment by pp-mo** [comment]
> https://github.com/pp-mo/iris/pull/60 on own fork, same thing of the PR not linking to the Travis tests.

Something has changed, I'm struggling to t know how to chase this...
dask+pandas are not having these problems,
But our own test-iris-imagehash is, even though it has a totally different + much simpler `.travis.yml`.
I guess we may need to look for something similar between iris + test-iris-imagehash travis configs?

**Comment by trexfeathers** [comment]
> pp-mo#60 on own fork, same thing of the PR not linking to the Travis tests.
> 
> Something has changed, I'm struggling to t know how to chase this...
> dask+pandas Github projects/repos are not having these problems,
> But our own test-iris-imagehash is, even though it has a totally different + much simpler .travis.yml.
> I guess we may need to look for something similar between iris + test-iris-imagehash travis configs?

I just re-ran the Travis tests and now I've got that information back on this PR. In order to re-run the tests I had to log out of Travis and log back in since the restart button wasn't there the first time. I don't know whether it was the log-in or the re-run that has fixed it for me.

**Comment by pp-mo** [comment]
> I just re-ran the Travis tests and now I've got that information back on this PR

Thanks for persevering -- this is great news!  
I was really worried that fixing this might long+complicated.

**Comment by pp-mo** [comment]
In theory, if I now just install the latest iris-test-data SHA in .travis.yml, this will then pass ...

**Comment by trexfeathers** [comment]
This all looks great, thanks @pp-mo!

**Pull request merged**
