### PR TITLE
bug in coord slice with step -1 and bounds 

### PR DESCRIPTION
**Pull request by jkettleb**
Hello,

this is more of a bug report than a pull request.  I've added a couple of failing tests that I think should pass.  Could you review and see if you agree?

This is likely propagate into other analysis - cube slice with -1 step (I think) would suffer from the same issue... which could give problems for area weighted regrid.

I don't feel confident of putting in a fix - particularly in quick time - I think there could be some issues I'd need to research, and I'm not sure when I'll have time.
1. can the 'cell/nbounds' dimension of a bounds array be anything other than the inner most (furthest left) dimension
2. I think the correct behaviour for 1d coords is clear - reverse the values along the 'cell/nbounds' dimension.  I'd have to think how this works for 2 (or more) dimensioned aux coords.

Jamie

### CODE REVIEW

**Comment by ajdawson** [comment]
These issues are the subject of the long-standing #423, see there for a short discussion.

**Comment by jkettleb** [comment]
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#cell-boundaries suggests that what I called the 'cell/bounds' dimension is the most rapidly varying and so is the most leftmost.  I think this makes a fix for this in the 1d coordinate case reasonably straight forward.

I still don't have time, at the moment, get my head round the CF discussion of 'Bounds for 2-D coordinate variables with 4-sided cells'.

**Comment by pelson** [comment]
:+1: for adding a test to highlight the problem. Thanks @jkettleb!

**Comment by cpelley** [comment]
I think applying a convention could be useful.  Imagine concatenating two datasets together, one with bounds oriented in one direction and the other with the bounds in the other direction.
The two datasets right now simply cannot be concatenated together since the resulting 
bounds array of the concatenated result would not be strictly monotonic (i.e. no longer described by a dimension coordinate).
One solution is to simply have the coordinates demoted to auxiliary coordinates (ignoring the fact for now that concatenation does not support concatenation over dimensions which have no dimension coordinate).  However, might the better approach be to assign a convention on the orientation of bounds?

Would there be harm in applying a chosen convention in iris?

**Comment by pelson** [comment]
Thanks for this PR. I'll close it in favour of the bug report in #423 as there will need to be some development work to arrive at a fix anyway.

👍 for raising

**Pull request closed without merging**
