### PR TITLE
whatsnew - using the author github id

### PR DESCRIPTION
**Pull request by bjlittle**
### Description
This PR makes a simple change to the **latest** `whatsnew` to opt to using and citing pull-request authors using their GitHub ID.

On reflection, this might be a better long term approach as:

- It's one less step for the person writing the `whatsnew` entry, as they no longer have to "look up" the authors profile to determine whether their GitHub name matches their GitHub ID
- The GitHub ID is how people are commonly referred to within the GitHub community, so it's easy to cross-reference the GitHub ID with their work on GitHub or locally within a repo, but this is not true for the GitHub name
- We are less likely to make an error when citing the GitHub ID

A built version of this pull-request is available on `readthedocs`, to easily view the rendered changes:
- [latest whatsnew](https://my-iris.readthedocs.io/en/latest/whatsnew/latest.html)
- [Writing a whatsnew contribution](https://my-iris.readthedocs.io/en/latest/developers_guide/documenting/whats_new_contributions.html#writing-a-contribution)

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/pulls.html#the-iris-check-list)

### CODE REVIEW

**Comment by bjlittle** [comment]
ping @SciTools/iris-devs

**Comment by rcomer** [comment]
It also means they can all be consistent, as everyone has a GitHub ID but not everyone has a GitHub name 👍 .

**Comment by trexfeathers** [comment]
Thanks @bjlittle, LGTM

**Review by trexfeathers — APPROVED** [review]

**Comment by bjlittle** [comment]
@trexfeathers Awesome, thanks!

**Pull request merged**
