### PR TITLE
Explicitly add defaults channel.

### PR DESCRIPTION
**Pull request by bjlittle**
@ajdawson reference #2051 and  https://github.com/conda/conda/issues/2675

### CODE REVIEW

**Comment by bjlittle** [comment]
@ajdawson @dkillick @marqh :pray:

**Comment by dkillick** [comment]
@bjlittle stick a comment in as well describing why it's now necessary to do so oddball a thing and I'm :+1:

**Comment by bjlittle** [comment]
Will do, thanks!

**Comment by bjlittle** [comment]
Good to go @dkillick ...

**Comment by bjlittle** [comment]
Nudge @dkillick ...

**Comment by dkillick** [comment]
Sorry! Meeting...

**Comment by dkillick** [comment]
Boom :boom: It's in. Thanks @bjlittle!

**Pull request merged**
