### PR TITLE
Added warning about data loss from overwriting a source file.

### PR DESCRIPTION
**Pull request by mo-g**
'Backport' from #1683. @pelson, please could you merge?

### CODE REVIEW

**Comment by pelson** [comment]
:+1:

**Comment by ajdawson** [comment]
BTW @mo-g, I can merge these PRs too, that is why I assigned myself to #1683.

**Comment by mo-g** [comment]
Sorry! No offence meant, I'm still getting to know people!

**Comment by ajdawson** [comment]
OK looks ready to go, cheers @mo-g.

**Pull request merged**
