### PR TITLE
Bump the version for the release candidate.

### PR DESCRIPTION
**Pull request by bjlittle**
- [ ] Optional #1601 ?
- [x] Requires #1604
* cherry-picked master 02cdf3ede687b829cbe964c2132266983c71340e

### CODE REVIEW

**Comment by rhattersley** [comment]
I have a fix for #1593 in-bound ...

**Comment by bjlittle** [comment]
Great! I'm not going to tag until we all agree ...

**Comment by rhattersley** [comment]
> I have a fix for #1593 in-bound ...

#1604

**Comment by rhattersley** [comment]
@bjlittle - sorry to be the bearer of bad news, but the copyright period needs updating. :unamused:

**Comment by bjlittle** [comment]
:scream:

**Pull request merged**
