### PR TITLE
removed units for time coords due to not matching autoticks

### PR DESCRIPTION
**Pull request by acchamber**
### Description
Draft pull request fixing #5426 
Implemented Ruth's suggestion and removed automatic units in axis titles for Time reference units entirely - can't ensure they line up with the autoticks. 

Draft because waiting on #5482 to change the image tests to match before pushing and asking for review

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by rcomer** [comment]
Does this make the change from #616 redundant?  If so it could be reverted.

**Comment by acchamber** [comment]
I think it does - tests should still pass. Once #5482 fixes the idiff tests I'll check if it can be removed safely.

**Comment by trexfeathers** [comment]
@acchamber now you have less time for SciTools things, what do you think about the status of this PR?

**Comment by acchamber** [comment]
Trying to rebuild my environment has resulted in environment issues when trying to run idiff.py to update the test results - it can't find iris on import, and I'm not sure why. The code should be fine, but until the test results can be updated it's not ready.

**Comment by rcomer** [comment]
> I will not be doing any further work on this PR

I have pulled this change into #5561

**Pull request closed without merging**
