### PR TITLE
NEP29 and NumPy v2 pins

### PR DESCRIPTION
**Pull request by trexfeathers**
### Description

- [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html)
  - `2024-06-22`: NumPy `>=1.24`
  - 0289e5680b208d02015be3a76715e8435002c4c0
- [NumPy v2](https://numpy.org/doc/stable/release/2.0.0-notes.html)
  - #6035 has proven that it will be a medium/large task to get all our tests supporting NumPy v2
  - We expect to have some slots to work on this for Iris v3.11 - #5571
  - So we need a pin in the meantime, and I expect also a patch release

The lock files already fit between these two pins so I have not refreshed those.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

---
Add any of the below labels to trigger actions on this PR:

- https://github.com/SciTools/iris/labels/benchmark_this

### CODE REVIEW

**Comment by trexfeathers** [comment]
As well as getting the v2 pin onto `main`, which will set us up correctly for future testing then future releasing, note that I am intending to cut a `3.9.0post0` release. Once this PR is merged, I will therefore be cherry-picking the squash commit onto the `v3.9.x` release branch.

**Review by bjlittle — APPROVED** [review]

**Comment by bjlittle** [comment]
> As well as getting the v2 pin onto `main`, which will set us up correctly for future testing then future releasing, note that I am also intending to cut a `3.9.0post0` release. Once this PR is merged, I will therefore be cherry-picking the squash commit onto the `v3.9.x` release branch.

Yup, good move.

Remember to update the community on https://github.com/SciTools/iris/discussions/5850 with our intentions 👍

**Comment by trexfeathers** [comment]
Thanks @bjlittle!

**Comment by trexfeathers** [comment]
> > As well as getting the v2 pin onto `main`, which will set us up correctly for future testing then future releasing, note that I am also intending to cut a `3.9.0post0` release. Once this PR is merged, I will therefore be cherry-picking the squash commit onto the `v3.9.x` release branch.
> 
> Yup, good move.
> 
> Remember to update the community on #5850 with our intentions 👍

I've basically run out of time before we cut the next release candidate anyway ([see 3.10](https://github.com/SciTools/iris/discussions/5570)) - I'm unavailable to work on this next week. Based on lack of user feedback so far the impact is limited. Discussed with @SciTools/peloton this morning and this seemed acceptable to those present.

**Pull request merged**
