### PR TITLE
Gallery: update COP maps example 

### PR DESCRIPTION
**Pull request by rcomer**
### Description
Some bits of this example weren't doing what its comments said it was doing.  Other bits just didn't make sense to me:

* The callback function was supposed to get the "experiment" from the directory name, but the files are all in the top level `sample_data` directory, so this added coordinate was the same regardless of file.  Part of the reason this hasn't been noticed before was probably because the "experiment" coordinate never got used after it was added.  I've updated the callback to get the experiment out of the filename.  Also loaded the two files together, then extracted the cubes in a loop.  This is a little contrived, but gives us an excuse to use the coordinate we went to the trouble of adding with the callback.  It's also the first time I've used `CubeList.extract_cube` (new at Iris v3!)

* Looping through slices of the cubes doesn't make sense to me as there is only one latitude-longitude slice.  I have instead looped through the experiments as this reduces repeated code.

* The `suptitle` comment claimed it was using the date in the format "MonthName Year", when it was actually just "Year" 🤷‍♀️

* For the colour array, I've used `np.stack` instead of `np.array` and `.T` because, well, I just like `np.stack`.

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by rcomer** [comment]
Alternatively, the callback function could just be removed.  The plot will obviously work fine without it.  For a user who is actively looking for advice on writing callback functions, I'm not sure that the gallery would be the obvious place to look, as it's really about plotting.

**Comment by rcomer** [comment]
Rebased 💃

**Comment by jamesp** [comment]
Hi @rcomer, I'm going to take a look at this PR for you.  The docs have had a bit of a re-org over the last week, would you mind rebasing this PR on the latest main?  thanks!

**Comment by rcomer** [comment]
Thanks @jamesp, I have now rebased and think everything is in order.

**Review by jamesp — APPROVED** [review]
Looks good to me @rcomer, thanks for the contribution! 👍

**Comment by jamesp** [comment]
> Alternatively, the callback function could just be removed. The plot will obviously work fine without it. For a user who is actively looking for advice on writing callback functions, I'm not sure that the gallery would be the obvious place to look, as it's really about plotting.

As a new user getting to know iris, I found the callback use helpful.  Up until then I didn't realise it was possible so I wouldn't have even known what to search for!  It's a good addition to the examples.

**Comment by rcomer** [comment]
Thanks @jamesp, great to have a fresh pair of eyes on this 👀

**Pull request merged**
