### PR TITLE
Remove BitwiseInt class and tests thereof

### LINKED ISSUE #2646: Remove deprecated Class `iris.fileformats.pp.BitwiseInt`
The class `iris.fileformats.pp.BitwiseInt` was deprecated in Iris 1.8.

https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L547

### PR DESCRIPTION
**Pull request by dkillick**
Remove the deprecated class `iris.fileformats.pp.BitwiseInt`. As @lbdreyer pointed out, this class is used as a base class for `_LBProc`, so I've also updated the inheritance of that class. Removed tests.

Fixes #2646

### CODE REVIEW

**Comment by corinnebosley** [comment]
@dkillick Looks like an example cube in userguide/loading_iris_cubes.rst has gained the attribute:
ukmo__process_flags: ()

**Comment by corinnebosley** [comment]
@dkillick Well there's some cml chaos happening now.  This PR is causing some weird problems.

**Comment by dkillick** [comment]
> This PR is causing some weird problems

@corinnebosley you're telling me!

**Comment by dkillick** [comment]
@corinnebosley other than a heap of test timeouts all the tests for this change are passing now too :taco: 

Do you want me to spin the timing out job or are you happy as-is?

**Comment by corinnebosley** [comment]
@dkillick I'm gonna respin it for good measure.  I am sure it will pass but I don't like unfinished jobs.  They make me tense.

**Comment by corinnebosley** [comment]
Ta-dah!

**Comment by dkillick** [comment]
@corinnebosley now the tests have passed (!) but the result has not been updated here...

**Comment by dkillick** [comment]
Woop!

**Pull request merged**
