### PR TITLE
Update tests.rst

### PR DESCRIPTION
**Pull request by bascrezee**
Added one line on how to test. This is mentioned in the Iris Check List in pulls.rst list, but would be good to have it here as well (useful for new contributors like me).

### CODE REVIEW

**Comment by bascrezee** [comment]
Hi @pelson, thanks for your message! I submitted a CLA to the mentioned e-mail address a few days ago, I'm awaiting a reply.

**Comment by bascrezee** [comment]
@pelson : I still didn't here back about  my CLA. I submitted my request both to the addresses cla@... and enquiries@... . I will resubmit today. Could you maybe check what's going wrong here? Or maybe @bjlittle can help?

**Comment by dkillick** [comment]
Hi @bascrezee – very sorry about the delay processing your CLA; this was entirely our fault. Still, we've got it all done now and that means that the CLA checker bot is now happy 🙂 

It looks like you've picked up some test failures that don't seem to be related to the change you've proposed here, so I'm going to restart the tests and see if that fixes it.

**Comment by pp-mo** [comment]
> you've picked up some test failures that don't seem to be related to the change you've proposed here

That was a problem with #3177, which was reverted in #3178.
Not a problem for this, I'll just merge.

Welcome + thanks @bascrezee !

**Pull request merged**
